### ISSUE TITLE
Provide (endorse?) MSYS2 Windows distribution

### ISSUE THREAD

**Issue by raehik** [wbhart/flint2#1001]
Hi, huge thanks for the library. I help maintain a Haskell project [CamFort](https://github.com/camfort/camfort) that uses FLINT, and we're trying to build it for Windows. I was unable to find a Windows distribution provider for FLINT (I think I saw some old stuff, but nothing maintained). Eventually after ironing out the issues, I realized it might be sensible to throw it on MSYS2 for others to benefit. Means anyone trying to build a project dependent on FLINT on Windows has a well-supported distribution on hand, rather than needing to build from source.

Would I have the maintainers' blessings to do this? I have a draft PR at https://github.com/raehik/MINGW-packages/pull/1 (I'll make a PR against the actual repo in a couple days). I do nothing special, lots adapted from the MSYS2 buildscripts for GMP, OpenBLAS.

To be clear, this shouldn't be any extra hassle on development side, & I'm down as the package maintainer.

**Comment by wbhart** [comment]
I have no objection to this. Flint is pretty widely distributed. In fact I thought I could find a flint on MSYS2 somewhere already, but so far I didn't, so this would be a welcome contribution to the community. Thanks for taking it on.

**Comment by raehik** [comment]
Awesome! I'll see to getting it merged (https://github.com/msys2/MINGW-packages/pull/9629). When it's done, should we note that it's packaged for Windows via MSYS somewhere on the site? I'm happy to close this issue or keep it open for tracking that.

**Comment by raehik** [comment]
It's merged! I'm using it successfully in a CI script. Here's the package page: https://packages.msys2.org/base/mingw-w64-flint

**Comment by wbhart** [comment]
I've added a link to the Flint downloads page:

http://flintlib.org/downloads.html

I also added your name to the authors page:

http://flintlib.org/authors.html

Thanks once again!
