### ISSUE TITLE
fmpq_poly_xgcd is broken, giving wrong results

### ISSUE THREAD

**Issue by thofma** [wbhart/flint2#1014]
```julia
julia> Qx, x = QQ["x"]
(Univariate Polynomial Ring in x over Rational Field, x)

julia> p, q = (x^512 - 1, x^512 + 1)
(x^512 - 1, x^512 + 1)

julia> u, v, w = gcdx(p, q)
(1, -1//2, -1//4*x^512 + 1//2)

julia> u == v * p + w * q
false
```

**Comment by wbhart** [comment]
The bug is now fixed, but I still have to do another release on the 2.8 branch so we can get the fix out there. But that requires fixing the other bugs reported for 2.8, in particular the documentation issue if we can figure it out.

**Comment by wbhart** [comment]
Good question. I guess we better check.

**Comment by wbhart** [comment]
This existed in fmpz_mod_poly_xgcd_hgcd but not in the finite fields modules, where we apparently don't have hgcd.
