### ISSUE TITLE
M1 mac make check error

### ISSUE THREAD

**Issue by math-gout** [wbhart/flint2#1023]
Configuring and building flint-2.8.3 works just fine on Apple Silicon, but when I run ```make check``` I get this error :
```
sdiv_qrnnd....FAIL: check identity
nh = 10004721567595360, nl = 81
d = -9223372036854775808
q = 0
r = 1
ph = 0, pl = 1
make[1]: *** [build/test/t-sdiv_qrnnd_RUN] Abort trap: 6
make: *** [check] Error 2
```

But if I do a ```git clone https://github.com/wbhart/flint2``` then I don't get this error.

**Comment by tthsqe12** [comment]
Compiler bug. Are you getting the work around here?
https://github.com/wbhart/flint2/pull/1013

**Comment by math-gout** [comment]
My compiler is Apple clang version 13.0.0 (clang-1300.0.29.3)

**Comment by tthsqe12** [comment]
Cool - the flint compiler hall of shame now has 3 entries. Surprising such an elementary compiler bug didn't get fixed from 12 to 13.

**Comment by math-gout** [comment]
So, this is a compiler bug that you found a work around for but hasn't yet been released to flint ?

**Comment by tthsqe12** [comment]
Apparently @wbhart is putting it into 2.8.4. It didn't get into 2.8.3.

**Comment by math-gout** [comment]
Ok thanks for your help and for replying so quickly !

**Comment by wbhart** [comment]
That's correct, I did. See https://github.com/wbhart/flint2/pull/1013

**Comment by wbhart** [comment]
@math-gout Is there any chance you could confirm that the flint-2.8 branch on my GitHub repository [1] does not have this problem. The issue should also not exist in trunk, but it would actually be more helpful to get some testing of the flint-2.8 branch (which will become the 2.8.4 release soon).

https://github.com/wbhart/flint2

**Comment by wbhart** [comment]
I see you tested this with trunk, so I'm going to assume this is fixed in 2.8.4 which I just released. Let us know if not.

**Comment by math-gout** [comment]
Just compiled flint-2.8.4, all checks passed without any issues.

**Comment by wbhart** [comment]
Thanks so much for testing!!
