### ISSUE TITLE
`gmp_printf` does not print correctly with `%wu`

### ISSUE THREAD

**Issue by albinahlback** [wbhart/flint2#1034]
Looking at https://gmplib.org/manual/Formatted-Output-Strings, it seems like `w` should be replaced by `M`.

**Comment by wbhart** [comment]
Can you be more specific about what does not print correctly. We use this all over flint, so I'm a bit sceptical.

I won't be replacing our formatted output options for machine words with the ones GMP uses. Ours have been in place for many years (about 11 I think) and it would be a terrible burden on our users to change it now.

I don't even know if ours predate those used by GMP. They were added for Windows support in Flint.

**Comment by albinahlback** [comment]
Sorry, I meant ´gmp_printf`. This appears in `fmpz/test/t-pow_ui.c` for example.

**Comment by wbhart** [comment]
Oh yes, that shouldn't be used to print flint limbs. That's a bug.

**Comment by wbhart** [comment]
Yeah it looks like when printing an slong x, we can use gmp_printf("%Md", x), as this prints a signed value not an unsigned one.

There does not seem to be an equivalent for a ulong x though. That will have to be changed to the usual flint_printf("%wu", x)

I will go through and change the 30+ instances of this in the fmpz test code right now.

**Comment by albinahlback** [comment]
You can simply write `%Mu` for `ulong`. I do not know about the compatibility, but at least it works on my system.

**Comment by wbhart** [comment]
Ah yes, that looks correct. I'll do that instead for all these cases. Much easier. :-)
