### ISSUE TITLE
Replace calling GMP's `mpz_neg(x, x)` with some macro

### ISSUE THREAD

**Issue by albinahlback** [wbhart/flint2#1046]
Calling `mpz_neg(x, x)` is basically calling a slower version of
```c
x->_mp_size = -(x->_mp_size);
```

In order to speed this up, I propose doing the faster version via some macro or inline function. Should this be done? And what should it be called in that case? Perhaps `flint_mpz_neg`?

**Comment by wbhart** [comment]
I think it has to be named so that it indicates it has only one argument instead of the usual two.

**Comment by albinahlback** [comment]
Perhaps
```c
static __inline__
void flint_mpz_neg_self(mpz_ptr res)
{
    res->_mp_size = -res->_mp_size;
}
```
inside `gmpcompat.h`?

**Comment by fredrik-johansson** [comment]
GMP already defines mpz_neg as an inline function in gmp.h:

```
__GMP_EXTERN_INLINE void
mpz_neg (mpz_ptr __gmp_w, mpz_srcptr __gmp_u)
{
  if (__gmp_w != __gmp_u)
    mpz_set (__gmp_w, __gmp_u);
  __gmp_w->_mp_size = - __gmp_w->_mp_size;
}
```

When __gmp_w == __gmp_u, the compiler can eliminate the branch, so mpz_neg(x, x) should be equivalent to the function you propose. Are you saying that this is not the case?

**Comment by albinahlback** [comment]
Didn't see that part of gmp.h. Sorry, will close this.
