### ISSUE TITLE
Inline part of elementary functions

### ISSUE THREAD

**Issue by albinahlback** [wbhart/flint2#1064]
Would it be okay to inline the small fmpz parts of elementary functions (like addition, shifting and multiplication)?

Example:
```c
inline void
fmpz_add(fmpz_t res, fmpz_t a1, fmpz_t a2)
{
    if (!COEFF_IS_MPZ(*a1)
    {
        if (!COEFF_IS_MPZ(*a2))
            fmpz_set_si(f, *a1 + *a2);
        else
            _fmpz_add_mpz_si(res, a2, *a1);
    }
    else
    {
        if (!COEFF_IS_MPZ(*a2))
            _fmpz_add_mpz_si(res, a1, *a2);
        else
            _fmpz_add_mpz_mpz(res, a1, a2);
    }
}

**Comment by fredrik-johansson** [comment]
I'm skeptical. There are cases where you might want to inline an fmpz_add, but in general this just blows up the library size and might lead to instruction cache misses and worse branch prediction. If anything we do too much inlining already in Flint.

**Comment by albinahlback** [comment]
What is an acceptable library size? And how could this introduce worse branch predictions?

**Comment by albinahlback** [comment]
> There's not an absolute size, but smaller is better. That also goes for compilation time, which is already pretty bad for Flint.

I see. Flint appears to be about 50 times larger than GMP, which is fine, but could be a lot better I think. For my ends, I rarely use something else than `fmpz`, `fmpq`, `fmpz_vec` and `fmpz_mat`. Perhaps one make such functions as a base for everything else, since that only should be a small fraction of the entire library. I don't know.

> Let's say you have a function with one branch inside; that's one branch for the branch predictor to learn. If you make 100 copies of the same branch, the predictor has 100 branches to learn, each of which may evict data from cache. I don't know how much of an issue this is with the latest generation of the CPUs, but it's something to be aware of. It's also the kind of effect that can make microbenchmarks misleading.

Good to know, thanks!
