### ISSUE TITLE
Don't support `mpz` with allocation size less than 2

### ISSUE THREAD

**Issue by albinahlback** [wbhart/flint2#1065]
Functions assume that allocation size is always 2 or more.

**Comment by fredrik-johansson** [comment]
I don't think we can assume this even if the memory manager currently always allocates >= 2 limbs. Someone might swap in an mpz allocated outside, and GMP functions could potentially reallocate.

**Comment by albinahlback** [comment]
As per GMP's manual on [memory management](https://gmplib.org/manual/Memory-Management), they state that `mpz_t` variables never reduce their allocated space. I have never seen that implemented in any functions either.

Moreover, if it would be the case that GMP did reallocate to less space than 2 limbs, Flint's memory manager simply would not work at it current state.

But yes, someone could initialize an mpz with less than 2 limbs.
