### ISSUE TITLE
Revise content in FLINT

### ISSUE THREAD

**Issue by albinahlback** [wbhart/flint2#1067]
As the repository get quite large, I think it can be nice to remove some unused functions. Of course one has to see what actually are being used, and if this is a good idea.

These are some modules and functions I think might be relevant:

- `mpf(r)_[vec/mat]`
- ~~`fmpz_one_2exp` as its not documented, and one might use `fmpz_mul_2exp` for this.~~
- ~~`fmpz_xgcd_partial`, is this ever used? Mentions `qfb` module, which I do not know what it is.~~

**Comment by fredrik-johansson** [comment]
mpf(r)_vec/mat are needed for LLL. It's unfortunately a lot of code that is really 100% boilerplate.

It would certainly be nice to have proper generics!

**Comment by fredrik-johansson** [comment]
The qfb module is in https://github.com/wbhart/antic/

**Comment by albinahlback** [comment]
Oh sorry. I think Firefox has stored an older version of the website, as the website seems to be down for me at the moment.

Then it's good to have `fmpz_one_2exp`.

**Comment by albinahlback** [comment]
Hmm, but do you think it's a good idea to revise what is actually being used? I mean, if we are concerned with the library's size, I personally think we should.

**Comment by wbhart** [comment]
Removing a small number of functions is not at all going to help Flint in any way. All the ones you list are in use by someone who needs them. Flint has a number of very important customers (Sage, Macaulay 2, Nemo, Oscar, etc.) We cannot just change the interface and remove functions without a VERY good reason.

**Comment by wbhart** [comment]
Let me be frank. No I do not think it is a good idea.

The only way to reduce the size of Flint would be to modularise it either by splitting it into smaller libraries or by making parts of it compile optionally. Both have rather serious implications for Flint users and there's a huge amount of effort required to actually make it happen. Personally, I think we are stuck with the binary size as it is.

The other way to handle it would be to reduce code duplication somehow. But that would be an extraordinary amount of work. Flint has taken 15 years to write. Nothing we do with it is going to be a quick job.
