### ISSUE TITLE
`alloca.h`

### ISSUE THREAD

**Issue by albinahlback** [wbhart/flint2#1072]
Starting at line 25 in `flint.h`, it says
```c
#if (!defined(BSD) && !defined(__MINGW64__) && !defined(__MINGW32__) && !defined(_MSC_VER)) || defined(__GNU__)
/* MinGW and FreeBSD have alloca, but not alloca.h */
#include <alloca.h>
#endif
```
However, on those Linux systems available to me, all have `alloca.h`, but none has `__GNU__` defined. So is this a typo? Should it say `__GNUC__` instead?

Edit: `__linux__` works for my systems as well

**Comment by wbhart** [comment]
It looks like a typo yes. Feel free to do a PR for this.

**Comment by albinahlback** [comment]
I was thinking wrong. Since my system does not define any of those things, it will include alloca.h.
