### ISSUE TITLE
Creating sparse polynomials is horridly slow

### ISSUE THREAD

**Issue by wbhart** [wbhart/flint2#109]
When creating sparse polynomials we set all the intervening coefficients to zero when adding a zero coefficient beyond the end of the current polynomial. This leads to an O(n^2) runtime.

See this sage-devel discussion for details:

https://groups.google.com/forum/#!topic/sage-devel/6qhW90dgd1k

**Comment by wbhart** [comment]
I have fixed this as follows for fmpz_poly:

* fmpz_poly_set_length and fmpz_poly_truncate now zero coefficients if they are no longer needed
* fmpz_poly_set_coeff_ui/si/fmpz now don't do zeroing
* checked that all ->length = blah are correct (in fmpz_poly) or call fmpz_poly_set_length instead

Unfortunately, this needs to be rolled out to the whole of flint, which is a big job. It's especially hard for nmod_poly, since usually we don't call nmod_poly_set_length, but just set the length directly. This will have to be fixed first, by checking all occurrences of ->length = blah in the module.

I'm pushing this back onto the stack for the next release, since it is too much work to do it all in one release. We have many poly modules which it needs to be done for. The nmod_poly module is the next most important module (used in Sage), followed by fmpz_mod_poly and fmpq_poly. These should be done nexrt, in that order, followed by the remaining poly modules.

**Comment by fredrik-johansson** [comment]
Rather than changing the way fmpz_poly_set_length etc work, isn't it easier to check whether the coefficient is zero in set_coeff_si/ui/fmpz? Something like

    void
    fmpz_poly_set_coeff_si(fmpz_poly_t poly, slong n, slong x)
    {
        if (x == 0)
        {
             if (n >= poly->length)
                return;

            fmpz_zero(poly->coeffs + n);

            if (n == poly->length - 1)  /* only necessary when setting leading coefficient */
                fmpz_poly_normalise(poly);
        }
        else
        {
            fmpz_poly_fit_length(poly, n + 1);
            fmpz_set_si(poly->coeffs + n, x);
        }
    }

This should even be a bit faster than what we have now.

**Comment by wbhart** [comment]
Yeah I guess that could work ok. I'll look into doing that.

**Comment by wbhart** [comment]
I've rolled out a (corrected) version of the above to the modules that didn't handle sparse polys correctly.
