### ISSUE TITLE
Remove no-longer-needed branches and rename tags

### ISSUE THREAD

**Issue by albinahlback** [wbhart/flint2#1092]
In Bash with `bash-completion`, writing `git checkout *double tab*` gives me 200+ possible options for different types of branches/tags. I don't think all of these are necessary. Specifically, they make it really difficult to use completion without any hacking.

Moreover, the names of the tags are inconsistent, and some branches are really meant to be tags.

Because of this, I propose to: 

- [ ] **Remove unnecessary branches.**
    You can remove them on the `origin` repository via `git push --delete origin **branch**`. (To remove them locally you write `git branch -D **branch**`.) Of course, as this repository is owned by an actual individual (as compared to an organization), some personal branches will probably still have to remain.

- [ ] **Make all tag-like branches to an actual tag. Delete all these branches as they will become obsolete.**
- [ ] **Rename all branches to `vMAJOR.MINOR.PATCH(-rcX)`**.
    Or some other good naming scheme. I think `v2.8.0-dev` can be removed completely due to it being [unofficial](https://groups.google.com/g/flint-devel/c/6mRu6041X40). However, I think `v2.8.0-beta1` should be preserved as is. The renaming can be done via
    ```
    git tag new old           # If new_tag is annotated, use "git tag -a new old^{}" instead.
    git tag -d old
    git push origin new :old  # Yes, it is supposed to be a colon there.
    ```
    This will make it very easy to distinguish which versions that are available via git. After this is done, people can run `git pull --prune --tags` to remove the deleted tags on your local system.

**Comment by wbhart** [comment]
Many of the branches do not correspond to something in the main branch and so can't be simply replaced by a tag.

We use actual branches for releases so that development can continue in trunk unimpeded.

**Comment by wbhart** [comment]
I'm happy to remove all unused branches after the 2.9 release, though the official repo will belong to @fredrik-johansson anyway

**Comment by albinahlback** [comment]
> Many of the branches do not correspond to something in the main branch and so can't be simply replaced by a tag.
> 
> We use actual branches for releases so that development can continue in trunk unimpeded.

How about making all the tags to a branch then and removing the tag?

**Comment by albinahlback** [comment]
However, it is fine for me to delegate this issue to Fredrik as it's not urgent. ;-)

**Comment by wbhart** [comment]
No, we can't remove tags. This is what the distributions use. Tags and branches will both remain, however I've deleted all the ones we definitely don't need.
