### ISSUE TITLE
Bug in `fq_nmod`

### ISSUE THREAD

**Issue by albinahlback** [wbhart/flint2#1094]
Edit: Bug appears during exponentiation of polynomials (nothing that can be prevented via better documentation). Some code has to change.

Big bug that has to do with `fq_nmod[_poly]`. Occurs because `c = 32` is not reduced by its modulo `mod = 23`, but this is not documented, neither in FLINT nor in Nemo (also gives error in test code for Nemo). Example code: 

```c
#include "flint/fq_nmod.h"

void _nmod_vec_scalar_mul_nmod_generic(mp_ptr res, mp_srcptr vec,
                                slong len, mp_limb_t c, nmod_t mod);

int
main()
{
    fq_nmod_t rop;
    fq_nmod_ctx_t ctx;
    nmod_poly_struct * res = rop;
    fmpz_t p;

    fmpz_init_set_si(p, 23);
    fq_nmod_ctx_init(ctx, p, 1, "x");

    fq_nmod_init(rop, ctx);

    /* _nmod_vec_scalar_mul_nmod_generic(res->coeffs, res->coeffs, res->length, 32, res->mod); */
    /* NMOD_MUL_PRENORM(res->coeffs[0], res->coeffs[0], 32 << res->mod.norm, res->mod); */

    fq_nmod_set_si(rop, 1, ctx);
    fq_nmod_mul_si(rop, rop, 31, ctx);
    fq_nmod_print(rop, ctx);
    printf("\n");
    fq_nmod_set_si(rop, 1, ctx);
    fq_nmod_mul_si(rop, rop, 32, ctx);
    fq_nmod_print(rop, ctx);
    printf("\n");
    fq_nmod_set_si(rop, 1, ctx);
    fq_nmod_mul_si(rop, rop, 33, ctx);
    fq_nmod_print(rop, ctx);
    printf("\n\n");

    printf("len = %ld\n", res->length);
    printf("mod.norm = %ld\n", res->mod.norm);

    fq_nmod_ctx_clear(ctx);
    fmpz_clear(p);
}
```
gives
```
1 23  8
0 23                   # I think it should be 9
1 23  1                # I think it should be 10

len = 1
mod.norm = 59
```

Occurs because `32 << res->mod.norm` equates to `0` because of a large shift. Don't really know when this bug was introduced, but the test code really need to cover this case as this is a serious bug. Could perhaps be hard-coded into the tests.

One solution would be to say in the documentation for `fqXXX` that `c` is assumed to be reduced. This requires that Nemo adopts this in some way, either via documentation or by reducing the argument before calling FLINT.

**Comment by tthsqe12** [comment]
If no one is doing this, I will take a look.

**Comment by wbhart** [comment]
Go ahead.
