### ISSUE TITLE
Does `fq_nmod_[set/get]_nmod_mat` make sense?

### ISSUE THREAD

**Issue by albinahlback** [wbhart/flint2#1095]
It only sets the first column vector in a matrix: https://github.com/wbhart/flint2/blob/trunk/fq_nmod/get_set_fmpz_mod_mat.c#L14-L35

@defeo do you have any reasons for why this function should exist at all? If it should exist at all, I would like to see an input that says what column in the matrix to get/set. But I even think this is a stretch; Why not just a setter and getter for `nmod_vec`?

And apart from the unused functions `fq_zech_[set/get]_nmod_mat`, I can't see it being used anywhere. Not in Nemo, not in FLINT.

**Comment by wbhart** [comment]
They do appear to be unused and could probably be removed if there are no complaints.

It's not that I can't see them being used for something to do with finite field embeddings. It's just that they currently don't seem to be.

**Comment by defeo** [comment]
I don't remember how these functions ended up in the code. I can only assume @erou and I we had a plan to use them for something, but never completed it. I think it's safe to remove them.

**Comment by wbhart** [comment]
Thanks.

**Comment by defeo** [comment]
Oh, the call's templated. There it is: https://github.com/wbhart/flint2/blob/trunk/fq_embed_templates/matrices.c#L203

So, clearly we needed these as internal working functions for the finite field embedding stuff. The intent wasn't to expose them, they could be prefixed with underscores, if you want to do some API cleanup.

**Comment by wbhart** [comment]
Oh yes, I see. I missed that. Thanks.

Anyway, I'm happy to leave them as is. It's unlikely anyone notices them.
