### ISSUE TITLE
Overflow in COEFF_TO_PTR

### ISSUE THREAD

**Issue by wbhart** [wbhart/flint2#1096]
Andreas Enge reports:

When testing PariTwine with strict checking, I observed the following
problematic behaviour of flint.

Here is tflint.c:
```
#include <flint/flint.h>
#include <flint/fmpz.h>
int main (void)
{
   fmpz_t fz;
   fmpz_init(fz);
   fmpz_set_si(fz, 23);
   fmpz_pow_ui(fz, fz, 100);
   fmpz_neg(fz, fz);
}
```

And if I compile it like so:
   gcc -Wall -Wextra -lflint -lgmp -fsanitize=undefined -fno-sanitize-recover=all tflint.c
and call ./a.out, I obtain the following error:
tflint.c:42:26: runtime error: left shift of 4611686018432001020 by 2 places cannot be represented in type 'long int'

The culprit is the call to COEFF_TO_PTR in line 467 of fmpz.h.

Looking at fmpz-conversions.h:

```
#define PTR_TO_COEFF(x) (((ulong) (x) >> 2) | (WORD(1) << (FLINT_BITS - 2)))
#define COEFF_TO_PTR(x) ((__mpz_struct *) ((x) << 2))
```

I get the impression that in the first macro, you put something into the
two highest bits of the ulong. Now with the second macro you rely on these
bits to be pushed out, which the -fsanitize option recognises as dangerous
business. How about doing something similar to the
```
   |    (WORD(1) << (FLINT_BITS - 2))
maybe
   & (^ (WORD(1) << (FLINT_BITS - 2)))
```
?

**Comment by wbhart** [comment]
Andreas has looked into this and found this from the GNU C manual:

"https://www.gnu.org/software/gnu-c-manual/gnu-c-manual.pdf#Bit%20Shifting
(Section 3.8):
"Bits shifted off the left side of the value
are discarded; new bits added on the right side will all be 0.
(...)
For both << and >>, if the second operand is greater than the bit-width of the first
operand, or the second operand is negative, the behavior is undefined."

Technically the correct reference would be the C standard itself, and the relevant section is "ISO 9899:2011 6.5.7 Bit-wise shift operators".

According to Wikipedia a direct link to this section of the standard is here:

https://stackoverflow.com/questions/4945703/left-shifting-with-a-negative-shift-count

[Obviously no one can link to the *actual* C standard as no one knows where that is (it was last seen at the Alpha Centuri planning department 50 earth years ago).]

**Comment by wbhart** [comment]
Summary: I think we can safely ignore -fsanitize

**Comment by tthsqe12** [comment]
cast to ulong before shifting out the bit

**Comment by tthsqe12** [comment]
I think you can close this. It was fixed 9 months ago here:
https://github.com/wbhart/flint2/commit/c620fa5a7be0237d4801a70411bddef1fe148afe
