### ISSUE TITLE
Possibility for other representations of large fmpz

### ISSUE THREAD

**Issue by albinahlback** [wbhart/flint2#1098]
As of now, the maximum and minimum value of a small fmpz is ±(2^{62} - 1).

My suggestion is to change `PTR_TO_COEFF` to
```c
#define PTR_TO_COEFF(x) \
    (((ulong) (x) >> 2) | ((ulong) 1 << (FLINT_BITS - 1)))
```
With this, the two leading bits on the form `10` would signal that it is a big fmpz. The maximum value of a small fmpz would become `WORD_MAX` and the smallest value would be -(2^{62} + 1). With this, one could simply define
```c
#define COEFF_IS_MPZ(x) \
    ((slong) (x) < COEFF_MIN)
```

Or is there a reason why the current method is preferred?

**Comment by wbhart** [comment]
All the arithmetic would have to be changed to not only look at the number of bits, but whether the value is positive or negative. What you are talking about is a huge amount of work, not binary compatible and will probably make very little difference to performance on average.

In theory the extra bit can currently be used for mark and sweep operations in garbage collection, and leaves the possibility of merging other types with the integers in systems that use Flint integers.
