### ISSUE TITLE
`mpoly_max_fields_fmpz` shifts with 64 bits

### ISSUE THREAD

**Issue by albinahlback** [wbhart/flint2#1103]
See [line 64](https://github.com/wbhart/flint2/blob/trunk/mpoly/max_fields.c#L64) @tthsqe12

**Comment by albinahlback** [comment]
Same goes for `mpoly_unpack_vec_fmpz`

**Comment by albinahlback** [comment]
To reproduce this, use `CFLAGS="-O2 -march=native -Wall -fsanitize=undefined -fno-sanitize-recover=all"`

**Comment by wbhart** [comment]
Oh yes, this is very bad. I'll add it to the milestone and again assign to @tthsqe12

**Comment by tthsqe12** [comment]
flint has too much UB for `-fsanitize=undefined -fno-sanitize-recover=all` to be useful at the moment, but I will try to fix the shifts.

**Comment by tthsqe12** [comment]
Ah, I see you are trying to fix these in #1102
