### ISSUE TITLE
`mpoly_copy_monomials` gets called with null pointers

### ISSUE THREAD

**Issue by albinahlback** [wbhart/flint2#1104]
@tthsqe12 Try inserting
```c
    if (exp1 == NULL || exp2 == NULL)
    {
        printf("len = %ld, N = %ld\n", len, N);
        fflush(stdout);
        return;
    }
```
into the function and run the tests for `fmpz_mpoly_factor`, and see that it prints.

**Comment by wbhart** [comment]
I'm putting this into the 2.9 Milestone, and I'll assume @tthsqe12 takes this one on.
