### ISSUE TITLE
Avoid duplicated rec_word_tab table in longlong.h

### ISSUE THREAD

**Issue by fredrik-johansson** [wbhart/flint2#1123]
``longlong.h`` defines a static table ``rec_word_tab`` directly in the header file that seems to get inserted multiple times in the library:

    fredrik@mordor:~/src/flint2$ nm libflint.so | grep "rec_word_tab" | wc -l
    84

This table should probably be moved to a .c file.

BTW, the entry type could be changed from ``int`` to ``short``, saving half the space.

**Comment by fredrik-johansson** [comment]
Also, here is a large inline function that GCC clearly doesn't want to inline:

    fredrik@mordor:~/src/flint2$ nm libflint.so | grep "_mpoly_heap_insert" | wc -l
    49

I suppose the various heap functions in mpoly.h could de-inlined as an anti-bloat measure.

**Comment by albinahlback** [comment]
> `longlong.h` defines a static table `rec_word_tab` directly in the header file that seems to get inserted multiple times in the library:
> 
> ```
> fredrik@mordor:~/src/flint2$ nm libflint.so | grep "rec_word_tab" | wc -l
> 84
> ```
> 
> This table should probably be moved to a .c file.
> 
> BTW, the entry type could be changed from `int` to `short`, saving half the space.

I agree with all of this.
