### ISSUE TITLE
fmpz/invmod test fails under Cygwin

### ISSUE THREAD

**Issue by Stefan137** [wbhart/flint2#116]
I am trying to build flint-2.4.5 from the official download site on Windows 8 (64 Bit)/Cygwin using
`configure --disable-static --with-gmp && make && make check`

Execution of the fmpz/invmod test fails with the following message:
`d = -98079714615394588911994614472087275129318930955018174464, e = 1, f = 0, g = 0, r1 = 0, r2 = 1`

The test also fails with --disable-shared instead of --disable-static. All available updates for Cygwin packages have been installed today; in particular, the GMP version is 6.0.0a-2.

**Comment by wbhart** [comment]
That's correct. Flint 2.4.x assumes the GMP < 6 convention for invmod.

**Comment by Stefan137** [comment]
I see. Unfortunately, GMP 5.x is not available any more via Cygwin. Are there plans to support GMP 6 in FLINT? And is it only the modulus == 1 case (cf. https://github.com/wbhart/flint2/issues/61) that is affected by this incompatibility?

**Comment by wbhart** [comment]
I would think the next version of flint will support GMP 6. Don't quote me
but I think the changes were already made in trunk.

The issue you linked to is exactly the same issue you reported.

**Comment by Stefan137** [comment]
Alright, thank you very much!

**Comment by wbhart** [comment]
This has now been fixed. See https://github.com/wbhart/flint2/issues/61.
