### ISSUE TITLE
Multivariate rational functions

### ISSUE THREAD

**Issue by Sander80** [wbhart/flint2#1176]
Greeteings.
While studying your documentation, I found
- univariate rational functions over rational numbers
- multivariate polynomials over rational numbers

Am I missing something or is there no support for multivariate rational functions over rational nmbers?

The goal would be to have an alalogue of the Mathematica Together function, but in an open-source program.

Would be gratefull for any feedback or hints where to look at!

**Comment by wbhart** [comment]
That's correct. Multivariate rational functions would probably require Groebner bases which we don't have in Flint.

You might have a look at the Oscar computer algebra system if you need to solve problems involving these.

**Comment by Sander80** [comment]
Thank you much for the quick answer!

**Comment by fredrik-johansson** [comment]
Note that there are multivariate rational functions in Calcium: https://fredrikj.net/calcium/fmpz_mpoly_q.html

**Comment by Sander80** [comment]
Thank you)
