### ISSUE TITLE
Use precomputed primes in modular algorithms

### ISSUE THREAD

**Issue by wbhart** [wbhart/flint2#148]
Claus Fieker reports that for small polynomials fmpz_poly_resultant_modular spends a considerable amount of time in n_nextprime. This can be avoided by including a table of the first 100 primes in the required range and then only switching to n_nextprime if that table is exhausted.

**Comment by fredrik-johansson** [comment]
Or more simply, we can have n_nextprime use tables near powers of two.

**Comment by danaj** [comment]
As an aside, n_nextprime can be simplified and sped up a bit.  This is a separate issue.
 - The proved flag is obsolete.
 - We can run 10x faster for tiny inputs by properly using the flint_primes_small table (not relevant to this issue).
 - If we remove all the modulii stuff from n_nextprime and add 3-6 lines to isprime, we get slightly faster results while reducing n_nextprime from 83 lines to 26.

Unfortunately at 2^63 the difference is fairly small (6.9uS -> 6.2uS per call) so wouldn't solve this issue.

Would adding 53 tables of ~100 entries each really be a good thing for n_nextprime to have?  That seems unusually complicated.  If we really want to hide the functionality, perhaps make an iterator which could hide the work of sieving small segments and doling out the results as requested?

**Comment by wbhart** [comment]
I'm in more than one mind about this.

I think Claus' suggestion of using a precomputed lookup table is the only
way we'll get truly good performance. Fredrik's solution looked good until
I tried to think of how to implement it, or how much space it would take up.

I think adding some things to isprime is a good idea. We should do that,
and clean up nextprime a little. But I will have to think more carefully
about how to implement Claus or Fredrik's ideas.

I'm not sure if an iterator can be made fast enough. But I don't know
precisely what you had in mind, Dana.

Bill.

**Comment by danaj** [comment]
isprime/nextprime changes are really orthogonal to this as at *best* we'd get a 1.5x speedup.

For an iterator I was thinking of something similar to the ulong n_primes_next setup, but it would need some serious sieve changes to make it competitive at that size, and it still would be dubiously faster.  A precomputed table is the way to get excellent performance.

If you just want to restrict to 2^31 and 2^63 the space isn't nearly as bad as all powers of 2.  I believe an implementation in n_next_prime is easy if just doing the two ranges.  It just seems out of place (unless other places do something similar).  I can make a branch with the isprime / nextprime / table for 2^31 and 2^63 + 100 changes if you'd like, but due to travel it may be next week.

**Comment by wbhart** [comment]
On 16 July 2015 at 00:22, Dana Jacobsen <notifications@github.com> wrote:

> isprime/nextprime changes are really orthogonal to this as at *best* we'd
> get a 1.5x speedup.
>
> For an iterator I was thinking of something similar to the ulong
> n_primes_next setup, but it would need some serious sieve changes to make
> it competitive at that size, and it still would be dubiously faster. A
> precomputed table is the way to get excellent performance.
>
> If you just want to restrict to 2^31 and 2^63 the space isn't nearly as
> bad as all powers of 2. I believe an implementation in n_next_prime is easy
> if just doing the two ranges.
>
I am definitely leaning toward this. Claus actually requested 10-15
precomputed primes. But 100 didn't seem like a ridiculous figure to me.

> It just seems out of place (unless other places do something similar). I
> can make a branch with the isprime / nextprime / table for 2^31 and 2^63 +
> 100 changes if you'd like, but due to travel it may be next week.
>

Sure, why not.

Bill.

P.S: I guess we could also use bit arrays if we wanted to minimise space
for primes around powers of 2.

**Comment by fredrik-johansson** [comment]
You could just store the first 15 primes minus 2^63 as shorts and do a linear search (binary search might not even be worth the trouble).

**Comment by fredrik-johansson** [comment]
I added a table in https://github.com/fredrik-johansson/flint2/commit/4dc03a4f2445c202dc222a0518264bf835b9108a

This bandage fix gives a >300x speedup generating the first 64 primes after 2^63.
