### ISSUE TITLE
Support MIPS64

### ISSUE THREAD

**Issue by wbhart** [wbhart/flint2#150]
Andreas Enge has been helping us by reporting test failures on MIPS64, of which there are many. Most of the same things that are required for Windows64 also fix MIPS64.

MIPS64 has 32 bit pointers and either 32 or 64 bit longs, depending on ABI.

This issue will record failures as they are reported, and their fixes.

**Comment by wbhart** [comment]
The latest failure is the following

   cbrt_newton_iteration....FAIL:
   n = 4294967295, val = 1626, ans = 1625
   ../Makefile.subdirs:91: recipe for target '../build/ulong_extras/test/t-cbrt_newton_iteration_RUN' failed
   make[1]: *** [../build/ulong_extras/test/t-cbrt_newton_iteration_RUN] Aborted
   make[1]: Leaving directory '/home/privat/flint2/ulong_extras'

This is new code, added recently, which uses many hacks. Presumably a ulong/slong is missing somewhere, or something is being allocated as a ulong *, which is too small to contain the result.

**Comment by wbhart** [comment]
The test output indicates that ulong_extras/cbrt_newton_iteration is returning a faulty result.

The returned result is coincidentally cbrt(2^32) which is possibly a hint.

The code can return this value without further checking on a 32 bit machine, but not a 64 bit one. So at this stage I have no idea how this error can occur. The code looks absolutely fine to me.

**Comment by kush789** [comment]
Since the newton iteration method is the last test to be run among the cube root tests, I assume the other tests run successfully. All the others make use of n_cbrt_estimate(), which was the hacky part. Since the other tests pass, I guess there is no problem in that particular function too.

**Comment by kush789** [comment]
Ive figured this out, its actually a mistake in the constant "upper_limit" for a 32 bit system. It should be 1625, not 1626.

In line 74, we calculate upper_limit^3, and log2(1626 ^ 3) is slightly larger than 32.

**Comment by kush789** [comment]
The constant for a 64 bit system is right, log2 (2642245 ^ 3) is slightly less than 64

**Comment by wbhart** [comment]
That's a bug either way. But now I have to work out why this is relevant on
MIPS64, which is a 64 bit machine.

Thanks for spotting this!

**Comment by kush789** [comment]
The commit for that fix is here

**Comment by wbhart** [comment]
I believe I have already fixed it. Thanks.

Bill.

**Comment by wbhart** [comment]
Andreas reports that the problem with cbrt_newton_iteration is no longer the issue. There is a new failure:

n_rootrem....FAIL:
Passed Parameters : n = 129140164 root = 17
Answer generated : base = 4 remainder = 129140164
Expected answer : base = 3 remainder = 1

**Comment by wbhart** [comment]
The last reported bug has now been fixed. However, it only showed up on other 32 bit platforms. It shouldn't have shown up on a 64 bit platform. 

Now we wait to hear if there are any more bugs on MIPS.
