### ISSUE TITLE
C++ interface no longer compiles

### ISSUE THREAD

**Issue by wbhart** [wbhart/flint2#161]
With --enable-cxx, gcc 4.8.2 no longer compiles our C++ test code (MOD=flintxx).

We need a C++ guru to look at some of the error messages.

**Comment by VladimirGl** [comment]
In line 204 of arith.h arith_dedekind_sum_coprime_d defined as d_dedekind_sum_coprime, which does not exist. Should be #define arith_dedekind_sum_coprime_d fmpz_dedekind_sum_coprime_d, I think.

nmod_mat have functions nmod_mat_cols and nmod_mat_nrows, but in nmod_matxx and tests we use nmod_mat_ncols and nmod_mat_nrows (it seems more logically).

In padic_matxx in line 220 we have prec() function, which return by reference, but padic_mat_prec returns just slong. This can be fix if we define padic_mat_prec in padic_mat.h as well as padic_mat_val (#define padic_mat_prec(A) ((A)->N)) or remove reference type prec() function from padic_matxx() (then there is a problem in padicxx 321 line).

Then test compiled and passed.

**Comment by wbhart** [comment]
Thanks for these fixes Vladimir. I've merged these.
