### ISSUE TITLE
install procedure copies files in full instead of copying links

### ISSUE THREAD

**Issue by kiwifb** [wbhart/flint2#180]
The current install procedure looks like this for shared libraies:
```
install: library
	mkdir -p "$(DESTDIR)$(PREFIX)/$(LIBDIR)"
	mkdir -p "$(DESTDIR)$(PREFIX)/include/flint"
	$(AT)if [ "$(FLINT_SHARED)" -eq "1" ]; then \
		cp $(FLINT_LIB) "$(DESTDIR)$(PREFIX)/$(LIBDIR)"; \
		cp $(wildcard $(FLINT_LIBNAME)*) "$(DESTDIR)$(PREFIX)/$(LIBDIR)"; \
		ln -sf "$(DESTDIR)$(PREFIX)/$(LIBDIR)/$(FLINT_LIB)" "$(DESTDIR)$(PREFIX)/$(LIBDIR)/$(FLINT_LIBNAME)"; \
	fi
```
The last link is currently not necessary on OS X or cygwin but is on linux if #179 isn't merged. The `cp` command preceding the linking command should create a copy of `FLINT_LIB` named `FLINT_LIBNAME` since this file exist. But there is further drama. `cp` invoked like this will create copies of the library not links. `cp -a` will preserve links on linux and should also work on OS X (according to the man page on my macbook pro) not sure on cygwin. My proposed change for this is
```install: library
	mkdir -p "$(DESTDIR)$(PREFIX)/$(LIBDIR)"
	mkdir -p "$(DESTDIR)$(PREFIX)/include/flint"
	$(AT)if [ "$(FLINT_SHARED)" -eq "1" ]; then \
		cp $(FLINT_LIB) "$(DESTDIR)$(PREFIX)/$(LIBDIR)"; \
		cp -a $(wildcard $(FLINT_LIBNAME)*) "$(DESTDIR)$(PREFIX)/$(LIBDIR)"; \
	fi
```
but this is dependent on the inclusion of #179.

**Comment by wbhart** [comment]
I can test this on Cygwin and Msys2 (Mingw) if you like?

**Comment by kiwifb** [comment]
Yes that would be good. I am assuming that on cygwin you would have gnu cp and that it would behave the same. Not sure about mingw. Things gets hairy for stuff like aix but then I would probably have to write a new recipe for it in the first place.

**Comment by wbhart** [comment]
I'm not personally worried about AIX. Cygwin/Msys testing will take a
while. Hours probably.

**Comment by wbhart** [comment]
Just checking that this is what we now have, after merging the other tickets. I'm not missing some change suggested here that's not already merged?

**Comment by wbhart** [comment]
Seems to work fine under Cygwin64 and Msys2 64 bits.

Will now try the 32 bit versions.

MinGW is off with the fairies. Seems the 64 bit compiler is not available with MinGW64. Don't know why, don't care.

**Comment by wbhart** [comment]
Seems to work under Cygwin and Msys2 32 bits.

If you can confirm what we now have in trunk (I made some changes) works with OSX, then I am inclined to release 2.5.1.

**Comment by kiwifb** [comment]
Fails on OS X but not because of this. I am somewhat surprised trunk worked on cygwin and co. #177 introduced a hard dependency on finding `ldconfig` but that only really make sense on linux as far as I know. OS X lacks `ldconfig` and unless I feed `LDCONFIG` with something bogus `configure` will just stop. I will see if I can fix this quickly.

**Comment by kiwifb** [comment]
It has been pointed out to me that you did something for cygwin and co. in `configure` that I hadn't caught on. `Darwin` will have to be added to that list of exceptions that gets `LDCONFIG=/dev/null`.

**Comment by kiwifb** [comment]
OK build, pass test and install properly on OS X when I configure garbage for `LDCONFIG` once that problem is sorted you certainly can put 2.5.1 out of the door.
