### ISSUE TITLE
Installed lib doesn't have the links

### ISSUE THREAD

**Issue by SnarkBoojum** [wbhart/flint2#183]
After a make install, I get the libflint-2.5.so.13.5.1, but without a symlink to a libflint-2.5.so... which means the symlink from libflint.so to libflint-2.5.so is broken.

I added a $(LDCONFIG) line to the install target to solve the problem.

**Comment by wbhart** [comment]
I don't see how this can happen. The only two .so names we generate are:

FLINT_LIBNAME="libflint.so"
FLINT_LIB="libflint.so.$FLINT_MAJOR.$FLINT_MINOR.$FLINT_PATCH"

i.e. libflint.so and libflint.so.13.5.1

The former is linked to the latter.

**Comment by wbhart** [comment]
I don't see where the 2.5 is even coming from. We don't provide it anywhere.

**Comment by SnarkBoojum** [comment]
Ah, the fact that the base name is libflint-2.5.1.so.13.5.1 and not libflint.so.13.5.1 is a renaming for my packaging, and indeed that is the cause of my problem... sorry for the noise!
