### ISSUE TITLE
How to clear fmpz_mod_polyxx from memory? Memory leak ?

### ISSUE THREAD

**Issue by hilder-vitor** [wbhart/flint2#188]
Hi.

I was wondering if there is a equivalent of mpz_poly_clear to clear a fmpz_mod_polyxx, because, I think, the fmpz_mod_polyxx's descructor is not working well.

Take a look at this example:

```
#include <iostream>
#include "flint/fmpzxx.h"
#include "flint/fmpz_mod_polyxx.h"
#include "flint/fmpz_mod_poly_factorxx.h"

using namespace flint;

void test()
{
    std::cout << "waiting to create new polynomial" << std::endl;
    int a;
    std::cin >> a; // wait 
    // q  (273-bit prime)
    fmpzxx q("15177100720513508366558296147058741458143803430094840009779784451085189728165691397");

    fmpz_mod_polyxx* myPoly = new fmpz_mod_polyxx(q); 
    for (int i = 0; i < 7000000; i++){
        myPoly->set_coeff(i, q - fmpzxx(i));
    }
    std::cout << "waiting to create new polynomial" << std::endl;
    std::cin >> a; // wait 
    // q  (273-bit prime)
    fmpzxx p("1517710072051350118366558296147058741458143803430094840009779784451085189728165691397");

    fmpz_mod_polyxx* myPoly2 = new fmpz_mod_polyxx(p); 
    for (int i = 0; i < 900000; i++){
        myPoly2->set_coeff(i, p - fmpzxx(i));
    }

    std::cout << "waiting to clear the first polynomial" << std::endl;
    std::cin >> a; // wait 

    delete myPoly;
    myPoly = NULL;

    std::cout << "waiting to clear the second polynomial" << std::endl;
    std::cin >> a; // wait 

    delete myPoly2;
    myPoly2 = NULL;

    std::cout << "waiting to exit function test" << std::endl;
    std::cin >> a; // wait 
}

int main(int argc, char *argv[])
{
    test();
    std::cout << "already returned to main function" << std::endl;
    int b;
    std::cin >> b; // wait 

    return EXIT_SUCCESS;
}
```

The main function calls the test function. So, this function waits for some input before creating a polynomial and set several coefficients. Then, it waits again for some input and creates a second polynomial. After, both polynomials should be cleared.

I compiled this program and ran it. Its pid was 2342. Then, I did

$ cat /proc/2342/smaps

and there was no heap section.

After creating the first polynomial, the same bash command told that the heap section was like that

VmFlags: rd wr mr mw me dw ac sd 
009ca000-21fde000 rw-p 00000000 00:00 0                                  [heap]
Size:             546896 kB
Rss:              546876 kB
Pss:              546876 kB
Shared_Clean:          0 kB
Shared_Dirty:          0 kB
Private_Clean:         0 kB
Private_Dirty:    546876 kB
Referenced:       546876 kB
Anonymous:        546876 kB
AnonHugePages:         0 kB
Swap:                  0 kB
KernelPageSize:        4 kB
MMUPageSize:           4 kB
Locked:                0 kB

After creating the second polynomial:

VmFlags: rd wr mr mw me dw ac sd 
009ca000-26493000 rw-p 00000000 00:00 0                                  [heap]
Size:             617252 kB
Rss:              617192 kB
Pss:              617192 kB
Shared_Clean:          0 kB
Shared_Dirty:          0 kB
Private_Clean:         0 kB
Private_Dirty:    617192 kB
Referenced:       617192 kB
Anonymous:        617192 kB
AnonHugePages:         0 kB
Swap:                  0 kB
KernelPageSize:        4 kB
MMUPageSize:           4 kB
Locked:                0 kB

when the first polynomial (should be) cleared (it means, after  `delete myPoly`):

VmFlags: rd wr mr mw me dw ac sd 
009ca000-264a4000 rw-p 00000000 00:00 0                                  [heap]
Size:             617320 kB
Rss:              617320 kB
Pss:              617320 kB
Shared_Clean:          0 kB
Shared_Dirty:          0 kB
Private_Clean:         0 kB
Private_Dirty:    617320 kB
Referenced:       617320 kB
Anonymous:        617320 kB
AnonHugePages:         0 kB
Swap:                  0 kB
KernelPageSize:        4 kB
MMUPageSize:           4 kB
Locked:                0 kB

the second polynomial (should be) cleared

VmFlags: rd wr mr mw me dw ac sd 
009ca000-264a4000 rw-p 00000000 00:00 0                                  [heap]
Size:             617320 kB
Rss:              617320 kB
Pss:              617320 kB
Shared_Clean:          0 kB
Shared_Dirty:          0 kB
Private_Clean:         0 kB
Private_Dirty:    617320 kB
Referenced:       617320 kB
Anonymous:        617320 kB
AnonHugePages:         0 kB
Swap:                  0 kB
KernelPageSize:        4 kB
MMUPageSize:           4 kB
Locked:                0 kB

after returning to main function:

VmFlags: rd wr mr mw me dw ac sd 
009ca000-264a4000 rw-p 00000000 00:00 0                                  [heap]
Size:             617320 kB
Rss:              617320 kB
Pss:              617320 kB
Shared_Clean:          0 kB
Shared_Dirty:          0 kB
Private_Clean:         0 kB
Private_Dirty:    617320 kB
Referenced:       617320 kB
Anonymous:        617320 kB
AnonHugePages:         0 kB
Swap:                  0 kB
KernelPageSize:        4 kB
MMUPageSize:           4 kB
Locked:                0 kB

It seems like a memory leak, doesn't ?
Or I'm supposed to call some function like _fmpz_poly_clear_ to delete my polynomials ?

Thank you very much.

**Comment by wbhart** [comment]
You might get it to clean up by calling flint_cleanup(). The fmpz type
holds onto a cache of data for performance reasons.

Bill.
