### ISSUE TITLE
Infinite loop on non-SSE i686

### ISSUE THREAD

**Issue by jamesjer** [wbhart/flint2#189]
When building for 32-bit Intel CPUs without SSE, code is generated for the 80-bit floating point coprocessor.  This leads to infinite loops inside d_mat_gso (d_mat/gso.c) and d_mat_qr (d_mat/qr.c), because in both of those loops, s \* D_EPS never reaches 0.  It gets very, very close to 0, closer than can be represented by a 64 bit floating point number, but not all the way to zero.  Perhaps the test "if (s \* D_EPS == 0)" in both functions should instead be something like "if (fabs(s \* D_EPS) < 1.0e-308)", or some other suitably small constant.

This was discovered while attempting to build flint 2.5.2 for the Fedora Linux distribution, which still supports non-SSE i686 CPUs.

**Comment by wbhart** [comment]
Thanks for reporting this bug. We'll attempt to fix it as soon as we can.
