### ISSUE TITLE
HAVE_FAST_COMPILER definition error

### ISSUE THREAD

**Issue by jamesjer** [wbhart/flint2#192]
The definition of HAVE_FAST_COMPILER in flintxx/test/helpers.h evaluates to false for gcc < 4.7.3, and to true for gcc 4.x.x >= 4.7.3.  However, it also evaluates to false for gcc >= 5.0 and < 5.7.3 and to true for gcc 5.x.x >= 5.7.3, and so on.  The definition should instead be something like this:

(**GNUC** > 4 || (**GNUC** == 4 && (**GNUC_MINOR** > 7 || (**GNUC_MINOR == 7 && __GNUC_PATCHLEVEL** >= 3))))

**Comment by wbhart** [comment]
Thanks for reporting this. We'll fix it as you suggest.

Bill.

**Comment by wbhart** [comment]
Fixed in trunk.
