### ISSUE TITLE
Feature Request: fmpqxx * int

### ISSUE THREAD

**Issue by isuruf** [wbhart/flint2#222]
Currrently, `fmpzxx * int` works (`int` is any C++ integer type), but `fmpqxx * int` doesn't

**Comment by isuruf** [comment]
`fmpzxx + int` doesn't work either

**Comment by wbhart** [comment]
The functions aren't implemented at the C level.

**Comment by isuruf** [comment]
Ah, how about converting to `int` to `fmpzxx` and doing the operations?

**Comment by fredrik-johansson** [comment]
I think a deliberate choice was made to avoid conversions in the C++ interface.

However, we should add fmpq_op_si fmpq_op_ui methods at the C level.

**Comment by wbhart** [comment]
I've added:

fmpq_set_ui
fmpq_cmp_si
fmpq_add_ui
fmpq_sub_ui
fmpq_mul_ui
fmpq_mul_si
fmpq_equal_ui
fmpq_equal_si

and

fmpz_add_si
fmpz_sub_si

Perhaps someone with more C++ fu than me, e.g. @tthsqe12 could add the requested functions to the C++ wrapper, which should now be easy.

**Comment by tthsqe12** [comment]
This looks doable.

**Comment by tthsqe12** [comment]
@wbhart where is your fmpz_add/sub_si?

**Comment by wbhart** [comment]
Inlines in fmpz.h.

**Comment by wbhart** [comment]
Fixed by @tthsqe12 in trunk.

**Comment by isuruf** [comment]
Thanks @tthsqe12 and @wbhart
