### ISSUE TITLE
in factor_ecm.c nm8 set but not used

### ISSUE THREAD

**Issue by argriffing** [wbhart/flint2#237]
maybe a bug or a copypaste oversight. This caused a flint build warning.
https://github.com/wbhart/flint2/blob/trunk/ulong_extras/factor_ecm.c

**Comment by wbhart** [comment]
It's best to send pull requests for things like this, as I can then merge
them immediately.

But thanks for mentioning it.

Bill.

**Comment by argriffing** [comment]
I would, but I don't know the fix. I don't want to just delete it because it might be a bug. I don't know anything about `ecm` or even what it stands for. Maybe something about elliptic curves, which I don't know anything about.

**Comment by wbhart** [comment]
I'm pretty sure it was just a line of code that was there for
experimentation only. I've removed it.
