### ISSUE TITLE
Make LGPLv2+ version of Flint

### ISSUE THREAD

**Issue by wbhart** [wbhart/flint2#244]
The following people have given their permission, definitely:

David Howden
Peter Shrimpton
Daniel Woodhouse
David Harvey
William Hart
Fredrick Johansson
Sebastian Pancratz

The following people did not give their permission:

Richard Howell-Peak

**Comment by fredrik-johansson** [comment]
I think this is what needs to be done:

* Add a configure option to build FLINT with polynomial factorisation modules disabled (Richard Howell-Peak wrote the original version of the polynomial factorisation code, so it has to stay GPL until someone rewrites it from scratch).

* Contact the remaining people on the AUTHORS list to get permission from all who have made significant contributions (we don't need permission from people who just contributed trivial patches).

* If anyone else objects, figure out a way to disable their code, or just rewrite it from scratch.

* Update license statements for all the files where we have permission, to state that those files are individually licensed LGPL (or dual licensed LGPL + GPL, though I'm not sure if that's necessary).

* Include a global statement somewhere to the effect that FLINT is LGPL when built with the all-LGPL modules.

**Comment by wbhart** [comment]
If it is licensed LGPL v2+ there is no need to dual license it GPL.

The only reason GMP does the dual license thing is that it is LGPLv3+ or
GPLv2.

Bill.

**Comment by certik** [comment]
@wbhart, @fredrik-johansson thank you for doing that. Are there issues with licensing Arb under LGPL?

**Comment by fredrik-johansson** [comment]
No, there are no issues, it's just that FLINT has to change its license first. The only other person (besides Bill and Sebastian) who has written a substantial amount of code for Arb so far is Alex Griffing. I haven't asked him, but he's a SciPy dev, so I expect he will be fine with it.

**Comment by rwst** [comment]
> Add a configure option to build FLINT with polynomial factorisation modules disabled 

This will still leave the source inside. Maybe better an option to make such a tarball?

**Comment by fredrik-johansson** [comment]
I have contacted the following people and will update as they reply. I also asked whether they would prefer BSD/MIT licensing their individual contributions.

Tom Bachmann - yes to LGPL, no to BSD/MIT (but "could probably be swayed" if there was a strong need)
Mike Hansen - no reply yet
Martin Lee - no reply yet
Jan Tuitman - no reply yet
Tom Boothby - no reply yet
Dana Jacobsen - no reply yet
Anubhav Srivastava - no reply yet
Dharak Kharod - no reply yet
Kushagra Singh - yes to LGPL, yes to BSD or MIT
Ashish Kedia - no reply yet
Lina Kulakova - no reply yet
Andres Goens - no reply yet
Jason Papadopoulos - no reply yet

I think that is all the authors who have made legally significant contributors. To reiterate, we don't need an answer from everybody; there is precedent for changing the license of an open source project with permission from 95% or so of the contributors, as long as no one explicitly objects (in which case we have to replace their code).

By the way, Richard Howell-Peak also has a copyright on the matrix window init/clear functions. However, I think this is incorrect; I based the original nmod_mat functions on the FLINT 1.x code where all the matrix functions were in one file, and I don't think he was the original author of that particular code. In any case, the code in question is trivial and could only be written one way. The copyright here can just be changed to Fredrik Johansson, 2011.

Howell-Peak also has copyright for some poly/remove.c functions. These are easy to rewrite.

**Comment by fredrik-johansson** [comment]
> This will still leave the source inside. Maybe better an option to make such a tarball?

We could just move the GPL modules to a separate package and require that to be installed with the extensions mechanism.

**Comment by fredrik-johansson** [comment]
Good news: after finally getting the answer from Mike Hansen, I contacted Richard Howell-Peak again, and he has now agreed to chance the license.

So we can just go ahead and switch over the entirety of FLINT to the LGPL now.

(Anubhav Srivastava, Dharak Kharod and Alena Sergeicheva have not replied, but they only contributed small bits of code, so that's fine.)

**Comment by certik** [comment]
Great news, thanks @fredrik-johansson for doing the work!

**Comment by fredrik-johansson** [comment]
Now we basically just need to write a script to change all the copyright headers.

While doing so, we should consider trimming some fat from the header. It's 24 lines (with one author name), which is more than the actual source code in many of our short .c files, taking up a full default sized terminal window in ``less``.

We could first of all replace the FSF address with a URL, removing one line (this is what FSF/GNU advocates now anyway: http://www.gnu.org/licenses/gpl-howto.html).

We could also merge the license statement + copyright statement into one comment block, getting rid of some extra lines.

We could even write a shorter version of the license statement itself, omitting the legal disclaimer, which should bring us down to ~10 lines. The FSF/GNU text that we use now is what is recommended officially, but I don't think it's strictly necessarily to stick to it. The header just needs to be absolutely clear about who owns the copyright, what the license is, and where to find the full license text.

**Comment by wbhart** [comment]
On 22 April 2016 at 17:30, Fredrik Johansson <notifications@github.com>
wrote:

> Good news: after finally getting the answer from Mike Hansen, I contacted
> Richard Howell-Peak again, and he has now agreed to chance the license.
>
> So we can just go ahead and switch over the entirety of FLINT to the LGPL
> now.
>
> (Anubhav Srivastava, Dharak Kharod and Alena Sergeicheva have not replied,
> but they only contributed small bits of code, so that's fine.)
>
I agree, those were minor contributions.

I will have to ask Nitin Kumar if we ever merge any of his QS code, but
that is not currently merged.

Bill.

**Comment by fredrik-johansson** [comment]
Adaptation of current header:

    /*=============================================================================

        This file is part of FLINT.

        FLINT is free software: you can redistribute it and/or modify
        it under the terms of the GNU Lesser General Public License as
        published by the Free Software Foundation, either version 2.1 of the
        License, or (at your option) any later version.

        FLINT is distributed in the hope that it will be useful,
        but WITHOUT ANY WARRANTY; without even the implied warranty of
        MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
        GNU Lesser General Public License for more details.

        You should have received a copy of the GNU Lesser General Public License
        along with FLINT.  If not, see <http://www.gnu.org/licenses/>.

    =============================================================================*/
    /******************************************************************************

        Copyright (C) 2009 William Hart
     
    ******************************************************************************/

Possible shorter version:

    /*
        Copyright (C) 2009 William Hart

        This file is part of FLINT.

        FLINT is free software: you can redistribute it and/or modify
        it under the terms of the GNU Lesser General Public License as
        published by the Free Software Foundation, either version 2.1 of the
        License, or (at your option) any later version.

        FLINT is distributed in the hope that it will be useful,
        but WITHOUT ANY WARRANTY; without even the implied warranty of
        MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
        GNU Lesser General Public License for more details.

        You should have received a copy of the GNU Lesser General Public License
        along with FLINT.  If not, see <http://www.gnu.org/licenses/>.
    */

Possible even shorter version:

    /*
        Copyright (C) 2009 William Hart

        This file is part of FLINT.

        FLINT is free software; you can redistribute it and/or modify it under
        the terms of the GNU Lesser General Public License (LGPL) as published
        by the Free Software Foundation; either version 2.1 of the License, or
        (at your option) any later version.  See <http://www.gnu.org/licenses/>.
    */

**Comment by rwst** [comment]
Just trying my hands on it. Careful, there are differences like as in
```
/* __clz_tab -- support for longlong.h

Copyright 1991, 1993, 1994, 1996, 1997, 2000, 2001 Free Software Foundation,
Inc.
```
so scripting might need a preedited list of files to work on.

**Comment by fredrik-johansson** [comment]
I think the only exceptions are longlong.h and the files in the fft module.

Any opinions on changing the header layout as above?

**Comment by rwst** [comment]
Having the copyright at the top looks better.

**Comment by wbhart** [comment]
Does the actual license contain the warranty disclaimer? We should make
sure it is included somewhere.

**Comment by fredrik-johansson** [comment]
Yes:

NO WARRANTY

15 . BECAUSE THE LIBRARY IS LICENSED FREE OF CHARGE, THERE IS NO WARRANTY FOR THE LIBRARY, TO THE EXTENT PERMITTED BY APPLICABLE LAW. EXCEPT WHEN OTHERWISE STATED IN WRITING THE COPYRIGHT HOLDERS AND/OR OTHER PARTIES PROVIDE THE LIBRARY "AS IS" WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE ENTIRE RISK AS TO THE QUALITY AND PERFORMANCE OF THE LIBRARY IS WITH YOU. SHOULD THE LIBRARY PROVE DEFECTIVE, YOU ASSUME THE COST OF ALL NECESSARY SERVICING, REPAIR OR CORRECTION.

16 . IN NO EVENT UNLESS REQUIRED BY APPLICABLE LAW OR AGREED TO IN WRITING WILL ANY COPYRIGHT HOLDER, OR ANY OTHER PARTY WHO MAY MODIFY AND/OR REDISTRIBUTE THE LIBRARY AS PERMITTED ABOVE, BE LIABLE TO YOU FOR DAMAGES, INCLUDING ANY GENERAL, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES ARISING OUT OF THE USE OR INABILITY TO USE THE LIBRARY (INCLUDING BUT NOT LIMITED TO LOSS OF DATA OR DATA BEING RENDERED INACCURATE OR LOSSES SUSTAINED BY YOU OR THIRD PARTIES OR A FAILURE OF THE LIBRARY TO OPERATE WITH ANY OTHER SOFTWARE), EVEN IF SUCH HOLDER OR OTHER PARTY HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.

**Comment by wbhart** [comment]
Cool, no problem then.

**Comment by rwst** [comment]
The NO WARRANTY also applies to this branch: https://github.com/rwst/flint2/tree/license1
It has 4576 (mostly automatically) changed files. It's probably best to d/l the diff: https://github.com/rwst/flint2/commit/7acce4a05dab9db6df9764ff8b5852e51ec6fec6.diff
...and break it into sizeable chunks for eyeballing.

What was not changed:
 * `build.vc14/`
 * `fmpz_poly_q/test/`
 * 5 files in `nmod_poly` by David Harvey
 * `nmod_poly/profile/`

**Comment by fredrik-johansson** [comment]
There's an extra blank line after the header now.

**Comment by rwst** [comment]
In this branch there is now always one blank line after the license comment: https://github.com/rwst/flint2/tree/license2
No further changes were made versus the previous branch.

**Comment by rwst** [comment]
Oh no, I added the file named `t`. I take the occasion to complain about source files in the main directory which makes `git add *` a risky operation.

**Comment by fredrik-johansson** [comment]
Could you do it again without t in the history? It's quite a large blob of junk to have for no reason. Also, perhaps make the commit message more descriptive.

We also need to include the text of the LGPL in the main directory (currently, there's gpl-2.0.txt). There should perhaps be a LICENSE file, which is more standard.

While we're at it, we should state the license in README.

**Comment by fredrik-johansson** [comment]
I think squashing the commits with rebase will also do the trick.

**Comment by rwst** [comment]
I could do the other mentioned changes too but do you really want them all
in this one commit?

**Comment by fredrik-johansson** [comment]
No, it makes sense to change the headers in one commit and do everything else in separate commits.

**Comment by fredrik-johansson** [comment]
I also noticed that we don't seem to state the license in the documentation.

**Comment by rwst** [comment]
Can be closed?
