### ISSUE TITLE
PDF not compilable

### ISSUE THREAD

**Issue by rwst** [wbhart/flint2#261]
(changed from "ECM documentation unavailable in PDF")
In trunk:
```
ralf@ark:~/flint2/doc/latex> make
cc -c -ansi -pedantic -std=c99 -g create_doc.c -o create_doc.o
cc create_doc.o -o create_doc
./create_doc

Parse exception:
Encountered malformed input near line 147
in file ../../fmpz_factor/doc/fmpz_factor.txt.

Makefile:5: recipe for target 'manual' failed
make: *** [manual] Error 1
```
The format of the resp. part is not legal TeX/LaTeX. The same applies to the ECM part of `ulong_extras/doc/ulong_extras.txt`. Moreover the `nmod_vec` doc does not compile.

**Comment by wbhart** [comment]
Are you happy that this can be closed now?

**Comment by rwst** [comment]
Yes, was afk, now mobile.
