### ISSUE TITLE
Compiler warnings for flint_realloc

### ISSUE THREAD

**Issue by rickyefarr** [wbhart/flint2#263]
I haven't used realloc much in my past, and thought realloc returned an integer for success or failure.  Quickly programming, I used flint_realloc(ptr, size) without thinking about return values.  Replacing flint_realloc with the regular realloc from C quickly showed me the reason, because the C library throws a warning when the value returned is unused.

Would throwing an value unused warning for flint_realloc (and for other memory manager functions) be worthwhile to implement?

**Comment by wbhart** [comment]
Yes, flint_realloc should have the same behaviour. It would be useful to
implement.

**Comment by wbhart** [comment]
Fixed in trunk.
