### ISSUE TITLE
Compiler warning for fmpz_mod_poly_product_roots_fmpz_vec

### ISSUE THREAD

**Issue by rickyefarr** [wbhart/flint2#264]
I recently upgraded to gcc-6.1.0, and I just noticed this output while running the tests.  With this version of gcc colored warnings are shown in the terminal.  I'm not sure if this error was caught by previous gcc versions or not.  I just wanted to share this.

test/t-product_roots_fmpz_vec.c: In function ‘main’:
test/t-product_roots_fmpz_vec.c:54:9: warning: implicit declaration of function ‘fmpz_mod_poly_product_roots_fmpz_vec’ [-Wimplicit-function-declaration]
         fmpz_mod_poly_product_roots_fmpz_vec(P, x, n, mod);
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Note that the build still passed all tests, regardless.

**Comment by wbhart** [comment]
Thanks for reporting it. There's probably a missing prototype somewhere.
We'll add it before the next release.

Bill.

**Comment by wbhart** [comment]
There was a missing #include in the test file. This is now fixed in trunk.

Bill.

**Comment by rickyefarr** [comment]
Thanks for the update.  I will now close this issue.
