### ISSUE TITLE
`divides` parameters are reversed

### ISSUE THREAD

**Issue by srajangarg** [wbhart/flint2#267]
As per 64.11.20 in the [flint docs](http://www.flintlib.org/flint-2.5.pdf#page=580), 
`divides(p, q)` returns `<true, q/p>` if  **p divides q**, otherwise `<false, undefined>`.

```
fmpz_polyxx p("2  4 4 \0");
fmpz_polyxx q("1  2 \0");

if(flint::divides(p, q).get<0>())
    cout<<p.pretty("x")<<" divides "<<q.pretty("x")<<endl;

else if(flint::divides(q, p).get<0>())
    cout<<q.pretty("x")<<" divides "<<p.pretty("x")<<endl;
```

The output of above program is `4*x+4 divides 2`. It should be the other way round as, q divides p here. Am I doing something wrong?
ping @wbhart @fredrik-johansson

**Comment by wbhart** [comment]
It looks like the documentation is wrong. Thanks for reporting it.
