### ISSUE TITLE
Configure's help output for flag "single" and "reentrant" versus documentation output

### ISSUE THREAD

**Issue by rickyefarr** [wbhart/flint2#268]
I'm not sure if this is an issue or not, but I'm confused about the help output for configure and what the documentation states.

When using ./configure --help, the following line prints to terminal about the --single and --reentrant :

--single             Faster [non-reentrant if tls or pthread not used] version of library (default)
--reentrant        Build fully reentrant [with or without tls, with pthread] version of library

Looking at page 23, the documentation given at link http://www.flintlib.org/flint-2.5.pdf says "To this end, the library is threadsafe, ...".  On page 27, it says "If you wish to use FLINT on a single core machine, then it can be configured for single mode." On the last paragraph of page 27 starts with "If you wish to build a threadsafe version of FLINT which uses a less complicated memory model, you can pass the --reentrant option to configure."

According to the documentation it seems since I'm not on a single core machine that the single flag could be bad for me, yet the configure help output just plainly says the library is faster using single mode without any restrictions (so why would I ever change out of this mode?).

Is non-reentrancy even an issue on single core machines?  If I'm non-reentrant, doesn't that mean I'm not threadsafe in general?

**Comment by rickyefarr** [comment]
Also, it's worth mentioning that with the reentrant flag enabled the test suite fails, with:

is_prime_pocklington....../Makefile.subdirs:91: recipe for target '../build/fmpz/test/t-randprime_RUN' failed
make[1]: *** [../build/fmpz/test/t-randprime_RUN] Segmentation fault (core dumped)
make[1]: *** Waiting for unfinished jobs....

If the reentrant flag is not used, the test suite passes all tests.

**Comment by wbhart** [comment]
On 15 June 2016 at 08:13, Ricky E. Farr <notifications@github.com> wrote:

> I'm not sure if this is an issue or not, but I'm confused about the help
> output for configure and what the documentation states.
>
> When using ./configure --help, the following line prints to terminal about
> the --single and --reentrant :
>
> --single Faster [non-reentrant if tls or pthread not used] version of
> library (default)
> --reentrant Build fully reentrant [with or without tls, with pthread]
> version of library
>
> Looking at page 23, the documentation given at link
> http://www.flintlib.org/flint-2.5.pdf says "To this end, the library is
> threadsafe, ...". On page 27, it says "If you wish to use FLINT on a single
> core machine, then it can be configured for single mode." On the last
> paragraph of page 27 starts with "If you wish to build a threadsafe version
> of FLINT which uses a less complicated memory model, you can pass the
> --reentrant option to configure."
>
> According to the documentation it seems since I'm not on a single core
> machine that the single flag could be bad for me, yet the configure help
> output just plainly says the library is faster using single mode without
> any restrictions (so why would I ever change out of this mode?).
>

You wouldn't, if your machine supports it. But it can happen that either
your platform doesn't support it, or there's some other complication with
software you are interfacing Flint with, and you want a simpler memory
model. It used to be that Flint was not threadsafe in the single mode, but
nowadays it is if your platform supports tls.

By the way, we know the nextprime code fails. We have an open ticket for
it. Thanks for reminding us of it.

Bill.
