### ISSUE TITLE
missing FLINT_DLL for fmpz_get_str

### ISSUE THREAD

**Issue by truedim** [wbhart/flint2#269]
Hi!
fmpz_get_str is not exported in the fmpz.h

Also possible redundant declarations in the flint.h:

extern char version[];

typedef __mpfr_struct mpfr;

**Comment by wbhart** [comment]
Thanks for reporting this.

**Comment by wbhart** [comment]
The FLINT_DLL is fixed.

version does not seem to be duplicate,  but should be flint_version.

mpfr also seems to not be duplicate, but should be flint_mpfr
