### ISSUE TITLE
No documentation for setting num/den for fmpq_t?

### ISSUE THREAD

**Issue by srajangarg** [wbhart/flint2#271]
Under 25.6
> `void fmpq_set_fmpz_frac(fmpq_t res, const fmpz_t p, const fmpz_t q)` sets `res` to the canonical form of the fraction `p / q`. This is equivalent to assigning the
numerator and denominator separately and calling `fmpq_canonicalise`.

But I couldn't find anything on assigning the numerator/denominator of a `fmpq` separately. Can someone point me to the functionality?

**Comment by srajangarg** [comment]
I needed this for implementing the functionality of `fmpq_pow_ui` by individually powering the num/den and setting on the result. Why doesn't a `fmpq_pow_ui` exist?

**Comment by wbhart** [comment]
Use fmpq_numref/denref, defined near the top of fmpq.h for getting a
reference to the numerator and denominator as fmpz's. You can then set them
separately.

There is fmpq_pow_si. It's not clear that you need an fmpq_pow_ui as well.

Bill.
