### ISSUE TITLE
Get coefficient by reference?

### ISSUE THREAD

**Issue by srajangarg** [wbhart/flint2#272]
Is there a way to get coefficients inside a `fmpz_poly`/`fmpq_poly` by reference?

**Comment by wbhart** [comment]
fmpz_poly_get_coeff_ptr for fmpz_poly. There is no way to do this for an
fmpq_poly since coefficients are not stored as fmpq's.

Bill.

**Comment by srajangarg** [comment]
Thanks! Have you considered opening a gitter channel?
