### ISSUE TITLE
Bug in flint2/fmpz_poly_q/clear.c

### ISSUE THREAD

**Issue by eschnett** [wbhart/flint2#273]
These lines in `clear.c`:

```
    if (rop->den != NULL);
    {
        fmpz_poly_clear(rop->den);
        flint_free(rop->den);
        rop->den = NULL;
    }
```

contain a semicolon right after the `if` statement that most likely should not be there.

**Comment by wbhart** [comment]
Definitely looks like a bug. Thanks for reporting this. Fortunately this
module is not used often.

Bill.

**Comment by wbhart** [comment]
Fixed in trunk. Thanks for the report(s).
