### ISSUE TITLE
GCD over `fmpz_poly` and `fmpq_poly`

### ISSUE THREAD

**Issue by srajangarg** [wbhart/flint2#276]
How is the GCD defined for both integer and rational polys?

I am confused because `fmpz_gcd(2*x**2, 2*x)` gives `2*x`, while `fmpq_gcd(2*x**2, 2*x)` gives `x`. I checked the code and saw it calls `make_monic` in the `fmpq_gcd` case. Sorry, I am not very familiar with the mathematical algebra involved.

**Comment by srajangarg** [comment]
Another thing I found : 
https://github.com/wbhart/flint2/blob/trunk/fmpq_poly/gcd.c#L40-L69

line 40 (if) checks : `fmpz_is_one(s)`
line 56 (else) again checks : `fmpz_is_one(s)`

Either the second time is redundant (won't ever be encountered) or actually `fmpz_is_one(t)` was meant. Can someone confirm?

**Comment by wbhart** [comment]
On 25 July 2016 at 09:38, Srajan Garg <notifications@github.com> wrote:

> How is the GCD defined for both integer and rational polys?
>
> I am confused because fmpz_gcd(2*x**2, 2*x) gives 2*x, while fmpq_gcd(2*x**2,
> 2*x) gives x. I checked the code and saw it calls make_monic in the
> fmpq_gcd case. Sorry, I am not very familiar with the mathematical
> algebra involved.
>

When working over a field, you can scale by any nonzero element of the
field. So we do that in the case of the rationals.

The integers are not a field, so you can't do that.

**Comment by wbhart** [comment]
That indeed looks like a bug. The second one should be fmpz_is_one(t). Nice
catch!

I'll correct this in the repo.

**Comment by wbhart** [comment]
Fixed in trunk.
