### ISSUE TITLE
bug in _arith_bernoulli_number_zeta()

### ISSUE THREAD

**Issue by aweisse** [wbhart/flint2#288]
Dear flint developers,

the function _arith_bernoulli_number_zeta() seems to give the wrong result for n = 250408.

Here are a few lines of Sage code that illustrate the problem:

```
algs = ['arb','flint','pari','bernmm']
n = 250408

nums = {}
for a in algs :
    nums[a] = numerator(bernoulli(n,a))

print ' == ?\t', algs
for a in algs :
    print a,'\t', map(lambda b: nums[a] == nums[b], algs)
```

The version of Sage I used was 7.3 which includes flint 2.5.2. 

The numerator of this Bernoulli number has more than a million digits, but the difference to the other results is only 1428094259. Maybe it is some precision issue in the floating point part or the rounding.

Best regards,

Alex

**Comment by fredrik-johansson** [comment]
I can confirm that there is a bug. I recommend using arb instead of flint, for this very reason.

**Comment by fredrik-johansson** [comment]
Fixed in my repo.

**Comment by aweisse** [comment]
Thanks for the quick fix. I noticed that increasing `prec` by just 1 is already sufficient, here's the diff:

```
--- arith/bernoulli_number_zeta.c.orig	2015-08-13 18:16:22.000000000 +0200
+++ arith/bernoulli_number_zeta.c	2016-09-06 15:45:36.154686362 +0200
@@ -46,7 +46,7 @@
     }
 
     prec = arith_bernoulli_number_size(n) + fmpz_bits(den);
-    prec += 10 + 2*FLINT_BIT_COUNT(n);
+    prec += 11 + 2*FLINT_BIT_COUNT(n);
     pi_prec = prec;
 
     mpz_init(r);
```

**Comment by aweisse** [comment]
P.S.: Maybe one should also notify Sage developers? They use flint as the default algorithm for n<=300000.

**Comment by fredrik-johansson** [comment]
Yes, it would be a good idea to open a Sage ticket about this.

**Comment by rwst** [comment]
I opened https://trac.sagemath.org/ticket/21439

**Comment by aweisse** [comment]
Perfect. I was just trying to figure out how to post to the sage-devel list without a stupid google account...

**Comment by wbhart** [comment]
There's no known rigorous bound we can use in flint. Arb's ball arithmetic is really what's needed here.

We could of course start a big project to exhaustively test all values in Flint up to some huge bound.

The fix Fredrik committed *should* fix the problem for all practical values of n, for some non-rigorous definition of "should".

**Comment by wbhart** [comment]
I've now pushed Fredrik's change to my repo also.
