### ISSUE TITLE
fmpz_is_probabprime should call the BPSW algorithm

### ISSUE THREAD

**Issue by wbhart** [wbhart/flint2#291]
The BPSW algorithm is implemented, but not called by fmpz_is_probabprime. Instead it is doing 25 Miller-Rabin iterations!

We should also have a trial division which checks divisibility by small _primes_.

I don't think we want fmpz_is_probabprime to call this automatically because fmpz_is_prime calls it at some point and I don't think we want to do trial division twice.

**Comment by fredrik-johansson** [comment]
This is actually fine with GMP 6.2 since its mpz_probab_prime_p has been changed to perform a BPSW test.

**Comment by wbhart** [comment]
Relying on this would make it harder to document what algorithm is actually used, as requested by Dana J on another open ticket. So I am in two minds about this.

**Comment by fredrik-johansson** [comment]
Yeah. I will fix this issue.

**Comment by wbhart** [comment]
I'll close this one since there is a different ticket that asks for the algorithm in is_probab_prime to be documented.
