### ISSUE TITLE
Problem building on OSX 10.11

### ISSUE THREAD

**Issue by jppelteret** [wbhart/flint2#293]
Hi! I'm trying to add a package for Flint to the [Spack package manager](https://github.com/LLNL/spack/pull/1885/commits/00295a6b1c5738faa4e641d7ef5138d84121b9f6) (I know that its currently pointing at a forked version of Flint, but I've changed this offline), and have hit some trouble building it on `OS X 10.11 El Capitan`. 

```
....
CC   ../build/ulong_extras/sqrtrem.lo
CC   ../build/ulong_extras/xgcd.lo
CC   ../build/ulong_extras/../ulong_extras.lo
ld: -rpath can only be used when creating a dynamic final linked image
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
Here is the [build log](https://github.com/fredrik-johansson/flint2/files/504946/spack-build.out.txt), which is the same for both `git master` and `v2.5.2`. I don't think that any additional flags or settings are being set by `spack`. Is this a bug, or there some configuration-time settings that I need to add when building on `OS X`?

**Comment by wbhart** [comment]
I am not sure. We build on OSX regularly, so you shouldn't need to do
anything strange. I also think Clang should be no problems.

You might have a look in the Makefile and see where the -rpath is coming
from. It doesn't seem to like it.

Bill.

**Comment by jppelteret** [comment]
Ok, thank you for the information. I'll try to build it outside of spack a little later, and I'll work from there to find the issue.

**Comment by jppelteret** [comment]
Thank you for your time and suggestion. I've managed to successfully build `flint` manually, so there's clearly something going on with `spack`'s compiler commands. In both cases, the Makefile that `flint` generates looks the same, so there must be some hidden arguments that I wasn't aware of. I'll take up the issue with the `spack` devs if I can't resolve it myself.
