### ISSUE TITLE
Compiling flint with PIE

### ISSUE THREAD

**Issue by SnarkBoojum** [wbhart/flint2#298]
Hi,

Ubuntu does and Debian is going to compile things with PIE enabled, which breaks flint's build. Logan Rosen wrote a patch for ubuntu but didn't send it upstream ; I am going to use it in my package [here](https://patches.ubuntu.com/f/flint/flint_2.5.2-9ubuntu1.patch) it is!

Cheers,

Snark on #debian-science

**Comment by SnarkBoojum** [comment]
Ok, now I can say Logan Rosen's patch isn't good enough : we still get failed builds involving those switches. I'm going to see what he can do and then report here.

**Comment by parleur** [comment]
Hi, I have encountered this issue and found an obscure patch on a sage forum (difficult for me to link into it I was not on my machine). 
I link a PR implementing the possible solution. Let me know if it is the Logan Rosen patch. I don't fully understand what it does but I have hint in the PR305.

**Comment by wbhart** [comment]
I don't know if it is the same as Logan's patch or not. The link to his
patch has gone dead, and the last time I tried to find it on debian I just
got caught in an infinite loop clicking links that didn't actually lead
anywhere.

I'm afraid I'm going to have to let the debian experts sort this one out.

**Comment by SnarkBoojum** [comment]
Here is a stable link to the [changes applied in the Debian package](https://anonscm.debian.org/cgit/debian-science/packages/flint.git/tree/debian/patches)

**Comment by parleur** [comment]
Thanks for this respond. I figures it may be used to patch the julia built script for Nemo (which is my purpose). 
The problem also arise for arb which is not in the list of patchs applied to the Debian package.

So there is two way to solve the problem:
- patch the buiding chain to make flint compatible for gcc 4,5 and 6 (same for arb). I think it is the best, but it's also harder.
- patch the Nemo build script to apply patch function of gcc 's local machine. Same issue/solution for Sage. Could be a workaround for the transition. 

I 'll have some time to spend at it.

**Comment by wbhart** [comment]
The stable link is dead.

**Comment by SnarkBoojum** [comment]
[Here](https://salsa.debian.org/science-team/flint/-/tree/master/debian%2Fpatches) is a new link... hopefully stabler than the dead stable link.

**Comment by wbhart** [comment]
Great, thanks! It looks like this is applied in trunk, so I will now close this and the associated issue.
