### ISSUE TITLE
Problems on x32 architecture

### ISSUE THREAD

**Issue by SnarkBoojum** [wbhart/flint2#300]
Hi,

among the failures the Debian buildds uncovered, there is:

    factor_trial....test/t-nextprime.c: In function 'main':
    test/t-nextprime.c:82:23: warning: left shift count >= width of type [-Wshift-count-overflow]
             n = (UWORD(1) << (FLINT_BITS-1)) + rep;
                           ^~
    PASS
    powmod_precomp....FAIL:
    a = 15403, exp = -1646270329, d = 138400
    r1 = 60387, r2 = 63587
    ../Makefile.subdirs:91: recipe for target '../build/ulong_extras/test/t-powmod_precomp_RUN' failed

The first is a worrying warning and the second a direct failure.

Thanks,

Snark on #debian-science

**Comment by wbhart** [comment]
Yes, we are aware that x32 is not currently supported by us. I don't know
if anyone is working on supporting it in flint.

Bill.
