### ISSUE TITLE
Conflicting count_*_zeros definitions

### ISSUE THREAD

**Issue by SnarkBoojum** [wbhart/flint2#306]
Hi,

a new patch was added to the flint Debian package, authored by Tobias Hansen, who had trouble with conflicting count_*_zeros definitions ; it is available [here](https://anonscm.debian.org/cgit/debian-science/packages/flint.git/tree/debian/patches/undef_count_leading_zeros.patch), if you want to apply it too.

Cheers!

**Comment by wbhart** [comment]
This patch looks ok to me. I think we can apply it.

Bill.

**Comment by rwst** [comment]
I took the liberty and opened #374 with this.
