### ISSUE TITLE
failing doctest  in fmpz_lll/lll_d_heuristic_dot

### ISSUE THREAD

**Issue by videlec** [wbhart/flint2#309]
At commit 9dfe24d

     on entre dans le répertoire « /opt/flint/fmpz_lll »
     wrapper....PASS
     lll_d_heuristic....PASS
     wrapper_with_removal....PASS
     lll_d_heuristic_with_removal....PASS
     heuristic_dot....FAIL:
     expo1 = 198, expo2 = 199
     d1 = 6.03268e-120, d2 = 2.01654, d3 = 1.06274, d4 = 3.07929
     3.54206e-12

**Comment by wbhart** [comment]
We know about this.
