### ISSUE TITLE
segfault in test for num_real_roots

### ISSUE THREAD

**Issue by thofma** [wbhart/flint2#316]
On latest trunk:

```
make[1]: *** [../build/fmpz_poly/test/t-num_real_roots_sturm_RUN] Segmentation fault (core dumped)
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [../build/fmpz_poly/test/t-num_real_roots_RUN] Segmentation fault (core dumped)
```
@videlec

Edit: It also crashed on travis.

**Comment by videlec** [comment]
I am not able to reproduce. On my computer `num_real_roots` went fine. Do you have more information?

**Comment by wbhart** [comment]
@thoffma Can you run the test with valgrind. It passes for me.

**Comment by thofma** [comment]
Not for me. I think the problem is that https://github.com/wbhart/flint2/blob/trunk/fmpz_poly/test/t-num_real_roots_sturm.c#L29 is called without initializing `p`. One must call `fmpz_init(p)` first. Similar in the other test file.

**Comment by videlec** [comment]
Thanks for tracking the issue. I made #319
