### ISSUE TITLE
Check slong is used for variables passed as params to _si functions

### ISSUE THREAD

**Issue by fredrik-johansson** [wbhart/flint2#32]
See title.

**Comment by wbhart** [comment]
There are five files xaa, xab, xac, xad, xae each with around 72 potential cases to check.

Here are the suspicious cases per file after volunteers examined the files. Each will have to be checked very carefully and/or fixed.

xaa:
===========================================
xab:
===========================================
xac:

fmpz/divexact_ui.c:        fmpz_set_si(f, c1 / (slong) h);

fmpz/invmod.c:            return (gcd == UWORD(1) ? fmpz_set_si(f, inv), 1 : 0);
fmpz/invmod.c:            return (gcd == UWORD(1) ? fmpz_set_si(f, inv), 1 : 0);

fmpz.h:        fmpz_set_si(f, x - m);

fmpz_mat/hadamard.c:            fmpz_set_si(fmpz_mat_entry(Q, r, c),
   Also: cases of long in this file!!
==================================================
xad:
==================================================
xae:

**Comment by fredrik-johansson** [comment]
The one in fmpz_mat/hadamard.c: is OK; the argument type is actually int. The longs are safe also and could be changed to either int or slong. In fact all the fmpz values being set in this file are -1, 0, 1.

**Comment by wbhart** [comment]
Thanks for checking. I may as well set the longs to slongs, just so we
don't keep examining the same thing in future.
