### ISSUE TITLE
Add remove for fmpz_mpoly, fmpq_poly and fmpz_poly(?).

### ISSUE THREAD

**Issue by thofma** [wbhart/flint2#323]

**Comment by wbhart** [comment]
I've added it for fmpz_poly.

**Comment by wbhart** [comment]
I have added a not totally dumb divides for fmpq_poly's and remove for fmpz_poly's and fmpq_poly's. These function seem to already exist for fq_poly's and friends and nmod_poly's and friends.

@tthsqe12 If you find the time, I will leave the fmpz_mpoly case for you to implement. Of course we'll eventually need them for all relevant *_mpoly (I guess you need a UFD), but the ticket doesn't ask for that. Just add a new ticket for those if you run out of motivation.

**Comment by wbhart** [comment]
@tthsqe12 Do you want to work on fmpz_mpoly_remove for the release (approximately 8 days until beta)? Or do you want me to push it out to the next release?

**Comment by tthsqe12** [comment]
I will not be working on this any time soon. I would not be doing anything more special than calling divides in a loop, which you can do fine elsewhere.

**Comment by wbhart** [comment]
No problem. Let's look at this in a later release then.
