### ISSUE TITLE
build errors

### ISSUE THREAD

**Issue by kalmarek** [wbhart/flint2#326]
I've tried to install Nemo, but flint2 (pulled from here as I see in `build.jl`) has problems building:

https://github.com/wbhart/flint2/blob/72fcb07c84e0bda3f7e3eed76bdc357e967d3ce7/fmpz_mpoly/unpack_monomials.c#L282
(parenthesis don't match)

https://github.com/wbhart/flint2/blob/trunk/fmpz_mpoly/set_monomial.c#L407
(`poly` is undefined)

**Comment by wbhart** [comment]
I tried merging a more recent version of my fmpz_mpoly branch into trunk. I
hope this fixes the issue for you. You probably have to delete the
.julia/v0.5/Nemo/deps/flint2 directory so it will start again.

**Comment by kalmarek** [comment]
The first one is obviously a syntax error; adding a closing parenthesis fixes it;
The second is probably some left-over from function definition (was poly the argument at some time?)
Anyway: deleting `poly->` fixes it;
(note that the the code-path is for 32bit arch)

Now (after Your merge) I also get
```
hashmap.h:87:12: error 'c' undeclared (first use in this function)
    int b = c = 0;
```
I don't know the syntax of C, but `int b = 0; int c = 0;` runs fine
(again this is code-path for 32bits)

**Comment by wbhart** [comment]
Ok, I'll change that b = c = 0; in just a moment.
