### ISSUE TITLE
flint_abort should be declared noreturn

### ISSUE THREAD

**Issue by fredrik-johansson** [wbhart/flint2#327]
flint_abort should be declared with `__attribute__ ((noreturn))`

Otherwise code like

    int func(int x)
    {
        if (x == 0)
            flint_abort();
        else
            return x;
    }

generates compiler warnings.

**Comment by rwst** [comment]
Created #375

**Comment by wbhart** [comment]
This needs to be done in a platform specific way, e.g. with a FLINT_NORETURN macro.

**Comment by fredrik-johansson** [comment]
Fixed in my repo.
