### ISSUE TITLE
Build Error On Bash in Windows 10

### ISSUE THREAD

**Issue by rickyefarr** [wbhart/flint2#330]
I looked through some of the reported issues on github, and I didn't find any that is  specific to this error.  I'm using the new Ubuntu bash shell within windows 10.  I will eventually check this with a pure linux installation.  After configuration, and typing make everything seems to go well until it ends with:

make[2]: Leaving directory `/home/therickaman/libs/flint2/fmpz_mpoly'
touch: cannot touch ‘fmpz_mpoly/test/t-*.c’: No such file or directory
make[1]: *** [libflint.a] Error 1
make[1]: Leaving directory `/home/therickaman/libs/flint2'
make: *** [library] Error 2

**Comment by rickyefarr** [comment]
I figured out the issue, I'll push the fix in a moment.

**Comment by rickyefarr** [comment]
Well, I tried to push the change but I couldn't get git to push the change over since I only added an empty directory.  The way I fixed this issue was to create an empty directory fmpz_mpoly/test.  After this file was created, I could build the library.

**Comment by rickyefarr** [comment]
The error is due to the directory fmpz_mpoly/test not existing.  I'm not sure the best way of fixing this issue.  Seems like creating an empty directory is not a very robust fix.

**Comment by wbhart** [comment]
Ah right. I'll add an empty file in that directory so it has something to
do. Thanks for finding that!

**Comment by rickyefarr** [comment]
Actually, adding the empty directory fixes the build issue but causes the tests to fail.  Here is the output:

PASS
make[1]: Leaving directory `/home/therickaman/libs/flint/flint2/fq_zech_poly_factor'
make[1]: Entering directory `/home/therickaman/libs/flint/flint2/fmpz_mpoly'
    CC   ../build/fmpz_mpoly/test/t-*
test/t-*.c:1:0: warning: ISO C forbids an empty translation unit [-Wpedantic]
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/crt1.o: In function `_start':
(.text+0x20): undefined reference to `main'
collect2: error: ld returned 1 exit status
make[1]: *** [../build/fmpz_mpoly/test/t-*] Error 1
make[1]: Leaving directory `/home/therickaman/libs/flint/flint2/fmpz_mpoly'
make: *** [check] Error 2

**Comment by wbhart** [comment]
I've added an empty test. It should be ok now.

**Comment by rickyefarr** [comment]
Thanks!
