### ISSUE TITLE
fq_nmod_poly multiplication using nmod_poly multiplication

### ISSUE THREAD

**Issue by wbhart** [wbhart/flint2#334]
JP Flori reports:

I've pushed a branch to perform fq_nmod_poly multiplication using nmod_poly multiplication at:
https://github.com/jpflori/flint2/tree/fq_nmod_poly_mul_univariate
It's very straightforward.

Note that it does not use the template framework as it directly manipulates the coefficients and making a coefficient type agnostic version could perform worse (and could be less readable).

I've not extensively benchmarked it and so did not plug it into fq_nmod_poly_mul yet.
I've also naively copied profile/p-mullow.c into profile/p-mul_univariate.c (and had to hack around RDTSC to work on ppc64) so it might be completely wrong.
Whatsoever the new code seems quite a bit faster when the fq degree is large whereas the poly degree is low.

Feel free to comment, modify it, or merge it

**Comment by wbhart** [comment]
We needed a pull request for this, and some timings. I can't remember if we already got a pull request, and if we merged it already or not.

**Comment by jpflori** [comment]
IIRC the "low-level" functions got merged in though not used in the more general multiplication routines.
