### ISSUE TITLE
Update issues on mpir 3.0.0 on windows

### ISSUE THREAD

**Issue by isuruf** [wbhart/flint2#338]
Due to https://github.com/wbhart/mpir/commit/b84e7e24ca24fd4a965017ff56c25728d2d10fdc, there are now warnings due to converting from `slong *` to `signed long*`.

Also `flint_mpf_get_d_2exp` has a different function signature compared to mpir 3.0.0 due to the same change in mpir.

**Comment by wbhart** [comment]
Thanks for finding these. This might explain why @thofma had problems with
flint on Windows using MPIR-3.0.0.

**Comment by isuruf** [comment]
I can send a PR. For `flint_mpz_get_d_2exp` what should be the type? Previously it was `slong` regardless of MPIR or GMP.

**Comment by wbhart** [comment]
I guess it should still be slong. We have a file gmpcompat.h which contains
versions of the code for use with GMP instead of MPIR. Typically this
involves taking the actual GMP code and replacing long with slong
throughout.

**Comment by isuruf** [comment]
Yes, that's because GMP used long* and MPIR-v2 used slong*. Now both GMP and MPIR-3.0.0 use long* in `mpz_get_d_2exp`

**Comment by wbhart** [comment]
That's annoying. Flint relies on the old MPIR semantics. I don't understand
why this was changed in MPIR.

**Comment by wbhart** [comment]
The reason for the change was explained here [1].

Obviously I should have said something at the time!

Bill.

[1] https://groups.google.com/forum/#!topic/mpir-devel/lTQ44UotiH0

**Comment by wbhart** [comment]
The following changes are required in Flint if there is ever a new MPIR release with Brian's changes, which he describes as follows:

I have implemented the proposed change to MPIR in my repository by
adding two new functions:

mpir_si mpz_get_2exp_d (double *r, mpz_srcptr src);
mpir_si mpf_get_2exp_d (double *r, mpz_srcptr src);

Everything works fine so this now offers a fix for the Windows x64 bug
in FLINT.  This also offers a more robust MPIR API as I said yesterday

The changes needed in FLINT are very small and in only two files:

in dlog.c:
```
#if defined(__MPIR_VERSION)
        slong e;
#else
        long e;
#endif

        s = mpz_get_d_2exp(&e, COEFF_TO_PTR(*x));

        return log(s) + e * 0.69314718055994530942;
    }
```

and in get_s_2exp.c:
```
#if defined(__MPIR_VERSION)
       return mpz_get_d_2exp(exp, COEFF_TO_PTR(d));
#else
       long exp2;
       double m = mpz_get_d_2exp(&exp2, COEFF_TO_PTR(d));
       *exp = exp2;
       return m;
#endif
```

**Comment by wbhart** [comment]
Note: those are not the changes to be made. Those are how the files currently appear.

**Comment by wbhart** [comment]
Flint seems to work just fine with MPIR-3.0.0 now. It was fixed a long while ago, including insertion of code for later versions of MPIR which would use Brian's new code.
