### ISSUE TITLE
Fix n_prime_pi_bounds and n_is_oddprime_binary for small input

### ISSUE THREAD

**Issue by fredrik-johansson** [wbhart/flint2#34]
n_prime_pi_bounds divides by zero if you pass n = 0 or 1. Another problem with the function is that it relies on floating-point arithmetic (there is probably a model of Bulgarian wristwatch on which the rounding goes the wrong way).

Here's a possible replacement:

    extern const unsigned char FLINT_PRIME_PI_ODD_LOOKUP[];

    void n_prime_pi_bounds(ulong *lo, ulong *hi, mp_limb_t n)
    {
        if (n < FLINT_PRIME_PI_ODD_LOOKUP_CUTOFF)
        {
            if (n < 3)
                *lo = *hi = (n == 2);
            else
                *lo = *hi = FLINT_PRIME_PI_ODD_LOOKUP[(n-1)/2];
        }
        else
        {
            /* 14/10 < 1/log(2)*/
            *lo = (n / (10 * FLINT_CLOG2(n))) * 14;
            /* 19/10 > 1.25506/log(2) */
            *hi = (n / (10 * FLINT_FLOG2(n)) + 1) * 19;
        }
    }

This change breaks n_is_oddprime_binary, however (test fails at d = 139). There is probably an off-by-one error in the way that function uses the starting bounds, making it fails when the bounds are exact.

**Comment by wbhart** [comment]
I've merged this patch.

The is_oddprime_binary function was doing a lookup in a table of primes using the *number* of primes, rather than their index in the table.

This is now fixed in trunk.
