### ISSUE TITLE
make check fails, flint_abort undefined

### ISSUE THREAD

**Issue by rwst** [wbhart/flint2#373]
```
mkdir -p build/test
    CC   build/test/t-invert_limb
    CC   build/test/t-sub_dddmmmsss
    CC   build/test/t-count_trailing_zeros
    CC   build/test/t-udiv_qrnnd
/tmp/ccNq3PFF.o: In function `main':
/home/ralf/flint2/test/t-invert_limb.c:45: undefined reference to `flint_abort'
collect2: error: ld returned 1 exit status
Makefile:267: recipe for target 'build/test/t-invert_limb' failed
make[1]: *** [build/test/t-invert_limb] Error 1
make[1]: *** Waiting for unfinished jobs....
/tmp/ccd6nWiG.o: In function `main':
/home/ralf/flint2/test/t-count_trailing_zeros.c:42: undefined reference to `flint_abort'
/home/ralf/flint2/test/t-count_trailing_zeros.c:42: undefined reference to `flint_abort'
/home/ralf/flint2/test/t-count_trailing_zeros.c:42: undefined reference to `flint_abort'
/home/ralf/flint2/test/t-count_trailing_zeros.c:42: undefined reference to `flint_abort'
/home/ralf/flint2/test/t-count_trailing_zeros.c:42: undefined reference to `flint_abort'
collect2: error: ld returned 1 exit status
Makefile:267: recipe for target 'build/test/t-count_trailing_zeros' failed
make[1]: *** [build/test/t-count_trailing_zeros] Error 1
/tmp/ccZZ41wG.o: In function `main':
/home/ralf/flint2/test/t-sub_dddmmmsss.c:51: undefined reference to `flint_abort'
collect2: error: ld returned 1 exit status
```

**Comment by wbhart** [comment]
flint_abort() is defined in exception.c, which is explicitly included in
SOURCES in Makefile. I can only guess that you need to run configure again.

**Comment by rwst** [comment]
No success after `make distclean; configure`. Any ideas what to do?

**Comment by rwst** [comment]
Same with a fresh clone, `configure; make check`, so it's real.

**Comment by wbhart** [comment]
No idea whatsoever. We use flint_abort all the time, on a variety of
machines.

**Comment by rwst** [comment]
I'm on it.

**Comment by rwst** [comment]
The reason is that the `-L` options in the compile command are ordered such that the path of the just compiled library comes after that of a possibly system-wide installed libflint. In my case that system-installed flint is older and does not have `exception.c`. The `-L` options come from LDFLAGS which has some paths set in my case.

So the real cause is that `$(LDFLAGS)` comes before `$(LIBS)`, and I think it should be vice versa so `$(LDFLAGS)` should go at the end of the `CC` command. PR follows.
