### ISSUE TITLE
Autoconfiscate flint

### ISSUE THREAD

**Issue by embray** [wbhart/flint2#408]
It's not immediately clear to me why flint has a hand-written `configure` script rather than using autoconf.  This came up because although its `configure` looks, superficially, like an autoconf script it does not support some standard options (e.g. `--libdir`).

If there's no specific reason for this (other than historical) I'm happy to do the work of converting this to use autoconf.

**Comment by wbhart** [comment]
This gets brought up regularly, and it's been tried numerous times before.
But the requirements for convincing the Flint developers of the utility of
switching to autotools as a complete replacement for the current system are:

1) Configure should take ~ 1s on reasonable hardware
2) The system should autodetect new files added to the source tree and
automatically build them when make is issued, without requiring reconfigure
or manual modification of the autoconf files
3) The current dependency tracking should be preserved
4) It must be possible to easily run individual tests and possible to test
an entire module and of course the whole of Flint
5) Adding additional modules to Flint should be trivial
6) Whoever does the conversion to autotools must make a commitment to fully
supporting it going forward, as we don't have the expertise or time
7) The autotools system should in no way create additional dependencies to
build Flint
8) All the existing targets (or equivalents), including docs, profiling,
tests, etc. should be supported

As I think that most of the above are simply not possible with Autotools,
what we are really talking about here is providing an autotools build which
is distributed with the released version of Flint only, and to continue
using the current hand-written configure script for development purposes.

I would support this, so long as someone else implements it and continues
to maintain it and so long as it doesn't get in the way of the developers,
i.e. some script would have to exist to switch the build systems, and the
default in the repo should be the developer's build system (make dist could
switch it to the autotools system).

I absolutely will not be supporting autotools myself as I do not have time
to do this. But I welcome anyone who wants to sign on to maintaining this
themselves. But we need to be very clear that it won't replace the current
system for the developers of Flint.

**Comment by embray** [comment]
I'm not even suggesting a full switch to using automake.  Just autoconf for generating the configure script.  With caching enabled this can be quite fast.

**Comment by wbhart** [comment]
I'm not sure exactly what you mean, but the difficulty with maintaining the
configure script using autoconf is that I would need to learn how to use
autoconf to add new features to Flint's configure. And I really don't want
to do that. For one thing, I find the autotools documentation to be utterly
impenetrable, and always have.

**Comment by xoviat** [comment]
So CMake can meet all of these requirements except for the "configuration in under one second."

**Comment by xoviat** [comment]
@wbhart Would you be open to switching to CMake? I can do the port.

**Comment by wbhart** [comment]
You can add a CMake build script if you want, for people who want to use
it. But I won't be switching to CMake and I won't be putting time into
maintaining it myself.

Are you sure it's even possible without adding dependencies (like CMake) to
Flint?

**Comment by fredrik-johansson** [comment]
There is a CMake script in Arb. It should be enough to copy it (with trivial changes).

There's no reason to remove the existing build system, though.

**Comment by xoviat** [comment]
I don't think it's fair to ask anyone else to maintain something unless you're paying them for it. However, I know that you had resisted adding a CMake script to mpir, even though no one was asking you to spend time maintaining it and even though others would benefit.

> Are you sure it's even possible without adding dependencies (like CMake) to Flint?

How do you mean? CMake is available on all modern unix distributions, and GNU Make is a build dependency for makefiles.

**Comment by wbhart** [comment]
On 27 February 2018 at 22:57, xoviat <notifications@github.com> wrote:

> I don't think it's fair to ask anyone else to maintain something unless
> you're paying them for it. However, I know that you had resisted adding a
> CMake script to mpir, even though no one was asking you to spend time
> maintaining it and even though others would benefit.
>
I'm not sure what you mean. I'm not asking anyone to add CMake support, let
alone install it. No one is paying me to maintain it either, so I don't see
your point.

> Are you sure it's even possible without adding dependencies (like CMake)
> to Flint?
>
> How do you mean? CMake is available on all modern unix distributions, and
> GNU Make is a build dependency for makefiles.
>
There's a difference between being available and being installed. Not
everyone has root access to install it on the system they use.

**Comment by wbhart** [comment]
install -> maintain (typo)

**Comment by xoviat** [comment]
> I'm not sure what you mean. I'm not asking anyone to add CMake support, let
alone install it. No one is paying me to maintain it either, so I don't see
your point.

My point is that I cannot and have not asked you to add CMake support. However, in the case of MPIR, you had rejected CMake support that everyone who was going to use CMake approved. I was simply asking whether you would be okay with adding CMake support here.

**Comment by wbhart** [comment]
On 27 February 2018 at 23:20, xoviat <notifications@github.com> wrote:

> I'm not sure what you mean. I'm not asking anyone to add CMake support, let
> alone install it. No one is paying me to maintain it either, so I don't see
> your point.
>
> My point is that I cannot and have not asked you to add CMake support.
> However, in the case of MPIR, you had rejected CMake support that everyone
> who was going to use CMake approved. I was simply asking whether you would
> be okay with adding CMake support here.
>
You can add it, so long as it doesn't interfere with the rest of Flint, and
so long as I'm not expected to maintain it.

MPIR is a different story. There is no way anyone is going to be able to
add fully working CMake support for MPIR without an absolutely gargantuan
effort. What was being proposed there was a half-baked effort that would
have just added broken clutter to a very mature library. Whoever proposed
it there simply didn't appreciate how much work it would be. CMake is not
magic, and MPIR is an extreme outlier.

If someone was proposing to create a CMake port for MPIR as capable as the
current autotools installation point for point, I would have considered it.
One of the main jobs of a maintainer is to ensure that utter crap is not
merged. And I'm not even very good at that!

**Comment by embray** [comment]
A configure.ac template doesn't have to contain much more than a shell script outside of some standard boilerplate.  After all, all it is is a pile of text macros for generating a shell script.  The main advantage would be to generate a `configure` script that is fully compatible with other tools that expect an autoconf-generated `configure`, in terms of what arguments it accepts, etc. (supporting all those arguments would require a little tweaking but not much).

At the very least it would be nice if this hand-written `configure` were made compatible with an autconf `configure` by adding some missing arguments (e.g. `--libdir`, which motivated this issue), or if the script were renamed to something else (e.g. `Configure`?) so that there's no confusion.

**Comment by wbhart** [comment]
I think we have cmake now (IIRC).
