### ISSUE TITLE
Versioning the shared library? Binary backwards compatibility guarantees?

### ISSUE THREAD

**Issue by fingolfin** [wbhart/flint2#41]
Hi there,
I am working on packaging flint 2.4 for Fink (a Mac OS X package manager). Doing that, I noticed that your custom build system builds a dynamic library that is not setting a compatibility_version.

Now, I can workaround that, e.g. by manually relinking the .dylib file. But the fact that the library is not versioned in any meaningful way immediately raises the question whether newer versions of the flint shared library will be backwards compatible on the ABI / binary level. E.g. is an executable linked against Flint 2.0 supposed to work when the shared library is upgraded to 2.4?

My hope is yes... but I couldn't find anything directly talking about this, nor any indirect hints (which in other projects are taken care of by library versioning -- which in turn of course is highly platform specific, which is why GNU libtool comes in handy for that).

Anyway: This is quite important to know for packaging purposes, as it affects how to package things: Do I make a flint2 package which is going to cover all 2.x release of flint? Or do I call it flint24 and then when 2.5 comes out, call that 2.5, to make sure I can install both versions in parallel (necessary to keep already compiled binaries working)? Or is compatibility possibly even broken by minor releases (e.g. 2.4.2 might or might not be binary backwards compatible)? In that case, I would probably only ship a static library.

Any pointers on this appreciated. Sorry if you cover this topic elsewhere and I missed it, in that case I would be grateful if you were to point me to the relevant discussion(s).

**Comment by wbhart** [comment]
I've attempted to version the library. Testing on OSX is needed.

**Comment by wbhart** [comment]
All seems to be ok on OSX.
