### ISSUE TITLE
smul_ppmm function missing on amd64

### ISSUE THREAD

**Issue by tthsqe12** [wbhart/flint2#411]
Calls to `smul_ppmm` on my 64bit x86 box do not generate the `imul` instruction. Around line 73 of longlong.h we need
```
#define smul_ppmm(w1, w0, u, v)                         \
  __asm__ ("imulq %3"                                    \
       : "=a" (w0), "=d" (w1)                           \
       : "%0" ((mp_limb_t)(u)), "rm" ((mp_limb_t)(v)))
```

However, the software fall back is around line 555 of longlong.h, and I'm not sure how to disable it in this case.

**Comment by wbhart** [comment]
It shouldn't be necessary to disable the fallback, I think. It should be
sufficient to just add the correct definition to the file at line 73.

If not, let me know and we can try to track down what is going wrong.

**Comment by tthsqe12** [comment]
If I add the definition at line 74, then the compiler warns about the redefinition on line 560.

**Comment by wbhart** [comment]
Ok, I guess you need to add && !(GMP_LIMB_BITS == 64 && defined
(__amd64__)) to the condition in the latter.

You can probably add this function for x86 32 bits as well, right?

I'm not actually sure why it's missing.
