### ISSUE TITLE
fq_zech_ctx_init assumes modulus is primitive

### ISSUE THREAD

**Issue by defeo** [wbhart/flint2#419]
The way the finite field elements are enumerated in this loop:

https://github.com/wbhart/flint2/blob/trunk/fq_zech/ctx_init.c#L140-L151

assumes that the field is defined by a primitive polynomial. If that is not the case, the reverse table has missing entries, consequently the construction of the log table will either segfault or corrupt memory.

Here's an example program that segfaults on my system before reaching the final loop:

```c
#include "fq_zech.h"
#include "fq_zech_poly.h"

void main() {
    fq_zech_ctx_t ctx;
    nmod_poly_t m;
    flint_rand_t state;
    int i;

    flint_randinit(state);

    nmod_poly_init(m, 23);
    nmod_poly_set_coeff_ui(m, 0, 16);
    nmod_poly_set_coeff_ui(m, 1, 12);
    nmod_poly_set_coeff_ui(m, 2, 1);
    nmod_poly_print_pretty(m, "X");
    printf("\n");

    fq_zech_ctx_init_modulus(ctx, m, "X");
    for (i = 0; i < 10; i++)
          printf("%ld,", ctx->zech_log_table[i]);
}
```

**Comment by wbhart** [comment]
Wow! Thanks for finding this.

Just to let you know, we are today discussing a possible implementation of
a new finite field type, which will try to store each element in a fixed
sized struct (probably one word) so that no allocations are done in
polynomials. It also looks like we (Daniel) will be implementing
multivariate polynomials over finite fields. I haven't discussed it with
Fredrik yet, so it might get canned if he has a better idea.

**Comment by defeo** [comment]
You're welcome. 

On the other hand, the Zech representation mostly makes sense for primitive polynomials, so I'm not quite sure what the fix is here.

At the very least, the documentation of `fq_zech_ctx_init_modulus` should be changed. I don't know if there are other places where this may be a problem.

Having a proper exception instead of a segfault would be nice.

**Comment by defeo** [comment]
Would this new representation only be for prime fields, or also for non-prime ones?

**Comment by wbhart** [comment]
Also non-prime ones, packed of course.

**Comment by wbhart** [comment]
Are you actually using non-primitive polynomials in the zech representation in your application?

I'd be happy with removing the fq_zech versions of your function altogether if they don't really make sense.

I think testing to make sure the polynomial is actually primitive is a little expensive, no? One would at least need to factor n - 1, right?

**Comment by wbhart** [comment]
Actually, I suppose factoring n-1 is no problem here, since n has to be very small for zech log tables anyway.

**Comment by wbhart** [comment]
By n I mean p^k I guess.

**Comment by defeo** [comment]
I don't need non-primitive polynomials. The segfault in #351 happens here: https://github.com/wbhart/flint2/pull/351/files#diff-fbd09fdfa015db006894da563f5d1ac3R94

That's in the test code, and that's just because I want to construct a random `fq_zech_ctx` with a given degree (and I'm stupidly using `poly_randtest_monic_irreducible` to build the modulus). What I would really need in #351, is a function to create a random primitive polynomial.

I can write that function as part of the solution to this issue. I haven't checked how hard that would be, but, as you said, factoring n-1 is no problem.

**Comment by wbhart** [comment]
Ah ok, that makes sense. We probably should have a random primitive function anyway, so maybe that is the best way forward.
