### ISSUE TITLE
Compilation failure on MSVC

### ISSUE THREAD

**Issue by duhadler** [wbhart/flint2#420]
I have just downloaded the current flint trunk version from 20/11/2017 and ran into the following two compiler errors using MSVC 2017:

In flint\\fmpz_mpoly\mul_heap_threaded.c:
All occurrences of the variable "small" (defined in line 50) in this file should be changed into "small_", since on Windows, "small" is defined in rpcndr.h as #define small char (this is included through  
windows.h -> winscard.h -> wtypes.h -> rpcndr.h)

In flint\fmpz\link\fmpz_single.c:
In line 130:
	if (header_ptr->count != 0 || header_ptr->thread != pthread_self()) 

the MSVC compiler does not like the expression 
	header_ptr->thread != pthread_self()
insisting that thread as a ptw32_handle_t is a struct and not a pointer (which is indeed the case at least for pthreads on Windows).
Changing line 130 to:
	if (header_ptr->count != 0)
will make things compile, but of course this looses the intended functionality.

With these changes made, flint compiled both on 64 bit and 32 bit.

**Comment by wbhart** [comment]
Thanks for letting us know about these.

**Comment by wbhart** [comment]
These appear to have been resolved in trunk, and as of today, everything passes on MSVC both 32 and 64 bits.
