### ISSUE TITLE
Cmake usage in Clion instead of MakeFile

### ISSUE THREAD

**Issue by akrsnr** [wbhart/flint2#424]
I'd like to use flint2 on Clion. To do it, I need CMakelist.txt related to flint2. Is there any option to use flint2 directly in Clion? I tried to add `include_directories(../afolder/flint)`, then when I want to use simple variable like `flint::fmpzxx x1, y1;`, I get the error, 
`flint/flintxx/../flint.h:47:10: fatal error: 'config.h' file not found
#include "config.h"`
If I run configure, I get config.h but not object file of course before make. I mean is there any way to use and run the library directly by Cmake?

**Comment by wbhart** [comment]
Cmake is now there IIRC.
