### ISSUE TITLE
Compiler error

### ISSUE THREAD

**Issue by akrsnr** [wbhart/flint2#425]
I have installed flint by ./configure, make and make install
"/usr/local/lib" libflint.a
"/usr/local/include/flint" header files

When I run the code,
```
#include <iostream>
#include <flint/fmpzxx.h>

using namespace std;

int main()
{
    flint::fmpzxx yz;
}

```
I get,
```
Undefined symbols for architecture x86_64:
  "__fmpz_clear_mpz", referenced from:
      _fmpz_demote(long*) in main.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
How can I solve it?

**Comment by wbhart** [comment]
You need to link against Flint. In particular you have to supply the
-L/path/to/flint and -lflint options to gcc/clang.

You will also need to do the same for mpir and mpfr.

**Comment by akrsnr** [comment]
clang: warning: -lflint: 'linker' input unused [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-L/usr/local/include/' [-Wunused-command-line-argument]
[100%] Linking CXX executable untitled4
Undefined symbols for architecture x86_64:
  "___gmpz_set_ui", referenced from:
      fmpz_set_ui(long*, unsigned long) in main.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by akrsnr** [comment]
Do I need mpir and mpfr to use flint? I don't understand.
After adding -lflint
still I get the error
```
Undefined symbols for architecture x86_64:
  "___gmpz_set_ui", referenced from:
      fmpz_set_ui(long*, unsigned long) in main.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by wbhart** [comment]
On 5 December 2017 at 13:50, Soner <notifications@github.com> wrote:

> Do I need mpir and mpfr to use flint?
>
Yes.


> I don't understand.
> After adding -lflint
> still I get the error
>
> Undefined symbols for architecture x86_64:
>   "___gmpz_set_ui", referenced from:
>       fmpz_set_ui(long*, unsigned long) in main.cpp.o
> ld: symbol(s) not found for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
>
> It's looking for the MPIR library. These are symbols in MPIR.

**Comment by wbhart** [comment]
Or you can use GMP instead of MPIR of course!

**Comment by akrsnr** [comment]
Sir, I have already installed on GMP on my computer, but when I remove -lmpir I get
```
Undefined symbols for architecture x86_64:
  "___gmpz_set_ui", referenced from:
      fmpz_set_ui(long*, unsigned long) in main.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
I'm struggling with the library 3 hours to use.

**Comment by wbhart** [comment]
If you want to use MPIR then it's -lmpir, if you want to use GMP then it's
-lgmp.

This process of linking against libraries is completely standard, and is
not specific to Flint. You can find lots of documentation online about how
to link C programs against libraries. To use Flint, you need to link
against flint, mpir and mpfr (or you can use gmp instead of mpir if you
want).

**Comment by wbhart** [comment]
Actually, if you compiled mpir with the --enable-gmpcompat option then you
can link against it using -lgmp
