### ISSUE TITLE
fmpz t-is_perfect_power segfaults

### ISSUE THREAD

**Issue by wbhart** [wbhart/flint2#431]
As the title says, there is a segfault when running this test.

**Comment by wbhart** [comment]
Seems to be a problem, according to valgrind.

**Comment by fredrik-johansson** [comment]
valgrind output is clean for me. Was this not fixed in b0098d2b4cb5b0f79f922c63c64cadfc59dc0bd3 ?

**Comment by wbhart** [comment]
I don't find the original report. Six months earlier, an uninitialised value was found with valgrind when running fmpz_is_prime on:

162238762522632308445231705601071288606737783890008944005716062319489350564871578581612172254100334381721445556525705919685238909781829160608439869026026477979116887892207238861279189460347557964692819406953105082147019398757392645678671311233791388375138850067994682727058138431187433771318524240651341008305530211820422897458328135480720062657278965188596745882774908467481930231098122483413011133324108380571476033465185998157717896785922764422319850445183795081403717665329192880475733070444328659565162243267248654103961772252207680941673103710345465017960286131579692011689275211391386242123007

I'll keep looking for the report about the segfault though. (This wasn't a segfault.)

**Comment by wbhart** [comment]
Found it. The segfault occurs under MSVC 32 bit. I have no additional details:

fmpz/test/t-is_perfect_power ..........................................***Exception: SegFault  1.15 sec
is_perfect_power....

**Comment by wbhart** [comment]
The fmpz_is_prime issue no longer exists.

**Comment by wbhart** [comment]
As MSVC 32 bit is passing on CI, this issue appears to be resolved.
