### ISSUE TITLE
Problem under Windows: __locale_ctype_ptr not found

### ISSUE THREAD

**Issue by stla** [wbhart/flint2#432]
Hello,
 I've compiled `flint` with msys2 under Windows. The compilation works fine but when I compile an example I get: 
```
path/to/libflint.a(printf.o):printf.c:(.text+0x6e): undefined reference to `__locale_ctype_ptr'
path/to/libflint.a(fmpz_poly_set_str.o):set_str.c:(.text+0xd7): undefined reference to `__locale_ctype_ptr'
```
I've googled "locale_ctype_ptr" and there are many reports of similar issues, unrelated to flint. I didn't find a solution.

**Comment by wbhart** [comment]
Unfortunately we don't know either, and cannot replicate.
