### ISSUE TITLE
rows * cols can overflow in XXX_mat_init()

### ISSUE THREAD

**Issue by jdemeyer** [wbhart/flint2#433]
The various matrix initialization functions (such as `fmpz_mat_init`) calculate `rows * cols`. There is no check for overflow of this multiplication. Should such a check be added?

Downstream: https://trac.sagemath.org/ticket/24459

**Comment by wbhart** [comment]
I have no objection, but note that a matrix of that size could not be
constructed on any realistic computer, and for the most part, Flint assumes
the user doesn't supply faulty information and leaves it up to the CAS to
sanitise input.

In the long run, I'd like to add a lot more flint_asserts and so on, but so
far I haven't found the time to work on this. The most urgent one is to
either deal with Z/nZ unconditionally, or to raise exceptions when an
impossible inverse is hit. We probably do this pretty inconsistently at the
moment.

Recently there has been some developments in a new fast algorithm for
resultant over Z/nZ, so there is some hope in this direction, but we are
probably years away from dealing with the issue comprehensively.

**Comment by jdemeyer** [comment]
> note that a matrix of that size could not be constructed on any realistic computer

Of course not. My point is that it should correctly detect this and raise an error. Right now, for large but non-overflowing values of `rows * cols`, the allocation in `flint_calloc()` will fail and correctly raise an error. For even larger (overflowing) values of `rows * cols`, it might incorrectly allocate too few bytes, leading to random breakage.

> Flint assumes the user doesn't supply faulty information and leaves it up to the CAS to sanitise input.

Fine for me. But in that case, you should document that in the documentation of `fmpz_mat_init`.

So there are two possible solutions (and the FLINT maintainers should decide):

(A) Check for overflow in `XXX_mat_init()`.

(B) Document that the value of `rows * cols` should fit in a `size_t`.

**Comment by wbhart** [comment]
I agree both should ultimately be done. By the way, we use slong, not
size_t for sizes. This is equivalent to an mp_limb_signed_t on all
platforms.

**Comment by dimpase** [comment]
@fredrik-johansson  By the way, arb has a similar issue in its matrix code.
