### ISSUE TITLE
Why does a seemingly valid factorization have a 0 sign?

### ISSUE THREAD

**Issue by carlcook** [wbhart/flint2#436]
https://github.com/wbhart/flint2/blob/0e46068e3e405b59c7587c635a849b69c61f40a8/fmpz_factor/print.c#L27

This seems like a bug to me.

How about this instead:

```
if (factor->sign == 0)
{
    if (factor->num == 0)
    {
            flint_printf("0");
    }
}
```

**Comment by wbhart** [comment]
This is supposed to indicate the factors have sign 0, not positive sign.

Can you give an example where this is not the case?

**Comment by carlcook** [comment]
Ah, I see, that makes sense thanks.

This makes me start to think that the qsieve_factor() function is not returing valid factors.

Given the following:

```
#include "fmpzxx.h"
#include "qsieve.h"

using namespace flint;

int main(int argc, char* argv[]) {
    if (argc != 2) {
        flint_printf("Syntax: fac <integer>\n");
        return EXIT_FAILURE;
    }

    fmpz_t n;
    fmpz_factor_t factors;
    FLINT_TEST_INIT(state);

    fmpz_init(n);
    fmpz_factor_init(factors);
    fmpz_set_str(n, argv[1], 10);
    qsieve_factor(factors, n);
    fmpz_factor_print(factors);

   return 0;
}
```

With input:
```
$ ./fac 490
```
I get this
```
0
```
Where I'd expect this:
```
2 * 5 * 7^2
```

**Comment by wbhart** [comment]
You probably want to use fmpz_factor, not qsieve factor for numbers that
small. I don't think qsieve will factor numbers that small.

**Comment by carlcook** [comment]
Sorry, that example was just for simplicity. I was factoring a 66 digit number (and the code ran incredibly fast... less than a minute on a single mid-spec CPU on a virtual box).

**Comment by wbhart** [comment]
But the factors still printed as zero?  I guess it's possible the QS is not
populating the factor struct properly.

**Comment by wbhart** [comment]
Fixed in trunk.
