### ISSUE TITLE
How to avoid mangling pointers in fmpz_t

### ISSUE THREAD

**Issue by tthsqe12** [wbhart/flint2#443]
I hope to get some ideas/feedback on the fmpz_t here.

Set n = FLINT_BITS.
An fmpz is currently either
 - a small machine integer (x) in (-2^(n-2), +2^(n-2)), or
 - a pointer (p)

These are stored in a machine word (u) resepectively as
 - u = x
 - u = p>>2 + 2^(n-2)

In order to tell if u is a pointer, it is necessary to compare u>>(n-2) to 1.

If it is desirable to avoid mangling pointers, what about changing fmpz's to:
 - a small machine integer (x) in [-2^(n-2), +2^(n-2)), or
 - a pointer (p)

These would be stored in a machine word (u) resepectively as
 - u = 2*x + 1
 - u = p

Now testing if u is a pointer is a simple u&1 == 0, and multiple pointers can be tested at once. 

If the target processor has an overflow flag, the basic operations of add, sub, and mul can be done efficiently inline.

Example:
```
fmpz_add_inline(a, b, c):
    if !(a&b&c&1)
        return fmpz_add(a, b, c)
    else
        t = ADD_CHECK_OVERFLOW(a, b-1)
        if OVERFLOW
            fmpz_set_si(a, t/2)
        else
            a = t

**Comment by fredrik-johansson** [comment]
It should be noted that Arb relies rather heavily on the fmpz representation right now.

**Comment by tthsqe12** [comment]
Could we at least settle on some macros for manipulating fmpz's directly? There are many places in the fmpz_mpoly code that I consider to be dirty where such direct manipulations are done in place of a call to fmpz_set_si. Such an example is https://github.com/wbhart/flint2/blob/fmpz_mpoly/fmpz_mpoly/divrem_monagan_pearce.c#L260

**Comment by wbhart** [comment]
Yes, let's work some out. The fmpz_mpoly code is probably one place where
performance is critical, so we should get it right there. The other place
is probably Arb.

**Comment by tthsqe12** [comment]
After giving this some though, I have decided that mangling the pointers is probably the best option and the current mangling scheme is also probably best.
