### ISSUE TITLE
flint_test_multiplier declared in flint.h but not in libflint.so

### ISSUE THREAD

**Issue by videlec** [wbhart/flint2#451]
```
$ grep flint_test_multiplier flint.h
FLINT_DLL int flint_test_multiplier(void);
$ nm libflint.so|grep flint_test_multiplier
```

**Comment by wbhart** [comment]
I guess it is more or less harmless, as it is only ever used from test code, which compiles in the relevant file. It probably should be declared in a test_helper.h instead. But I guess it's not a major issue.

**Comment by videlec** [comment]
I also believe so (I just encountered it while I was writing the configure/Makefile for antic).

**Comment by wbhart** [comment]
It's nowadays defined in test_helpers.h.
