### ISSUE TITLE
mpfr_root is deprecated

### ISSUE THREAD

**Issue by wbhart** [wbhart/flint2#452]
I'm not sure what it is replaced by, but mpfr_root is deprecated:

number_of_partitions_mpfr.c: In function ‘sinh_cosh_divk_precomp’:
number_of_partitions_mpfr.c:371:5: warning: ‘mpfr_root’ is deprecated [-Wdeprecated-declarations]
     mpfr_root(ch, ex, k, MPFR_RNDN);
     ^
In file included from /home/wbhart/.julia/v0.6/Nemo/deps/flint2/arith.h:22:0,
                 from number_of_partitions_mpfr.c:13:
/home/wbhart/.julia/v0.6/Nemo/local/include/mpfr.h:693:21: note: declared here
 __MPFR_DECLSPEC int mpfr_root (mpfr_ptr, mpfr_srcptr, unsigned long,

**Comment by fredrik-johansson** [comment]
See https://github.com/fredrik-johansson/arb/commit/a7d9c0b1c11745e8a053c7d0659e3166db2f7e18

**Comment by wbhart** [comment]
Thanks!

**Comment by fredrik-johansson** [comment]
This is already fixed.
