### ISSUE TITLE
[one-liner patch] Broken latex code

### ISSUE THREAD

**Issue by SnarkBoojum** [wbhart/flint2#470]
A bug was reported on the Debian package failing to build with texlive 2018, with a trivial patch to solve the issue ; in fmpz_mat/doc/fpmz_mat.txt, a $m$ ×  $n$ should be a $m \times n$ (line 1243).

**Comment by SnarkBoojum** [comment]
Or remove the two $ signs in the middle: $m × n$ since it's apparently what is done everywhere else...

**Comment by SnarkBoojum** [comment]
Ah, no, just removing the $ signs isn't enough: one needs to change it like it's done elsewhere in the file. (why not use $m\times n$?)

**Comment by wbhart** [comment]
Yeah. $m\times n$ will be fine. A pull request would help.

**Comment by wbhart** [comment]
I believe this is fixed.
