### ISSUE TITLE
strange behavior of fmpq_poly_set_str

### ISSUE THREAD

**Issue by videlec** [wbhart/flint2#474]
With
```
err = fmpq_poly_set_str(p, "3  -2 0 1");
```
I obtain correctly `x^2 - 2` and `err` is set to `0`. But with only one space after the length
```
err = fmpq_poly_set_str(p, "3 -2 0 1");
```
`err` is set to zero and the minus sign is ignored. Wouldn't be better to set `err` to `1` in the second situation? Even stranger situation does not lead to error such as
```
err = fmpq_poly_set_str(p, "3 X-2 0 1")
```
(which sets also to `x^2 - 2`).

I would be happy to provide a pull request if we agree that `err` should be set to `1` if there is anything else than two spaces after the length.

**Comment by wbhart** [comment]
Yes, I agree the only correct format is two spaces, and so error should be set in any other case. The PR would be most appreciated.

**Comment by videlec** [comment]
On it! Will also provide `fmpq_set_str` which I miss.

**Comment by videlec** [comment]
What should I do with the empty string? (currently we get the zero polynomial)

**Comment by wbhart** [comment]
My inclination is to say it is invalid input. I can't promise no one will complain, but I don't personally see any problem with disallowing it.
