### ISSUE TITLE
make check failure

### ISSUE THREAD

**Issue by keithbriggs** [wbhart/flint2#484]
config_gauss....../build/aprcl/test/t-config_gauss: symbol lookup error: ../build/aprcl/test/t-config_gauss: undefined symbol: config_gauss_init

**Comment by wbhart** [comment]
What is the OS? We are not seeing this problem in testing.

**Comment by keithbriggs** [comment]
Ubuntu 14.04.  Everything up-to-date.


________________________________

**Comment by keithbriggs** [comment]
Just tried it on Ubuntu 16.04 and I do not get the problem.

**Comment by isuruf** [comment]
Do you have another installation of flint? Which version of flint are you using?

**Comment by keithbriggs** [comment]
I've got /usr/lib/sagemath/local/lib/libflint.so, but I don't think that will be found by the test process.

I checked out the latest flint sources yesterday,

**Comment by wbhart** [comment]
By latest, do you mean from GitHub, or the latest tarball from the website?

I don't see why either should be problematic on Ubuntu 14.04, but it's worth knowing.

**Comment by keithbriggs** [comment]
It was flint2-trunk from github.

**Comment by wbhart** [comment]
Unable to replicate.
