### ISSUE TITLE
make install fails because 'cp: Missing target file operand'

### ISSUE THREAD

**Issue by danieagle** [wbhart/flint2#485]
Debian Buster Amd64.
obs: in annex the configure command used.
obs: I used all srcs from git repositories.

Thanks in Avance!

Best whishes, Dani

root@eagle30:/home/dani/hds/jesus1/repositorios/GitHub/bignumlibs/flint2ecia/flint2# make install 
make[1]: Entering directory '/home/dani/hds/jesus1//repositorios/GitHub/bignumlibs/flint2ecia/flint2'
make[1]: Nothing to be done for 'shared'.
make[1]: Leaving directory '/home/dani/hds/jesus1/repositorios/GitHub/bignumlibs/flint2ecia/flint2'
mkdir -p "/usr/local/lib"
mkdir -p "/usr/local/include/flint"
cp  aprcl.h  ulong_extras.h  long_extras.h  perm.h  fmpz.h  fmpz_vec.h  fmpz_poly.h  fmpq_poly.h  fmpz_mat.h  fmpz_lll.h  mpfr_vec.h  mpfr_mat.h  mpf_vec.h  mpf_mat.h  nmod_vec.h  nmod_poly.h  mpoly.h  nmod_mpoly.h  fmpz_mpoly.h  fmpq_mpoly.h  nmod_poly_factor.h  arith.h  mpn_extras.h  nmod_mat.h  fmpq.h  fmpq_vec.h  fmpq_mat.h  padic.h  fmpz_poly_q.h  fmpz_poly_mat.h  nmod_poly_mat.h  fmpz_mod_poly.h  fmpz_mod_poly_factor.h  fmpz_factor.h  fmpz_poly_factor.h  fft.h  qsieve.h  double_extras.h  d_vec.h  d_mat.h  padic_poly.h  padic_mat.h  qadic.h  fq.h  fq_vec.h  fq_mat.h  fq_poly.h  fq_poly_factor.h  fq_nmod.h  fq_nmod_vec.h  fq_nmod_mat.h  fq_nmod_poly.h  fq_nmod_poly_factor.h  fq_zech.h  fq_zech_vec.h  fq_zech_mat.h  fq_zech_poly.h  fq_zech_poly_factor.h NTL-interface.h flint.h longlong.h config.h gmpcompat.h fft_tuning.h fmpz-conversions.h profiler.h templates.h exception.h hashmap.h  fq_vec_templates.h  fq_mat_templates.h  fq_poly_templates.h  fq_poly_factor_templates.h  fq_templates.h "/usr/local/include/flint"
cp: falta o operando arquivo de destino após '/usr/local/include/flint'
Tente "cp --help" para mais informações.
Makefile:234: recipe for target 'install' failed
make: *** [install] Error 1

[configure_do_flint.txt](https://github.com/wbhart/flint2/files/2081887/configure_do_flint.txt)

**Comment by danieagle** [comment]
Hi!

  I partially discover one culprit: the EXT_HEADERS is just one blank space; I Changed configure to use quoted blank space between extensions and this partially work with a new error. the new error is duplicating the path to the files in extensions. :-)

e.g.:
root@eagle30:/home/dani/hds/jesus1/repositorios/GitHub/bignumlibs/flint2ecia/flint2# ../configure_do_flint_v2.txt 
Configuring...x86_64-Linux
Testing __builtin_popcountl...yes
Testing native popcount...yes
Testing __thread...yes
Testing fenv...yes
FLINT was successfully configured.
root@eagle30:/home/dani/hds/jesus1/repositorios/GitHub/bignumlibs/flint2ecia/flint2# make
make[1]: Entering directory '/home/dani/hds/jesus1/repositorios/GitHub/bignumlibs/flint2ecia/flint2'
    CC   build/printf.lo
    CC   build/fprintf.lo
    CC   build/sprintf.lo
    CC   build/scanf.lo
    CC   build/fscanf.lo
    CC   build/sscanf.lo
    CC   build/clz_tab.lo
    CC   build/memory_manager.lo
    CC   build/version.lo
    CC   build/profiler.lo
    CC   build/thread_support.lo
    CC   build/exception.lo
    CC   build/hashmap.lo
    CC   build/inlines.lo
mkdir -p build/interfaces
make[2]: Entering directory '/home/dani/hds/jesus1/repositorios/GitHub/bignumlibs/flint2ecia/flint2'
make[2]: *** 

************************** note the duplicate path ******************** :-)

/home/dani/hds/jesus1/repositorios/GitHub/bignumlibs/flint2ecia/arb//home/dani/hds/jesus1/repositorios/GitHub/bignumlibs/flint2ecia/arb/acb_hypgeom.h: Arquivo ou diretório inexistente.  Pare.

*************************************************************************** :-)

make[2]: Leaving directory '/home/dani/hds/jesus1/repositorios/GitHub/bignumlibs/flint2ecia/flint2'
Makefile:140: recipe for target 'libflint.so.13.5.2' failed
make[1]: *** [libflint.so.13.5.2] Error 2
make[1]: Leaving directory '/home/dani/hds/jesus1/SoliCoin_e_Cia/repositorios/GitHub/bignumlibs/flint2ecia/flint2'
Makefile:172: recipe for target 'library' failed
make: *** [library] Error 2

Debian AMD64 Buster gcc-8.

And Really Thanks for this excelent lib.

Best Wishes, Dani. :-)


[configure_do_flint_v2.txt](https://github.com/wbhart/flint2/files/2112854/configure_do_flint_v2.txt)

**Comment by alexjbest** [comment]
In your configure file you have extensions specified with a `\ ` between each one, at least on my machine this does not do the right thing what happens if you use simply a non-escaped space ` `?

You could also look at your `Makefile` after configure is run and see whether the paths look ok in there.

**Comment by danieagle** [comment]
Hi!

without \

make: execvp: /bin/sh: Lista de argumentos muito longa ( list of args too long)
Makefile:258: recipe for target 'build/CPimport.h' failed
make: *** [build/CPimport.h] Error 127

Best Wishes, Dani. :-)

**Comment by alexjbest** [comment]
Okay, so can you move those folders so that the extensions string isn't so huge?
Also do you actually need to install flint with arb + antic + bland simultaneously, it works with just plain flint right?

**Comment by wbhart** [comment]
Arb and antic have their own installs nowadays, and don't need to be
installed as extensions.

Also, if you have more than one extension, you have to put double quotes
around the whole lot together.

The CPimport thing shouldn't happen with a fresh checkout of Flint from the
repository. It usually happens with an old Makefile and a new Flint.

**Comment by danieagle** [comment]
just one extension works fine :-)
I'll use bland como extension and build others has stand alone.

p.s.: now I tried a fresh git and Cpimport error ocur.

Really thanks for the atention and libs :-)

[]'s Dani.

**Comment by wbhart** [comment]
We are not getting this error in testing.

Another possibility is you have an old version of libflint.so installed
somewhere.

The best I can think of is for you to try older commits. The behaviour of
CPimport was changed recently, so maybe it broke something. But we are not
seeing any problems ourselves, except when an old and new version of flint
or its Makefile conflict.

**Comment by danieagle** [comment]
Hi! 

Worked now with this setup:
[configure_do_flint_v4.txt](https://github.com/wbhart/flint2/files/2126975/configure_do_flint_v4.txt)

cd /root
git clone flint2
mv flint2 flint
git clone arb
git clone bland
git clone antic
cd arb
rpl -R  \"flint  \"\.\.\/flint 
cd ../bland
rpl -R  \"flint  \"\.\.\/flint 
cd ../antic
rpl -R  \"flint  \"\.\.\/flint 
cd ../flint
./configure_do_flint_v4.txt
make
make install (before make check, some tests use system headers)
make check

my issue changed to a whishlist: add more about shorten paths and add more about proceding with this huge setting (3 extensions).

I yet not tested myself the system headers, but I consider this issue closed :-)

Reaaly Thanks! :-)

[]'s Dani.
