### ISSUE TITLE
WORD_MAX macro name collision

### ISSUE THREAD

**Issue by bjodah** [wbhart/flint2#490]
In symengine both `flint.h` and a header from LLVM may be imported in the same translation unit,
this leads to a name collision (see https://github.com/symengine/symengine/issues/1438) since they
define a variable named `WORD_MAX` which is defined as a macro in flint:
https://github.com/wbhart/flint2/blob/22cdd6e6420575f0f6079c641d4fbe746b6174f2/flint.h#L133

Would it be possible for flint to prepend macro names with e.g. `FLINT_`? Or should third party codes (such as symengine) use another approach?

**Comment by bjodah** [comment]
Sounds good to me.

**Comment by wbhart** [comment]
I decided to take a different approach, which the GNU people have occasionally used:

If you #define FLINT_NO_WORDMAC before #including flint.h, these macros will not be exported from flint.h.
