### ISSUE TITLE
Non-asm sub_dddmmmsss is wrong

### ISSUE THREAD

**Issue by fredrik-johansson** [wbhart/flint2#503]
The fallback version of sub_dddmmmsss in longlong.h is plain wrong. I believe __t and __u should be replaced by -__t and -__u in the last line, but someone should double-check this.

**Comment by wbhart** [comment]
I can confirm it is incorrect and that __t and __u should be -__t and -__u.

In assembly language, it would be faster, but doing it faster in C is difficult. One can compare ml with sl for example to determine whether there is a borrow, but this is basically equivalent to doing a subtraction, so may as well take the result of the subtraction we've already done, as there is no portable way to capture the carry flag in C.

Anyhow, I have fixed this in trunk.
