### ISSUE TITLE
Build failure when including flint/fft.h

### ISSUE THREAD

**Issue by hendrikeerikson** [wbhart/flint2#508]
I am trying to compile an empty program that just includes flint and fft. I get an error in the header file fft.h:
```
/usr/include/flint/fft.h: In function ‘mp_limb_t mpn_sumdiff_n(mp_ptr, mp_ptr, mp_srcptr, mp_srcptr, mp_size_t)’:
/usr/include/flint/fft.h:82:25: error: invalid conversion from ‘void*’ to ‘mp_ptr {aka long unsigned int*}’ [-fpermissive]
         t = flint_malloc(n * sizeof(mp_limb_t));
             ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~
```
The program I'm trying to compile looks like this:
```
#include <gmp.h>
#include <flint/flint.h>
#include <flint/fft.h>

int main (int argc, char *argv[])
{
    return 0;
}
```

I am using Ubuntu 18.04, I tried both the apt package version of FLINT and compiling it from this repo. I can successfully build and run a program using flint that doesn't include fft.h.

**Comment by wbhart** [comment]
Thanks for the report. I guess you are using g++ instead of gcc. You will need to insert a cast from void* on that malloc in that case. Of course we should add it in flint so that people can compile this with g++ without an error message. It looks like it's been missed.

**Comment by wbhart** [comment]
Should be fixed in trunk.
