### ISSUE TITLE
libflint-dev flint.h not found

### ISSUE THREAD

**Issue by smkuls** [wbhart/flint2#512]
I pulled the package from `apt` and got this version `libflint-dev/stable,now 2.5.2-15`. I am still facing the issue #217 when I try to use flint.

Is it possible to have the package updated on `apt` with the latest version?

**Comment by wbhart** [comment]
We aren't responsible for the apt package, but they are probably waiting for us to do a new release. There's still some pretty big tickets to sort out before we can do another release, sorry. You can of course work from our GitHub trunk branch instead, with the understanding that some things are not release ready (anything in the old documentation should be more or less stable though).

**Comment by smkuls** [comment]
Is it okay if we keep this issue opened until the new release? I'd like to get notified so that I can follow up with the folks responsible for maintaining the apt package.

**Comment by wbhart** [comment]
That's fine by me.

**Comment by wbhart** [comment]
I'd really like to close this issue now, since we are going through doing a cleanup ready for the flint release, which we will be working on from 6 Jan to 31 Mar. The best way to be informed of a release is to subscribe to the very low traffic flint-devel.

**Comment by sbellem** [comment]
Hi, I am somewhat new to this problem. Just to provide context to those who may face the problem, would it possible to point to the _commit_ and _version_ in which the fix was made?

**Comment by wbhart** [comment]
There hasn't been a release yet. Therefore the problem cannot have been fixed by those who maintain the apt package!

**Comment by sbellem** [comment]
Thanks for your quick answer! Yes I understood that part ... I am wondering if I build the package myself using the code under this repository, from which commit is the fix included.

**Comment by wbhart** [comment]
Which fix?

**Comment by wbhart** [comment]
Oh you mean the fix for #217. It will of course be in trunk, since 2016. I don't know the commit, but I'm sure you can easily track it down if you look for what commits were made on that day.

**Comment by sbellem** [comment]
Yes, thanks! So I went ahead and built a docker image just in case that this may be of interest to people visiting this page. The image is at https://hub.docker.com/repository/docker/sbellem/flint2. This is work-in-progress, but in my local tests, the image has appeared to work.
