### ISSUE TITLE
opensuse, flint-dev package, flint.h error: config.h not found

### ISSUE THREAD

**Issue by pulmark** [wbhart/flint2#521]
Installed flint lib and development package into Linux OpenSuse Tumbleweed. Included flint.h in my app but build gives error that no config.h found. I checked /usr/include/flint directory and there is no config.h in that directory, flint.h refers to config.h (#include "config.h").

Is the OpenSuse package broken or do I need to run some configure script or build lib from git ?

**Comment by wbhart** [comment]
My guess would be the OpenSuse package is broken. Our make install is copying that into $PREFIX.

But maybe you could ask the OpenSuse package maintainer, as we don't maintain that directly ourselves.

**Comment by maiphi** [comment]
According to https://build.opensuse.org/package/show/science/flint the packaging rules for opensuse consider it illegal to include a config header with `#include "config.h"`, so this is considered an issue in FLint.

I submitted a bug report to opensuse in the hope that some kind of agreement can be achieved on this.
https://bugzilla.opensuse.org/show_bug.cgi?id=1169283

**Comment by wbhart** [comment]
It wouldn't be a huge big deal for us to rename our config file to flint-config.h. That gets around the "illegal" problem. The original issue was however a problem with the OpenSuse package, which didn't include this file.

**Comment by maiphi** [comment]
Let's see what the opensuse people have to say about this and what would be an acceptable solution for them.

**Comment by wbhart** [comment]
Well, they did already say on their ticket that renaming to flint-config.h would be acceptable.

Technically, we install into $PREFIX/include/flint, so they shouldn't be picking up our config.h by accident. However, it does make more work for their users if they are building projects against Flint and numerous other packages at the same time.

**Comment by maiphi** [comment]
I'm note sure how official the comment from https://build.opensuse.org/package/show/science/flint is and obviously it had no consenquence (to me personally, what you are doing seems quite common and reasonable). Since the package is broken hat the moment, this must have been an accident (if fixing it by including config.h violates the packaging rules, it should not have been packaged). So I hope that via the bug tracker we can trigger some kind of activity.
