### ISSUE TITLE
building with NTL support using cmake

### ISSUE THREAD

**Issue by dimpase** [wbhart/flint2#542]
Is this supported? Lack of the corresponding Cmake file makes one suspect that it is not.

**Comment by dimpase** [comment]
By the way, CGAL has https://github.com/CGAL/releases/blob/master/cmake/modules/FindNTL.cmake
which perhaps can do the job.

**Comment by dimpase** [comment]
See #543 towards a possible solution.

**Comment by isuruf** [comment]
Fixed in #543
