### ISSUE TITLE
6 problems with flint

### ISSUE THREAD

**Issue by tthsqe12** [wbhart/flint2#549]
(i) The nmod_poly_t stores its own context. While this looks nice when one is simply manipulating nmod_poly's, this is a real pain when building higher structures on top of them and it actually makes no sense from an interface point of view. There are three problems
   (1) Suppose I initialise polynomials A mod 3, B mod 5, and C mod 7. The current interface has no problem doing A = B*C and it makes a nonsensical output determined by the modulus of B or C (could be either).
   (2) every nmod_poly_t, fq_nmod_t, fq_nmod_poly_t, ... is twice as big as necessary because every nmod_poly_t is storing a redundant nmod_t.
   (3) suppose you are doing a modular algorithm and want to change the modulus of all of your polynomials but crucially _reuse_ the space already allocated to them. Instead of simply changing the modulus in a context object, you have to go into each polynomial and manually change the modulus stored in each one.
For these reasons I will be creating an nmod_polydr_t (nmod_poly's done right) that is simply an array of coefficients. The fq_nmod_t will eventually be typedef'ed to an nmod_polydr_t.

(ii) fq_nmod arithmetic is quite slow and currently has no support for delayed reduction. This is not unrelated to (i) above. The most outstanding function in this module is fq_nmod_mul, which basically guarantees that the result of any multiplication has at some point been reallocated to length 2*d from an initial and quite sufficient length of d+1.

(iii) The fmpz_t are cached in single mode. This is nice but the caching mechanism looks a bit unsafe from threads. The problematic point seems to be where one thread starts modifying/clearing fmpz_t created on another thread. If this usage of fmpz_t is to be disallowed, then the fmpz_t is almost useless from a multithreaded point of view.

**Comment by wbhart** [comment]
Rather than introduce a new module, why not put the new functions in the existing nmod_poly files and write the existing functions in terms of the new ones.

**Comment by tthsqe12** [comment]
@wbhart What do you think about something like this as the goal? The problem with the nmod_t is that is it a struct and not a pointer to struct. The nmod_ctx_t will wrap this in a pointer and this is what you will pass to the arithmetic functions.
```
typedef struct {
    nmod_t mod;
    /* could put other info here as well, but will bloat the obsolete nmod_poly_t */
} nmod_ctx_struct;

typedef struct {
    mp_limb_t * coeffs;
    slong alloc;
    slong length;
} nmod_polydr_struct;

typedef struct {
    nmod_polydr_t poly;
    nmod_ctx_t ctx; /* could also just be a nmod_t */
} nmod_poly_struct

```

**Comment by tthsqe12** [comment]
On second though, it might be better to simply leave the nmod_poly_struct alone. The rabbit hole is too deep.

**Comment by tthsqe12** [comment]
(iv) fmpz_mod_poly_t also stores its context (the p)!! This is especially egregious because now this is an allocated member. Could _fmpz_vec_scalar_mod_fmpz be sped up by passing some precomputed info besides p (that would properly be stored in a context object)?

**Comment by tthsqe12** [comment]
(v) the randstate is only 128 bits. Also, the return of n_randint is not uniformly distributed as advertised in the docs.

**Comment by fredrik-johansson** [comment]
My idea for a future major flint update has been to have a single type per mathematical type, and in particular a unified type replacing both nmod and fmpz_mod. You would have different packing sizes (like with multivariate exponents) and different kinds of precomputed inverse for different moduli.

**Comment by fredrik-johansson** [comment]
I think about 90% of uses of delayed reduction can be done with atomic dot product functions.

**Comment by tthsqe12** [comment]
(vi) the current threaded functions have no argument for passing a limit on the number of threads used. It will be very bad design to have no control over how many worker threads a function could spawn. Also, functions without "threaded" in their name can also spawn workers, and this is going to be a mess to fix.

@fredrik-johansson That is another idea that sounds great for the external end user interface but will probably be a trainwreck for the internals (i.e. is useless for internal use). In your new mod_poly_t you will need to have some flag that tells if the polynomial is implemented via word-sized arithmetic or arbitrary-sized arithmetic. This is one word of bloat unless the coeffs member is a union of mp_limb_t * and fmpz * and the flag is stored in a context object. Next, while the nmod_t is (almost) a proper context for word-sized mod p arithmetic using Barret reduction, there is currently no corresponding struct or infrastructure for Barret reduction for arbitrary-sized arithmetic. All reductions currently use the naive %p.
The other 10% of cases where the vectors that are to be dotted together are not known in advance is a big 10%.

**Comment by wbhart** [comment]
@fredrik-johansson If you were going to do this, then we'd also have to do the same for finite fields, i.e. one type for all finite fields. It all sounds like a lot of work for other people to handle the new types and for us to write all the code. Do either of us really have the time to do such a large amount of work?

I'm also not really sure I see how a combined nmod_poly/fmpz_mod_poly module would work. It sounds like it would be a bit messy internally.

I do think we need to sort Dan's issue out though. Having discussed it with Dan, I'm now more inclined to let him just implement a zmodn_poly module to eventually replace the existing nmod_poly module. At least this would uniformise the interface with the finite field interface, where all functions take a context object.

I really don't like the name nmod_polydr, and it bothers me a bit to just shove a bunch of new functions somewhere deep inside Flint rather than expose them in a module.

Also, Dan really has limited time to work on this, as the deliverables he's working on are due in a few months. Even if it is a bit messy for now, I think it is better to just get it done in a not too stupid way, and change the design later if we ever find the time (I doubt we will).

**Comment by tthsqe12** [comment]
Lets sleep on it a few more days. I don't need anything changed right away because I can work on a different algorithm in the mean time.

**Comment by tthsqe12** [comment]
The nmod_poly whose redundant nmod_t I need to change are deeply nested inside complicated structures. Going in there will be a very ugly kludge which I object to on aesthetic grounds. However, I will give it a shot. I just don't like reinforcing this bad design.
You all can rest easy. I have decided to simply accommodate nmod_poly by making my code ugly.

**Comment by tthsqe12** [comment]
@wbhart can we at least get an official (or unofficial) function in nmod_poly for initialising from/changing the modulus given an nmod_t?
```
nmod_poly_init_mod(nmod_poly_t a, nmod_t mod);
nmod_poly_change_mod(nmod_poly_t a, nmod_t mod);
```
Again, reuse of the already allocated coeffs is paramount in nmod_poly_change_mod, so it must literally just replace the mod member.

**Comment by wbhart** [comment]
We can certainly have such a function. But can I ask why you don't just work with the underscore functions directly? Don't bother with the nmod_poly_t's at all. Perhaps write a small amount of helper functions to deal with the memory allocation/aliasing cases you care about, but that perhaps handle multiple polys at once. This is probably how I would do it.

**Comment by wbhart** [comment]
Note that there is already FLINT_DLL void nmod_poly_init2_preinv(nmod_poly_t poly, 
                                      mp_limb_t n, mp_limb_t ninv, slong alloc);

It was introduced before we switched to using the mod struct, so takes its components. Of course I'm 100% happy with officially supporting one that takes the mod struct.

The one advantage of having nmod_poly contain its own mod struct is it is really easy for users. I think if we do ever decide to introduce a version that doesn't take the mod struct, we should rewrite the entire module to not take the struct, then write nmod_poly to work exactly as it currently does, in terms of the new version. The biggest problem with that by far is figuring out what to call the new module.

Anyhow, I'm glad you have decided not to go down that route for now @tthsqe12

**Comment by tthsqe12** [comment]
I can't just work with underscore functions because I depend heavily on fq_nmod_t and fq_nmod_poly_t, which I do not want to rewrite in terms of underscored functions. Also, fq_nmod has nmod_poly exposed in its interface. Mpoly will contribute 10k+ lines of inertia towards the current nmod_poly so that an even bigger force will be required to change it. May the force be with you if you ever do decide to do nmod_poly right.

**Comment by tthsqe12** [comment]
Hm. Maybe I could get away with it. This "small amount of helper functions" is exactly what I was proposing. I will see if it can be done entirely in mpoly. If it does work, the problem is of course what to call what I am currently calling nmod_polydr_t.

**Comment by tthsqe12** [comment]
@wbhart Are you saying that nmod_poly was invented before nmod_t? I find that hard to believe.
Also, I looked into how nmod_poly's are being used in nemo https://github.com/Nemocas/Nemo.jl/blob/master/src/flint/FlintTypes.jl#L448 and I have tonnes of questions.
First, the julia struct does not match the flint struct because the mod struct is flattened out in julia. There is now no hope of the mod member matching, which I assume is ok because you don't reference it. Are you using the coeffs, alloc, and length members directly from julia? I hope not because this is an undefined pointer cast - when you do such a cast apparently only the first member is valid (i.e. coeffs). How do you ensure that julia reserves enough space in its struct so that flint is not possibly overwriting the parent member of the julia struct?

**Comment by thofma** [comment]
The julia struct minus the parent has the same size as an nmod_poly on the C side. Flint cannot overwrite the parent member (unless it is doing something illegal).

**Comment by tthsqe12** [comment]
How is this possible since julia doesn't know the size of the C struct?

**Comment by wbhart** [comment]
It's unlikely we will change the interface of nmod_poly_t. It would simply break too much code.

However, the other issues I have opened tickets for separately. So this issue can be closed, as tickets should have one issue each and should be specific in what should be implemented/fixed.
