### ISSUE TITLE
Dependency (.d) files missing with GNU Make 3.80

### ISSUE THREAD

**Issue by wbhart** [wbhart/flint2#55]
I am on a Mac OS X 10.4 PPC machine, using GNU make 3.80.  The basic problem is that in compiling some library extensions in Sage involving mwrank, compilation fails with

/usr/bin/ld: Undefined symbols:
_nmod_mat_clear referenced from libec expected to be defined in libflint.dylib
_nmod_mat_init referenced from libec expected to be defined in libflint.dylib
_nmod_mat_rref referenced from libec expected to be defined in libflint.dylib
collect2: error: ld returned 1 exit status
error: command 'g++' failed with exit status 1

and then when we inspect Flint's package build, it turns out there are mysterious 

../Makefile.subdirs:41: no file name for `-include'

which Bill Hart already has pointed out.  All self-tests pass ('SAGE_CHECK=yes') so it's really just this issue of the linker not having the right symbols to link with because of these missing things earlier in compiling.

-include $(patsubst %, %.d, $(PROFS)) 

is the line in question, but other lines like this cause no problems, and it's only a few times that this particular line hiccups - lots of the .d files are produced and (presumably) included. (?)

See https://groups.google.com/forum/#!topic/sage-release/6Vh55hF7UXk for more details, and http://boxen.math.washington.edu/home/kcrisman/ for the Makefile, Makefile.subdirs, and log of flint 2.4.1.p0 within Sage.

**Comment by wbhart** [comment]
I take it the original problem itself is gone in 2.4.3, since it was concluded that setting the LIBNAME was the culprit.

However, that leaves the problem with

-include $(patsubst %, %.d, $(PROFS))

when there is no profile directory or no profile files in the directory.

I don't have a clue how to fix this. You can't conditionally put lines in a Makefile. This seems like a bug in the implementation of the -include directive to me. Someone with more expertise than me will have to look into this one.

**Comment by kiwifb** [comment]
Resurrecting old threads, I will have to look that one again.

**Comment by wbhart** [comment]
gnu make allows empty filename list, so I think this is just a bug in an old version of make. We require gmake anyway. So I am going to close this issue. It really can't be fixed.
