### ISSUE TITLE
x86-specific profiling code causes ARM builds to fail.

### ISSUE THREAD

**Issue by cngkaygusuz** [wbhart/flint2#565]
I am cross-compiling FLINT on OSX Mojave (10.14) for WatchOS 5.2. The function `get_cycle_counter` defined in `flint2/profiler.h` on line 113 contains x86-specific assembly code for builds that does not define `_MSC_VER`. This assembly code makes cross-compilation fail, fortunately simply removing the assembly code and returning a dummy value from the function clears the issue, and the library can be compiled and used without any problems.

Even though there is a workaround, this issue made me lose a couple of hours. The library itself should handle this situation without any problems.

**Comment by wbhart** [comment]
We should investigate this. I don't think profiler.h should be compiled into the library. It was certainly never intended to be.

**Comment by wbhart** [comment]
We should investigate this. I don't think profiler.h should be compiled into the library. It was certainly never intended to be.

**Comment by wbhart** [comment]
We should investigate this. I don't think profiler.h should be compiled into the library. It was certainly never intended to be.

**Comment by fredrik-johansson** [comment]
> We should investigate this. I don't think profiler.h should be compiled into the library. It was certainly never intended to be.

I do use Flint's profiling functions in Arb.

**Comment by wbhart** [comment]
In the library itself?

**Comment by fredrik-johansson** [comment]
In example programs and profiling programs. There is also at least one occurrence in the library itself. Anyway, breaking the example programs would be bad enough.

**Comment by wbhart** [comment]
I guess we should just fix this then. But the profiler was never really meant to be used in the library. It's hard to maintain stuff like this across platforms.

By the way, the parallel code does not work on ARM. Hopefully we put guards around all of it so it is not compiled there. ARM violates the sequence rules and can't support parallelism in the way that we do it.

**Comment by tthsqe12** [comment]
@cngkaygusuz Are you saying that you did get the library to build on ARM and the test code passes? @wbhart 's last comment here is not quite accurate: The threaded functions that should work on ARM have no preprocessor guards, and the functions that should be broken on ARM have such guards. It would be interesting to remove such guards and see that the code is in fact broken. The fact that they are broken is not a fault of the ARM processor but a fault of the language flint it written in. We would need something like the c++ std::atomic.

**Comment by cngkaygusuz** [comment]
@tthsqe12 let me begin by saying I am not a flint user. I merely received the code that is written in C that happens to use flint and cross-compiled it for ARM. Since we are cross-compiling, I don't think any tests were run at least on ARM: some libraries run tests as part of the compilation procedure, since I am compiling on an x86 machine for ARM, this should not be the case.

The code I received does not seem to be parallelized, as only one core was used (there are two cores on the device) while I was profiling the application that the library was used, hence I cannot comment on how it behaves in threaded scenarios. 

In addition, I am not working on that project anymore; however, I shall let my colleagues know about this potential pitfall and urge them to report any discovered issues here.

**Comment by wbhart** [comment]
The original issue reported here is now fixed in trunk.

The parallel code is simply excluded from the build on ARM at present. The library should still build, it is just that those functions will not be available. This is likely to be the case for quite some time. But in the mean time, you should be able to get some work done with Flint.

Lifting the restriction on a parallel build for ARM would probably mean working with someone in the community who was serious about using ARM for high performance computations.
