### ISSUE TITLE
Aliasing in fmpz_poly_divrem seems suspicious

### ISSUE THREAD

**Issue by tthsqe12** [wbhart/flint2#575]
When Q and A are aliased in fmpz_poly_divrem, the call _fmpz_poly_set_length(Q, ...) can have poly->length greater than poly->alloc and I am getting crashes that I am fairly sure are not my fault. Is it bad to have poly->length bigger than poly->alloc in _fmpz_poly_set_length? I feel I am not qualified to fix this because I am not sure what _fmpz_poly_set_length is supposed to do.

**Comment by wbhart** [comment]
Yeah, you should never have poly->length > poly->alloc. Can you give me an example of a set of calls that would result in this behaviour and I'll take a look.
