### ISSUE TITLE
fq_zech_ctx_randtest can choose a non primitive polynomial

### ISSUE THREAD

**Issue by erou** [wbhart/flint2#583]
I was discussing with @defeo why #351 fails on Travis and he suggested this.    

The function `fq_zech_ctx_randtest` calls `fq_nmod_ctx_init`. If a Conway polynomial is available, it will be chosen to define the finite field, otherwise a random irreducible polynomial will be chosen using `nmod_poly_randtest_sparse_irreducible`.

That polynomial may not be primitive and if it is not, then Flint will abort when calling `fq_zech_ctx_init_fq_nmod_ctx`. 

The function `fq_zech_ctx_init_random` always picks a primitive polynomial. So `fq_zech_ctx_randtest` could call `fq_zech_ctx_init_random`, or the tests could call `fq_zech_ctx_init_random` instead of `fq_zech_ctx_randtest`.

How would you prefer to address the problem? 

(Please tell me if opening a new issue was not the appropriate way of discussing the problem.)

**Comment by wbhart** [comment]
An issue is a very appropriate way of addressing the problem.

Either of the proposed solutions seems fine to me, so long as the test times are kept down to a second or two whilst still doing some meaningful random testing. 

As this issue only seems to affect testing, then it is not so important. So whichever way works for you, just go with it, I would say.
