### ISSUE TITLE
Unused code in nmod_mat/lu_recursive.c

### ISSUE THREAD

**Issue by krisk0** [wbhart/flint2#59]
As of ver 2.4.3 subroutine nmod_mat_lu_recursive() contains unused var A1, and code to initialize and clear it

I suggest removing A1 var definition and three lines accessing the var:

66c66
<     nmod_mat_t A0, A1, A00, A01, A10, A11;
---
>     nmod_mat_t A0, A00, A01, A10, A11;
85d84
<     nmod_mat_window_init(A1, A, 0, n1, m, n);
93d91
<         nmod_mat_window_clear(A1);
144d141
<     nmod_mat_window_clear(A1);

**Comment by wbhart** [comment]
Fixed in trunk.
