### ISSUE TITLE
Implement *_mpoly_resultant_ducos

### ISSUE THREAD

**Issue by wbhart** [wbhart/flint2#596]
@tthsqe12 will no doubt be interested in this one.

**Comment by tthsqe12** [comment]
ducos is here https://github.com/wbhart/flint2/blob/trunk/fmpz_mpoly/univar.c#L1011
It doesn't seem productive to write 5 more versions (nmod_, fmpz_mod_, fq_nmod_, fq_zech_, fq_) of this function when the algorithm is _completely_ generic - the worst that is needs is divexact.
I would like to get rid of this function and the equally useless fmpz_mpoly_gcd_prs.
How about
   (1) deciding on an interface for pulling a variable out (sparse univar over sparse multivariate), and
   (2) comparing the ducos in nemo and flint and making sure the memory management in the former is not atrocious.
?

**Comment by tthsqe12** [comment]
The commit that removed resultant and discriminant are here
https://github.com/wbhart/flint2/commit/967cadc93df543fd882c854f7753ac8831c79d5f
I believe these should be done generically.

**Comment by wbhart** [comment]
We could do this in Nemo. The only problem with that is the very long compile time for that in Nemo. For gcd_prs it is 3 seconds before you can run the gcd.

Of course, the version of Ducos that is there is only for iterated univariates, I think. PRS is implemented for actual multivariates.

**Comment by tthsqe12** [comment]
Here is what I am talking about specifically.
I could only find in the generic ducos in this section https://github.com/Nemocas/AbstractAlgebra.jl/blob/master/src/generic/Poly.jl#L1679
This means that it is only implemented for dense univariates. One would have to translate the above sparse univariate code in flint to the SparsePoly module and provide c functions that pull out a variable from the mpoly's and produce a SparsePoly over mpoly's the remaining variables.
