### ISSUE TITLE
fmpz_nextprime/randprime broken

### ISSUE THREAD

**Issue by wbhart** [wbhart/flint2#597]
These were broken (deals incorrectly, internally, with the region around where we switch from small to large integers), but I don't recall if I already fixed it and don't see an open or closed ticket for it.

**Comment by fredrik-johansson** [comment]
Seems like you fixed this in 662e7ddec39564562e46fd7c3371b12eb7c40c5a

**Comment by wbhart** [comment]
Fixed in trunk.
