### ISSUE TITLE
cl build broken after fixing MPFR deprecation warning

### ISSUE THREAD

**Issue by wbhart** [wbhart/flint2#598]
Appveyor reports:

number_of_partitions_mpfr.c.obj : error LNK2001: unresolved external symbol mpfr_rootn_ui
bin\flint.dll : fatal error LNK1120: 1 unresolved externals

I think this is because we are using Brian Gladman's repo on Windows (not totally sure if this is the issue). I have written to Brian to clarify.

**Comment by isuruf** [comment]
Updating the line in https://github.com/wbhart/flint2/blob/trunk/appveyor.yml#L49 to `mpfr=4.*` should fix it

**Comment by wbhart** [comment]
Thanks. We think this shouldn't be relevant (unless the version in Conda is really, really ancient). But I updated it anyway.

**Comment by isuruf** [comment]
Issue was that the version in conda was using Brian's repo, but the version 3.1.5 was a commit I used from Brian's repo with the version at 4.0.0.dev. It was functionally equivalent to 3.1.5, but `MPFR_VERSION_MAJOR` was wrong.
In 4.x series, we are using `mpfr.org` sources with Brian's vc14 build system, so the version mismatch shouldn't occur.

**Comment by wbhart** [comment]
Ah, thanks.

**Comment by wbhart** [comment]
Seems to be fixed.
