### ISSUE TITLE
polynomial evaluation seems problematic

### ISSUE THREAD

**Issue by zhaoli-IHEP** [wbhart/flint2#601]
I am not sure if this is a bug or my mistake on the function implementation.
```
flint::fmpz_polyxx the_poly( "3  1 2 -1" );
auto eval_poly = flint::evaluate( the_poly, flint::fmpzxx(2) );

cout << endl << endl;
print_pretty( the_poly, "x" );
cout << endl << eval_poly << endl;
```
This gives the result
```
-x^2+2*x+1
-4207975614325919
```
Or isn't the evaluation function the operation x=2?

**Comment by wbhart** [comment]
Does it always give the same answer? I think it may be printing the pointer to eval_poly and not its value. But I am not sure.

What is the type of eval_poly?

**Comment by zhaoli-IHEP** [comment]
> Does it always give the same answer? I think it may be printing the pointer to eval_poly and not its value. But I am not sure.
> 
> What is the type of eval_poly?

Thank you for reminding me of this.
It should be converted to fmpzxx as follows
```
flint::fmpzxx eval_poly = flint::evaluate( the_poly, flint::fmpzxx(2) ).to<flint::fmpzxx>();
```
Then it gives the correct answer.

**Comment by tthsqe12** [comment]
I could not reproduce this on my machine. It works fine with the auto. By the way the type of the auto is
```
flint::mp::enable_if_v<true, flint::fmpzxx_expression<flint::operations::evaluate_op, flint::tuple<const flint::fmpz_polyxx_expression<flint::operations::immediate, flint::detail::fmpz_poly_data>&, flint::tuple<const flint::fmpzxx_expression<flint::operations::immediate, flint::detail::fmpz_data>&, flint::empty_tuple> > > >::type {aka flint::fmpzxx_expression<flint::operations::evaluate_op, flint::tuple<const flint::fmpz_polyxx_expression<flint::operations::immediate, flint::detail::fmpz_poly_data>&, flint::tuple<const flint::fmpzxx_expression<flint::operations::immediate, flint::detail::fmpz_data>&, flint::empty_tuple> > >}```
