### ISSUE TITLE
Problem on nmod_polyxx init

### ISSUE THREAD

**Issue by zhaoli-IHEP** [wbhart/flint2#606]
Here is the example code
```
flint::nmod_polyxx ppp = flint::nmod_polyxx( ("3 14638944639719  -12 18 12") );
print( ppp );
```
I thought it would reduce -12 mod  14638944639719. However, the result gives
```
3 14638944639719  18446744073709551604 18 12
```
Then this 14638944639719 really confused me.
Do I have some misunderstanding here?

**Comment by wbhart** [comment]
The function uses nmod_poly_set_str to read the input. This assumes that the string is exactly as it would be printed from a valid nmod_poly (see nmod_poly_print).

Unfortunately, Flint does not have better reading and writing capabilities than this at present.

If you want to use Flint in a more convenient form, you might consider using the Julia package Nemo.jl.

**Comment by zhaoli-IHEP** [comment]
> The function uses nmod_poly_set_str to read the input. This assumes that the string is exactly as it would be printed from a valid nmod_poly (see nmod_poly_print).
> 
> Unfortunately, Flint does not have better reading and writing capabilities than this at present.
> 
> If you want to use Flint in a more convenient form, you might consider using the Julia package Nemo.jl.

Thank you for the explanation.
