### ISSUE TITLE
malloc -> flint_malloc

### ISSUE THREAD

**Issue by wbhart** [wbhart/flint2#619]
@tthsqe12 Another one for the next PR when you get back to it:

fmpz_mpoly/divides_heap_threaded.c:        L = (divides_heap_chunk_struct *) malloc(sizeof(divides_heap_chunk_struct));
fmpz_mpoly/mpolyu_divides_threaded.c:        L = (divides_heap_chunk_struct *) malloc(sizeof(divides_heap_chunk_struct));
nmod_mpoly/divides_heap_threaded.c:        L = (divides_heap_chunk_struct *) malloc(
nmod_mpoly/mpolyn_divides_threaded.c:        L = (divides_heap_chunk_struct *) malloc(sizeof(divides_heap_chunk_struct));

**Comment by tthsqe12** [comment]
ok

**Comment by wbhart** [comment]
Fixed in trunk by tthsqe12
