### ISSUE TITLE
make install with extensions fails

### ISSUE THREAD

**Issue by fredrik-johansson** [wbhart/flint2#62]
I get an error running "make install" with extensions:

/bin/sh: 1: [: /home/fredrik/src/arb/bernoulli.h: unexpected operator

with the shell changed to /bin/bash:

/bin/bash: line 0: [: too many arguments

The problem appears to be this:

$(AT)if [ ! -z $(EXT_HEADERS) ]; then \
	cp $(EXT_HEADERS) $(DESTDIR)$(PREFIX)/include/flint; \
fi

It works if one removes the first and third lines.

**Comment by nexttime** [comment]
> As far as I remember BASH specification, construct [ -z smth ] and [ ! -z smth ] is illegal if smth is a string with spaces. Such problems are usually fixed with double-quotes ". I am however unsure how bash evaluates string like $(EXT_HEADERS) because according to man page of bash, $(smth) means run command smth and take its stdout.

`$(EXT_HEADERS)`  is expanded by `make`, not the shell.

The shell (whether bash or some other shell) doesn't care either; `[` is an alias for `test`, an external program.  To be on the safe side, in `[ -z $var ]` the variable should **always** be quoted.

In Sage, currently the following patch gets applied:
```diff
commit 81c820b73dc0208f107629d7658f4f0642ca64e8
Author: Jean-Pierre Flori <jean-pierre.flori@ssi.gouv.fr>
Date:   Mon Feb 3 15:02:22 2014 +0100

    Fix test for empty string in install target.

diff --git a/Makefile.in b/Makefile.in
index 0fa717b..19caed2 100644
--- a/Makefile.in
+++ b/Makefile.in
@@ -178,7 +178,7 @@ install: library
 		cp libflint.a $(DESTDIR)$(PREFIX)/lib; \
 	fi
 	cp $(HEADERS) $(DESTDIR)$(PREFIX)/include/flint
-	$(AT)if [ ! -z $(EXT_HEADERS) ]; then \
+	$(AT)if [ ! -z "$(EXT_HEADERS)" ]; then \
 		cp $(EXT_HEADERS) $(DESTDIR)$(PREFIX)/include/flint; \
 	fi
 	mkdir -p $(DESTDIR)$(FLINT_CPIMPORT_DIR)
```

**Comment by krisk0** [comment]
In my humble opinion this patch is useless because either make variable EXT_HEADERS is evil and cp $(EXT_HEADERS) ... will fail, or EXT_HEADERS is good and everything is fine, with or without patch

**Comment by wbhart** [comment]
This patch has now been applied in the repository and will make it into flint-2.5.
