### ISSUE TITLE
About how to release std::map<std::pair<int,int>,flint::fmpq_polyxx>

### ISSUE THREAD

**Issue by zhaoli-IHEP** [wbhart/flint2#620]
In our work we prepared two functions, which give same result. However, the memory occupation is very different. The obvious difference between these two functions is that one of the function has a very bit std::map<std::pair<int,int>,flint::fmpq_polyxx> for local use. In my understanding the local std::map should be released after the function is finished. However, we found later calculation does not use this extra (should have been released) memory. Therefore, we were wondering if we need to destroy each flint::fmpq_polyxx manually using some function, or it is enough to just clear the map.

**Comment by wbhart** [comment]
I don't know, as I am not a C++ expert, but I think everything should be "automatic" using destructors.

Unfortunately, no one is currently maintaining the C++ wrapper, so I don't know if someone else has information on this.

**Comment by tthsqe12** [comment]
@zhaoli-IHEP  The destructors are called when the object goes out of scope, and the std::map will destroy all of its keys and values before it destroys itself. In this example
```
    {
        std::map<std::pair<int,int>,flint::fmpq_polyxx> m;

        m[std::pair<int,int>(2,1)] = flint::fmpq_polyxx( "3  1 2 3" );
        m[std::pair<int,int>(1,1)] = flint::fmpq_polyxx( "3  4 5 6" );
        m[std::pair<int,int>(0,2)] = flint::fmpq_polyxx( "3  7 8 9" );

        for (auto it = m.begin(); it != m.end(); ++it)
        {
            std::cout << "<" << it->first.first << "," << it->first.second << ">: ";
            flint::print_pretty(it->second, "x");
            std::cout << std::endl;
        }
    }
```
, I have put print statements in `fmpq_poly_init` and `fmpz_poly_clear` so you can see that indeed all memory management is done for you:
```
fmpq_poly_init called
fmpq_poly_init called
fmpq_poly_clear called
fmpq_poly_init called
fmpq_poly_init called
fmpq_poly_clear called
fmpq_poly_init called
fmpq_poly_init called
fmpq_poly_clear called
<0,2>: 9*x^2+8*x+7
<1,1>: 6*x^2+5*x+4
<2,1>: 3*x^2+2*x+1
fmpq_poly_clear called
fmpq_poly_clear called
fmpq_poly_clear called
```

**Comment by zhaoli-IHEP** [comment]
> @zhaoli-IHEP The destructors are called when the object goes out of scope, and the std::map will destroy all of its keys and values before it destroys itself. In this example
> 
> ```
>     {
>         std::map<std::pair<int,int>,flint::fmpq_polyxx> m;
> 
>         m[std::pair<int,int>(2,1)] = flint::fmpq_polyxx( "3  1 2 3" );
>         m[std::pair<int,int>(1,1)] = flint::fmpq_polyxx( "3  4 5 6" );
>         m[std::pair<int,int>(0,2)] = flint::fmpq_polyxx( "3  7 8 9" );
> 
>         for (auto it = m.begin(); it != m.end(); ++it)
>         {
>             std::cout << "<" << it->first.first << "," << it->first.second << ">: ";
>             flint::print_pretty(it->second, "x");
>             std::cout << std::endl;
>         }
>     }
> ```
> 
> , I have put print statements in `fmpq_poly_init` and `fmpq_poly_clear` so you can see that indeed all memory management is done for you:
> 
> ```
> fmpq_poly_init called
> fmpq_poly_init called
> fmpq_poly_clear called
> fmpq_poly_init called
> fmpq_poly_init called
> fmpq_poly_clear called
> fmpq_poly_init called
> fmpq_poly_init called
> fmpq_poly_clear called
> <0,2>: 9*x^2+8*x+7
> <1,1>: 6*x^2+5*x+4
> <2,1>: 3*x^2+2*x+1
> fmpq_poly_clear called
> fmpq_poly_clear called
> fmpq_poly_clear called
> ```

Thank you for the reply. I also found this by triggering the double free error. 
However, it is really confusing that the freed memory was not fully recycled in the later calculation. 
But I guess it is related to how C++ and OS work on the memory.

**Comment by wbhart** [comment]
The integer coefficients of fmpq_poly's are recycled in a cache. If this is not what you want, you can configure Flint with the --reentrant option. But it will be about 20% slower for many operations.

**Comment by zhaoli-IHEP** [comment]
> The integer coefficients of fmpq_poly's are recycled in a cache. If this is not what you want, you can configure Flint with the --reentrant option. But it will be about 20% slower for many operations.

Thank you. We have figured out another ugly approach to avoid this. Project has been saved with a little bit of timing comprise. But we will keep in mind the --reentrant option.
