### ISSUE TITLE
fmpz_zero() assigns zero twice

### ISSUE THREAD

**Issue by krisk0** [wbhart/flint2#64]
fmpz_zero() when called with a big number assigns zero twice: once in _fmpz_demote() and once by itself.

I offer a patch, to fix the problem (can't sleep at night when my program works slower than it could)
```
--- fmpz.h      2014-04-01 03:48:29.000000000 +0400
+++ fmpz-m.h    2014-04-17 18:36:53.312158379 +0400
@@ -270,8 +270,9 @@
 static __inline__
 void fmpz_zero(fmpz_t f)
 {
-   _fmpz_demote(f);
+   if (COEFF_IS_MPZ(*f)) 
+       _fmpz_clear_mpz(*f);
 }
```

**Comment by wbhart** [comment]
Merged.
