### ISSUE TITLE
fmpz_factor_smooth and fmpz_factor_trial fails on 32 bits

### ISSUE THREAD

**Issue by wbhart** [wbhart/flint2#646]
factor_trial....
This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
ERROR: number of factors do not agree
n = 1838265625
factor_trial computed factors: 1838265625
factor_trial_range computed factors: 5^6 * 7^6

1198/1923 Test #1197: fmpz_factor-test-t-factor_smooth ......................................***Failed    3.33 sec
factor_smooth....
This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
ERROR: factor is not prime!
input: 304888344611713860501504000000
computed factors: 2^25 * 3^13 * 11^2 * 13^2 * 23 * 12117546875

**Comment by wbhart** [comment]
The bug is almost certainly in the code in flint_mpn_factor_trial_tree that depends on FLINT_BITS.

**Comment by tthsqe12** [comment]
factor trial tree has some problems.
https://travis-ci.org/github/thofma/Flint2Builder/builds/669713630

**Comment by thofma** [comment]
Here is the error:
```
    CC   ../build/mpn_extras/factor_trial_tree.lo
factor_trial_tree.c: In function '_tree_mutex_init':
factor_trial_tree.c:32:25: error: 'factor_trial_lock' undeclared (first use in this function)
     pthread_mutex_init(&factor_trial_lock, NULL);
                         ^
factor_trial_tree.c:32:25: note: each undeclared identifier is reported only once for each function it appears in
make[2]: *** [../Makefile.subdirs:67: ../build/mpn_extras/factor_trial_tree.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/workspace/srcdir/flint2/mpn_extras'
make[1]: *** [Makefile:143: libflint-13.dll] Error 2
make[1]: Leaving directory '/workspace/srcdir/flint2'
make: *** [Makefile:174: library] Error 2
ERROR: LoadError: Build for libflint on x86_64-w64-mingw32 did not complete successfully
```

**Comment by wbhart** [comment]
Fixed in trunk.
