### ISSUE TITLE
fmpz_poly-test-t-taylor_shift_divconquer segfault

### ISSUE THREAD

**Issue by wbhart** [wbhart/flint2#649]
On 64 bit GCC with CMake. It seems to pass on Linux, so valgrind would be the first port of call.

**Comment by tthsqe12** [comment]
I would be surprised if this was not the same issue as https://github.com/wbhart/flint2/issues/648

**Comment by wbhart** [comment]
I am working on this.

**Comment by wbhart** [comment]
Fixed in trunk.
