### ISSUE TITLE
Document fmpq_poly_get_numerator

### ISSUE THREAD

**Issue by wbhart** [wbhart/flint2#656]
Function was requested by Winfried Bruns, who did not find it.

**Comment by thofma** [comment]
Is there are problem with `fmpq_poly_get_numerator`?

**Comment by wbhart** [comment]
Yes, according to the documentation there is no such function. Thus Winfried did not find it.

So let's change the ticket to "document...."

**Comment by wbhart** [comment]
Fixed by deinst.
