### ISSUE TITLE
Changes needed for Arb dll

### ISSUE THREAD

**Issue by wbhart** [wbhart/flint2#658]
Brian Gladman has produced the following list of changes needed to build Arb as a dll using visual studio.

FLINT changes needed to build ARB as a DLL

1. In file artih.h, add between line 221 and 222:

```
FLINT_DLL const unsigned int partitions_lookup[128];
```

2. In file flint.h, add export definition on line 177:

```
FLINT_DLL int flint_test_multiplier(void);
```

3. in file longlong.h, add a guard around line 326:

```
#ifndef NEED_CLZ_TAB
#  define NEED_CLZ_TAB
#endif
```

**Comment by wbhart** [comment]
Fixed in trunk.

**Comment by wbhart** [comment]
The CMAKE CI fails with these changes. I've reverted the first change which seems to be the most suspicious for now.

**Comment by isuruf** [comment]
I think https://github.com/wbhart/flint2/pull/665 will fix it

**Comment by isuruf** [comment]
Nvm, that's a different error

**Comment by isuruf** [comment]
For the partitions lookup symbol error, `partitions_lookup` should be declared as an `extern`.

**Comment by wbhart** [comment]
Seems fixed.
