### ISSUE TITLE
'gm: command not found' in fq_embed with gmake on MinGW64

### ISSUE THREAD

**Issue by gvanuxem** [wbhart/flint2#659]
Using gmake the build process stops in fq_embed directory with the error message:
'gm: command not found'.

If I re-switch to GNU Make directly (without a reconfigure and make) the problem no longer happens.

**Comment by gvanuxem** [comment]
Ok, I looked a little deeper at this yesterday and that seems related to GNU Make.

The gmake used yesterday was in fact GNU Make 4.2.1 from the Strawberry Team. I tried also this version renamed as gmake and I encountered different errors too.

The GNU Make that I use usually is the 4.3 version from MSYS2. It works nicely named make or gmake.

So I'm doubtful. May be one day someone will hit this again and will be able to check a little more. Moreover on a different configuration.

**Comment by wbhart** [comment]
Ok, thanks for the feedback. Either way it seems to not be a Flint issue, but an issue with make. So I will close this issue here.

If you find some information that suggests we are doing something wrong, you can reopen the ticket. We are not able to replicate the problem ourselves, at least.
