### ISSUE TITLE
Buggy fmpz_powm

### ISSUE THREAD

**Issue by tthsqe12** [wbhart/flint2#660]
One is led to believe negative exponents work because the docs say nothing about negative exponents, but they do not work. Mpz_powm says it tries negative exponents and throws if something goes wrong. Anyways, the following behaviour was an unpleasant surprised - caused by a bad slong->ulong cast - when I was trying to clean up fmpz_mod_pow_fmpz. 2^-1 mod 10 = 2^(2^64-1) mod 10 = 8 with no errors. Ultimately fmpz_mod_pow_fmpz will return an int and never throw. I just would like to know what fmpz_powm is supposed to do.

**Comment by wbhart** [comment]
It should be as per https://gmplib.org/manual/Integer-Exponentiation.html

If you find a case that doesn't follow that, then please add it to the report and we'll fix it.

**Comment by tthsqe12** [comment]
2 is not invertible mod 10. It should throw. It does not as I explained above.

**Comment by wbhart** [comment]
Ok, I wasn't clear if that was powm or mod_pow_fmpz. But agreed, that should throw.

**Comment by tthsqe12** [comment]
I am working on this.

**Comment by tthsqe12** [comment]
fixed by #664
