### ISSUE TITLE
fq_nmod_mpoly t-divrem_ideal_monagan_pearce aborts on ppc64le

### ISSUE THREAD

**Issue by isuruf** [wbhart/flint2#669]
```
add/sub....add/sub_fq_nmod....PASS

cmp....PASS

compose_fq_nmod_mpoly....PASS

compose_fq_nmod_poly....PASS

degree....PASS

derivative....PASS

div_monagan_pearce....PASS

divrem_ideal_monagan_pearce....Flint exception (General error):

make[1]: *** [../Makefile.subdirs:91: ../build/fq_nmod_mpoly/test/t-divrem_ideal_monagan_pearce_RUN] Aborted (core dumped)

make[1]: *** Waiting for unfinished jobs....

    Polynomial exponents invalidPASS
```

xref: https://travis-ci.com/github/conda-forge/libflint-feedstock/builds/161505371#L11122-L11124

**Comment by wbhart** [comment]
@tthsqe12 Any ideas? It looks like it is aborting deliberately. Is this something you anticipated?

**Comment by tthsqe12** [comment]
This is unexpected. I will try to fix it soon.

**Comment by tthsqe12** [comment]
@isuruf Do you have any hints on how I can reproduce this?

**Comment by isuruf** [comment]
Do you have access to a power8 or power9 machine? If not, I can give you temporary access.

**Comment by tthsqe12** [comment]
I have no such access.

**Comment by isuruf** [comment]
Can you send your public SSH key to `isuruf@gmail.com` ? I can give you access and instructions on how to reproduce.
