### ISSUE TITLE
qlimbs incorrect in gcd_heuristic

### ISSUE THREAD

**Issue by wbhart** [wbhart/flint2#695]
@jamesjer reported in PR #694 that an array is overrun sometimes in gcd_heuristic. It's possibly the -1 on the prior line that is erroneous, but this should be carefully checked against the algorithm.

**Comment by tthsqe12** [comment]
Possibly related
https://github.com/wbhart/flint2/issues/402

**Comment by wbhart** [comment]
Ah yeah, it could well be that. This is harmless. But I will check thoroughly to make sure.

**Comment by wbhart** [comment]
I think it is #402. I'm going to close this as not a bug.
