### ISSUE TITLE
Support GMP 6.2

### ISSUE THREAD

**Issue by wbhart** [wbhart/flint2#700]
Many of the items in gmpcompat assume that _mp_d has been allocated with at least one limb. This is not the case in the new version of GMP.

We also need to go through all direct accesses of _mp_d in Flint and check the new restrictions are not violated.

**Comment by tthsqe12** [comment]
Has convicing the gmp folks that a ui on win64 is 64 bits been tried? This has got to be rather trivial mistake to fix.

**Comment by tthsqe12** [comment]
Did you test this on a relevant setup?

**Comment by wbhart** [comment]
No I haven't. But I'm issuing an alpha now, so we'll soon know if it is broken. :-)

**Comment by tthsqe12** [comment]
@wbhart The code added in flint_mpf_set_ui/si is clearly in error. With these two pieces removed, the library compiles and the test code passes.
