### ISSUE TITLE
Put up new sphinx documentation

### ISSUE THREAD

**Issue by wbhart** [wbhart/flint2#703]
It has been proofread and corrected.

**Comment by fredrik-johansson** [comment]
Should we change the website to point to the new Sphinx documentation directly, like http://arblib.org/ ? It would simplify keeping the website up to date.

**Comment by wbhart** [comment]
I don't think that is a good idea. We have info in the website which is not in the docs.

**Comment by fredrik-johansson** [comment]
Sure, but it's easy to move to the docs, and then everything is in one place.

**Comment by wbhart** [comment]
What do you mean?

**Comment by fredrik-johansson** [comment]
By "info in the website which is not in the docs", I presume that you mean things like "Links and references", "Authors and credits" and "Downloads". For Arb I just put all such info in the documentation.

**Comment by wbhart** [comment]
If you are willing to do that, yes. We also don't have the C++ interface in the docs I think, and the install and configure information.

**Comment by wbhart** [comment]
Done
