### ISSUE TITLE
Zassenhaus pruning

### ISSUE THREAD

**Issue by wbhart** [wbhart/flint2#709]
NTL uses a variety of pruning tricks for Zassenhaus. They get a crossover with van Hoeij of 40 or 50 local factors. We don't need to improve that much, but we can do much better.

**Comment by tthsqe12** [comment]
Some naive pruning was added in https://github.com/wbhart/flint2/commit/8d62059cc73e3bcf0939b741502a686d63c1f9e2
Should be good enough in combination with power hacks (which have not been added yet).
