### ISSUE TITLE
Valgrind some modules

### ISSUE THREAD

**Issue by wbhart** [wbhart/flint2#726]
@jamesjer reported some issues after running -fsanitise=address. We should valgrind the modules in his PR and fix the issues.

Also the _f functions in the fmpz_mod_poly module leak, but are not tested.

Note reports of SSE overruns in GMP are harmless. They are within spec.

**Comment by wbhart** [comment]
We should also valgrind all new modules: the mpoly stuff and fmpz_mod_mat, aprcl and also valgrind nmod_poly, nmod_poly_factor, fmpz_mod_poly, fmpz_mod_poly_factor due to all the work on the factorisation code.

Various other modules could be valgrinded. Add suggestions here.

**Comment by tthsqe12** [comment]
Don't let me forget to avoid parallel division unless `FLINT_KNOW_STRONG_ORDER` is true.
This was initially done but forgotten latter.

**Comment by wbhart** [comment]
Not really necessary now that James Jer's patch has been merged. I assume no leaks.

**Comment by tthsqe12** [comment]
Nono, there are still big problems with the memory is various modules. Should make a list of the problems here?

**Comment by wbhart** [comment]
Ok, but how can there still be leaks. I merged all jamesjer's patches.

**Comment by tthsqe12** [comment]
The fmpz_mat_scalar_smod does invalid reads on an an empty matrix.
When the test code finishes running, I will collect all of the problems.

**Comment by wbhart** [comment]
Oh yeah, there's still his other two pull requests. Unfortunately the fixes weren't valid though. So we have to fix those.

**Comment by wbhart** [comment]
Fixed in trunk by @tthsqe12
