### ISSUE TITLE
Allow to compile against mpir (without --enable-gmpcompat in mpir)

### ISSUE THREAD

**Issue by hasufell** [wbhart/flint2#73]
Distributions usually cannot enable gmpcompat in mpir since they need both installed at the same time. Enabling gmpcompat would cause file collision and is impossible to support sanely on distribution-level. That limits the user choice here effectively to gmp.

**Comment by wbhart** [comment]
Flint now supports GMP as well as MPIR with --enable-gmpcompat, so if GMP is installed, that should be used.

I don't think there is any advantage to us complicating our build system just so people can switch between the two.
