### ISSUE TITLE
Do release announcement.

### ISSUE THREAD

**Issue by wbhart** [wbhart/flint2#730]
As the title says.

**Comment by dimpase** [comment]
Could you tag this (in git) ? This would be more convenient than the commit itself.

**Comment by wbhart** [comment]
Can I ask why? It's not the release, and I really don't want to spam up the git tags with endless alpha and beta releases.

**Comment by dimpase** [comment]
You have zero tags in your git repo. Zero. :-)

Tags are useful to mark frozen states, as opposed to branches. It helps people navigate the repo. 

If you think alphas are too often, you could tag at least betas and stable releases, hopefully.

**Comment by wbhart** [comment]
We will tag releases, but absent a compelling reason, that's all at this stage.

**Comment by dimpase** [comment]
Bill, without following flint newsgroups/mailing lists (or issues here), it's impossible to find out that you have an 2.6.0 alpha now.

**Comment by wbhart** [comment]
That is certainly intentional. I will tag a late beta as rc1, once all the "doh, I'm stupid" stuff has been sorted out by the people who have very kindly offered to test these very unstable early alphas and betas. Or, if the alpha looks really good, we'll skip betas and go straight to release candidates and tag them all.

**Comment by dimpase** [comment]
seems that something needs to be updated  for 2.6
I just wanted to make a [tarball to use for Sage ticket 29719](https://trac.sagemath.org/ticket/29719)
```
$ make dist
git archive --format tar --prefix flint-2.5.2/ flint-2.5 > ../flint-2.5.2.tar; gzip ../flint-2.5.2.tar
fatal: not a valid object name: flint-2.5
make: *** [Makefile:117: dist] Error 2
```

**Comment by wbhart** [comment]
I think if you edit your Makefile to change the line to the following, it
will work for you:

  git archive --format tar --prefix flint-2.6-alpha2/
a960857c7d8e5ea7c4d4c2958e38ec52778d85d9 > ../flint-2.6-alpha2.tar; gzip
../flint-2.6-alpha2.tar

Of course this is set up for us to make the distribution tarball once the
flint-2.6 branch exists.

Beware that the soname will not be updated between alphas, betas and the
final release. It only starts incrementing from that point on.

Bill.

**Comment by wbhart** [comment]
Done.
