### ISSUE TITLE
Factoring cubics and quartics

### ISSUE THREAD

**Issue by fredrik-johansson** [wbhart/flint2#733]
Polynomials of degree 3 and 4 could be special-cased in the fmpz_poly_factor code.

For cubics, factoring is equivalent to finding a rational root. The rational root theorem could be used in trivial cases, but not in general.

If a cubic in standard form x^3 + px + q = 0 has a rational root, then -q/2 + sqrt(D) is a perfect cube in Q[sqrt(D)] where D is the discriminant. [ https://doi.org/10.1080/0025570X.1991.11977602 ]. It might be possible to turn this into an algorithm, but right now I don't see how.

Alternatively, we could compute the real roots numerically with the cubic formula (or Newton's method) and use continued fractions to recover candidate rational roots, but this requires some error analysis and ultimately might not even be faster than the general factoring code.

In nmod_poly_factor, we could simply brute force for candidate factors of cubics and quartics when the modulus is tiny.

**Comment by tthsqe12** [comment]
For cubics with only one real root, it is easy to give the one or two rational possibilities for the real root using only integer arithetic. For cubics with three real roots it is not so clear.

**Comment by tthsqe12** [comment]
I am having trouble getting anywhere close to the claimed 50x speedup on any quadratic. It is at best 4x for me and usually 3x. As for cubics, all factor patterns are 5x faster (large coeffs) to 10x faster (small coeffs) _except the important cases of irreducible cubic and linear * irreducible qudratic_. For irredicible cubics with large coeffs, it is only 1.5x faster so this is still better. However, for linear*quadratic, the cubic formula (using fmpz_root) is 4x slower   with large coeffs at finding the root than the padic lifting currently employed.

**Comment by fredrik-johansson** [comment]
I don't know how you are benchmarking this, but did you turn off the call to factor_quadratic both in the main factor function and in factor_zassenhaus?

**Comment by tthsqe12** [comment]
Ok. The speedup ratio of the quadratic code seems to depend on the
environment. My tests are in fmpz_poly_factor/profile/p-factor_quadratic_cubic on my new branch https://github.com/tthsqe12/flint2/tree/cubic_factoring.
On my trusty old linux box it seems to be at an extreme on
factoring a 10-bit quadratic with negative discriminant, where the speedup is
1114/31 = 36x, which is a much bigger ratio than what I was getting on a
different machine and setup. My code for cubics has big problems on factoring
a (linear)*(quadratic with negative discriminant), where the _slowdown_ is
13630/1577 = 9x.

```
        bits :      10     20     40     80    160    320    640   1280
-----------------------------------------------------------------------
      (d1)^2 :      45     41     40     48     57     62     67     69
    (d1)(d1) :      64     60     59     79    107    119    121    114
       (d2+) :      41     37     33     31     36     32     28     23
       (d2-) :      31     29     27     24     27     23     20     15
      (d1)^3 :      51     54     66     84    106    111    117    143
  (d1)(d1)^2 :     111    121    143    164    196    200    221    238
(d1)(d1)(d1) :     213    242    311    383    436    453    478    561
   (d1)(d2+) :     258    321    550    944   1599   2428   4335  13630
   (d1)(d2-) :     170    193    223    258    290    268    244    230
        (d3) :     114    113    114    124    143    138    260    159
factors found: 759843
```

Disabling the specializations in factor.c and factor_zassenhaus.c:
```
        bits :      10     20     40     80    160    320    640   1280
-----------------------------------------------------------------------
      (d1)^2 :     169    161    164    173    195    187    175    165
    (d1)(d1) :    1666   1889   1900   2048   2067   1767   1335   1007
       (d2+) :    1033   1002    919    796    672    491    353    216
       (d2-) :    1114   1088   1003    832    661    465    344    189
      (d1)^3 :     235    242    263    291    354    351    327    372
  (d1)(d1)^2 :     288    314    358    417    501    514    528    557
(d1)(d1)(d1) :    3826   4232   4457   4679   4822   4093   3245   2654
   (d1)(d2+) :    2701   2939   2971   3126   3113   2612   2066   1577
   (d1)(d2-) :    2301   2481   2531   2597   2709   2219   1724   1359
        (d3) :    1733   1671   1526   1308   1178    821    558    384
factors found: 759843
```

**Comment by tthsqe12** [comment]
With https://github.com/tthsqe12/flint2/commit/f9cba65daa57952eaf88d25f3aa6221d20103b8c, it is promising that it is quick both to recognize irreducibles and to find the factors of reducibles.
```
        bits :      10     20     40     80    160    320    640   1280
-----------------------------------------------------------------------
      (d1)^2 :      45     41     41     52     58     64     65     66
    (d1)(d1) :      63     63     63     78    109    122    120    115
       (d2+) :      43     39     34     32     36     33     28     23
       (d2-) :      35     31     28     25     27     24     19     15
      (d1)^3 :      52     57     67     87    115    115    119    144
  (d1)(d1)^2 :     116    130    144    172    200    207    225    239
(d1)(d1)(d1) :     233    250    292    393    473    478    464    499
   (d1)(d2+) :     356    374    404    440    447    412    372    372
   (d1)(d2-) :     180    196    224    263    299    271    254    231
        (d3) :     143    134    123    117    100     77     60     46
```

**Comment by fredrik-johansson** [comment]
Looks great!

**Comment by tthsqe12** [comment]
@wbhart done by https://github.com/wbhart/flint2/commit/c494f07c8341d2e032d48c5361a7bf95a40a4bf3
