### ISSUE TITLE
a probable bug in gcd of polynomials over ZZ / p^k ZZ

### ISSUE THREAD

**Issue by dimpase** [wbhart/flint2#743]
On Sage, we're hitting a snag with gcd computations of polynomials over `Z/nZ`, for `n=p^k`, `p` prime
(see https://trac.sagemath.org/ticket/29719)
e.g. 
```
sage: T.<y>=Integers(3^2)[]
sage: f=y^3+y+1 # this is implemented using Flint
sage: df=f.derivative()
sage: f.gcd(df)
Flint exception (Impossible inverse):
    Cannot invert modulo 3*0
------------------------------------------------------------------------
/home/dimpase/sage-src/local/lib/python3.7/site-packages/cysignals/signals.cpython-37m-x86_64-linux-gnu.so(+0x7ccb)[0x7bcd687d6ccb]
/home/dimpase/sage-src/local/lib/python3.7/site-packages/cysignals/signals.cpython-37m-x86_64-linux-gnu.so(+0x7e98)[0x7bcd687d6e98]
/home/dimpase/sage-src/local/lib/python3.7/site-packages/cysignals/signals.cpython-37m-x86_64-linux-gnu.so(+0xa70d)[0x7bcd687d970d]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x12730)[0x7bcd6af44730]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0x10b)[0x7bcd6a9be7bb]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x121)[0x7bcd6a9a9535]
/home/dimpase/sage-src/local/lib/libflint.so.14(+0x84cfd)[0x7bcd5b868cfd]
/home/dimpase/sage-src/local/lib/libflint.so.14(flint_throw+0xe0)[0x7bcd5b868de0]
/home/dimpase/sage-src/local/lib/libflint.so.14(_nmod_poly_rem_q1+0x8f)[0x7bcd5b9e26ef]
/home/dimpase/sage-src/local/lib/libflint.so.14(_nmod_poly_rem+0x145)[0x7bcd5b9d0d85]
/home/dimpase/sage-src/local/lib/libflint.so.14(_nmod_poly_gcd_euclidean+0x60)[0x7bcd5b9b3da0]
/home/dimpase/sage-src/local/lib/libflint.so.14(nmod_poly_gcd+0x93)[0x7bcd5b9db6a3]
/home/dimpase/sage-src/local/lib/python3.7/site-packages/sage/rings/polynomial/polynomial_zmod_flint.cpython-37m-x86_64-linux-gnu.so(+0x117e4)[0x7bcce715f7e4]
...
```

It appears to be necessary to have `f` of degree `p` to trigger this, which raises a suspicion 
that it might be a Flint bug, as Sage merely delegates this to Flint. This works with Flint 2.5.2, needless to say.

**Comment by wbhart** [comment]
We'll take a look. I was unaware we even implemented gcd for polynomials mod composite moduli. But we may have added it sometime or other.

**Comment by wbhart** [comment]
Yeah, it's just using the Euclidean algorithm, which means it tries to invert 3 modulo 9. In Nemo we check whether n is prime before calling GCD and raise an exception otherwise.

Having said that, the Flint documentation doesn't exactly make this restriction clear.

**Comment by wbhart** [comment]
Anyway, it's not clear to me what is meant by a GCD modulo p^k. You have arbitrarily large units in this ring don't you?

**Comment by dimpase** [comment]
On Sat, 23 May 2020, 00:20 wbhart, <notifications@github.com> wrote:

> Anyway, it's not clear to me what is meant by a GCD modulo p^k. You have
> arbitrarily large units in this ring don't you?
>

this is a part of square-freeness test in Sage. One cares whether  f and f'
have no common factor of positive degree, that's all.
(gcd is an overkill here)

**Comment by dimpase** [comment]
It appears that Flint 2.5.2 always returns gcd=1 in such cases.
So there is a bug in Sage, it seems, that computes gcd - and always gets 1, regardless of the presense of common factors in f and f'.

**Comment by wbhart** [comment]
Again, I'm not sure what squarefreeness actually means here.

Note ```f = f*(3y+1)^3```

**Comment by dimpase** [comment]
well, that's an academic question, whether to define square-freeness so that in *every* representation of `f` there is no factor of multiplicity >1, or this is true for *some* representation of `f`.

Anyhow it's not a Flint bug, it's just Flint got more consistent. :-)
