### ISSUE TITLE
Optimise fmpz_mpoly for nvars == 1

### ISSUE THREAD

**Issue by fredrik-johansson** [wbhart/flint2#744]
Operations on small fmpz_mpolys in one variable are an order of magnitude slower than fmpz_poly operations. It should be possible to get nearly the same performance with special code paths for nvars == 1 (maybe some linear overhead can also be avoided in the present generic code).

I mainly have in mind addition, subtraction, multiplication, exact division and gcd.

(I'm making this issue because of http://fredrikj.net/calcium/fmpz_mpoly_q.html as I'd rather have multivariates fast enough for nvars == 1 instead of switching between fmpz_poly_q and fmpz_mpoly_q depending on the number of variables.)

**Comment by tthsqe12** [comment]
Is the slowdown unacceptable for large inputs, small inputs, or just all inputs?
There is not much that can be done for addition and subtraction unless there is some aliasing of the output.

**Comment by tthsqe12** [comment]
I will eventually get around to a special case for multiplication and division by monomials and  binomials.

**Comment by fredrik-johansson** [comment]
I'm mostly thinking of small input (I have not benchmarked large input).

The lack of in-place addition is one thing. Other than that, I agree that addition looks tough to improve, but perhaps just adding a special case for nvars == 1 to minimize exponent handling overhead will make a difference.

Multiplication for small input looks possible to improve though. If I'm reading the code correctly, it simply jumps into_fmpz_mpoly_mul_johnson_maxfields.  It should be a lot faster to create three fmpz arrays, insert the coefficients, and call _fmpz_poly_mul. Linear overhead is very significant here so I think it's important to read the packed exponents directly and make minimal data movements. An optimised 1D version of mul_array might work even better than _fmpz_poly_mul for the basecase.

I have not looked at division yet; the same approach of calling _fmpz_poly_div(rem) ought to work. Actually, I'm sure even _fmpz_poly_div(rem)_basecase and related functions (including _fmpz_poly_gcd) can be optimised quite a bit for small input using array versions that work entirely with slongs instead of fmpzs when possible.

**Comment by tthsqe12** [comment]
Looking at the mpoly code, I can see many sources of inefficiencies almost everywhere. With fmpz_mpoly finally nearing completion, it is clear what is needed internally. In particular, since it looks like the basics add/sub/mul will be needed internally, they will get more attention. Could you perhaps share some Ce code in which you noticed an unacceptable slowdown? This could direct me in optimizing nvars=1.

**Comment by tthsqe12** [comment]
BTW, I think a proper implementation of rational fxns must include the pseudo factored representation
`fmpq * prod_i fmpz_mpoly_i ^ fmpz_i`
I'm sure you can figure out how to add these things, and benchmark against the expanded form on a real application would be interesting.

**Comment by tthsqe12** [comment]
@fredrik-johansson do you have a test program for this issue?

**Comment by fredrik-johansson** [comment]
No, but profiling basic arithmetic and GCD with small random polynomials as input should do it.

BTW, I agree about the pseudo factored representation. How would you go about computing the factored normal form of symbolic expressions? Do rational function arithmetic using the pseudo factored representation, and do a full factorization at the end?

**Comment by tthsqe12** [comment]
This turned out to be a fool's errand. I tried something for multiplication, and that was the only thing that could be called a success. There is nothing that can be done for addition and subtraction. There is barely a noticable difference between the mpoly and poly gcd in the nvars=1 case.

**Comment by wbhart** [comment]
As we've started beta testing, I don't know if I should merge this until after the release. But timings look good.

**Comment by tthsqe12** [comment]
> As we've started beta testing, I don't know if I should merge this until after the release. But timings look good.

What? so you don't want any add any more changes?

**Comment by wbhart** [comment]
Is this part of the tuning you were discussing on Friday?

I think it is not good form to add a lot of new code after we've asked people to start beta testing.

We agreed some stuff you mentioned on Friday would be fine though.

**Comment by tthsqe12** [comment]
Nope. This is the easy part of what I was talking about. If there shall be no more changes, then I will work on other stuff. There is plenty to do elsewhere.

**Comment by wbhart** [comment]
I can certainly separate the release branch so this can be committed to trunk.

Let's focus on just the changes we agreed to on Friday (I don't remember exactly what they were).
