### ISSUE TITLE
disable-shared and install_name_tool

### ISSUE THREAD

**Issue by DanGrayson** [wbhart/flint2#746]
I think one more step has to be skipped when the --disable-share option is used on the Mac:
```
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool: can't open file: /Users/dan/src/M2/M2.git/M2/BUILD/dan/builds.tmp/gallium-development/usr-host/lib/libflint.dylib (No such file or directory)
make[1]: *** [Makefile:245: install] Error 1
make[1]: Leaving directory '/Users/dan/src/M2/M2.git/M2/BUILD/dan/builds.tmp/gallium-development/libraries/flint/build'
make: *** [../Makefile.library:134: .installed-2.6.0-rc1] Error 2
```
[LOG-flint.txt](https://github.com/wbhart/flint2/files/4682664/LOG-flint.txt)

**Comment by wbhart** [comment]
Looks like it, yeah. Thanks for the report. I'll try to adjust this for the release.

**Comment by wbhart** [comment]
Or maybe do an rc2 on Thursday.

**Comment by wbhart** [comment]
@DanGrayson is it possible that you actually did write --disable-share and not --disable-shared? The former would cause this problem.

I don't see at the moment why the latter would cause this. The relevant line in Makefile.in is in fact guarded to prevent calling it if building a shared library is disabled.

**Comment by DanGrayson** [comment]
Yes, it was `--disable-shared`.

But oops, sorry, I was using code a month old.  I've just updated and now that step works, since the line is guarded.
