### ISSUE TITLE
is_reduced_d.c:122:20: error: 'FE_DOWNWARD' undeclared (first use in this function)

### ISSUE THREAD

**Issue by SnarkBoojum** [wbhart/flint2#749]
The error message in the title only happens on the sh4 platform, for which the libc doesn't provide FE_DOWNWARD.

It's definitely not a very big problem, but still, if something easy can be done...

**Comment by wbhart** [comment]
We'll take a look. I'll mark it for 2.6, but don't be too surprised if it gets pushed back.

Thanks for the report.

**Comment by SnarkBoojum** [comment]
Oh, as I said it's minor. I just stumbled into it looking at : https://buildd.debian.org/status/package.php?p=flint&suite=sid (the x32 failure), since I uploaded a new flint package today (followup for the mips64el issue : better patch).

**Comment by wbhart** [comment]
It seems we test for fenv in configure, but this is not enough as FE_DOWNWARD is only available with C++11 compatible systems.

Perhaps @tthsqe12 can suggest a line we can add to the .h file in the configure test that will fail if FE_DOWNWARD is not available.

**Comment by wbhart** [comment]
I had a go at fixing this. According to the documentation FE_DOWNWARD is a macro, so this should be the correct fix. Feel free to reopen the issue after rc2 if it doesn't go away.

The relevant commit is 7e70bef5c

**Comment by SnarkBoojum** [comment]
Your check looks nice.
