### ISSUE TITLE
FLINT 2.6.0-rc2 Minor Cosmetic Compiler Issues On Windows

### ISSUE THREAD

**Issue by sudleyplace** [wbhart/flint2#751]
I am trying to compile this version on Win 10 using MSVC 2013 (ver. 18.00.40629).

All Minor Cosmetic Compiler Issues:

FWIW, Win10 doesn't seem to recognize alloca, but it does know about _alloca, so I put
`    /D alloca=_alloca`
on the compiler command line.

============================================================
In the file mpn_extras\factor_trial_tree.c, the function _cleanup_trial_tree needs to be declared as
`    void _cleanup_trial_tree(void)`
instead of 
`    void _cleanup_trial_tree()`
so as conform (at least as fas as MSVC is concerned) to the prototype for
`    typedef void (*flint_cleanup_function_t)(void);`

============================================================
In the file nmod_poly\compose_mod_brent_kung_vec_preinv.c the function
`    _nmod_poly_compose_mod_brent_kung_vec_preinv`
differs from its prototype in nmod_poly.h where the fifth parameter is of type
`    const mp_srcptr`
and in the prototype it is
`    mp_srcptr`
I changed the prototype in nmod_poly.h to include const.

============================================================
In the file nmod_poly\compose_mod_brent_kung.c the function
`    _nmod_poly_compose_mod_brent_kung'
differs from its prototype in nmod_poly.h where the fourth parameter is of type
`    mp_src_ptr`
and in the prototype it is
'    const mp_src_ptr`
I changed the declaration in  nmod_poly\compose_mod_brent_kung.c to include const.

============================================================
In the file qadic\ctx_init_conway.c, there is a reference to the file CPImport.h which is not contained in the 2.6.0-rc2 source code.  In previous versions, it was found in either /build.vc14/ or /qadic/.  I copied it from an old version to /qadic/ which fixed the problem.

============================================================
In the file ulong_extras\randint.c, the declaration of function n_urandint is
`    mp_limb_t n_urandint(flint_rand_t state, const mp_limb_t limit) `
but the prototype in ulong_extras.h is
`    ulong n_urandint(flint_rand_t state, ulong limit);`
Note the difference in the result and parameter 2.  I changed the prototype in ulong_extras.h to match the declaration as the declaration looks more specific.  However, now in ulong _extras.h the adjacent prototypes are all similar and different from the one I changed.  Please help -- this decision is way above my pay grade.

============================================================
For the moment, I'm compiling without thread support (HAVE_PTHREAD 0).  However, there are a lot of instances where thread support is included whether I like it or not (unresolved externals, e.g. pthread_mutex_init, ..._lock, ..._unlock, ..._destroy, ...).  I thought that defining HAVE_PTHREAD as 0 would omit those dependencies.  Is there some simple way to compile without thread support?

============================================================
With these changes, I can compile all of FLINT2 2.6.0-rc2, but linking it has thread support problems.

**Comment by wbhart** [comment]
Thanks for reporting these.

> I am trying to compile this version on Win 10 using MSVC 2013 (ver. 18.00.40629).
> 
> All Minor Cosmetic Compiler Issues:
> 
> FWIW, Win10 doesn't seem to recognize alloca, but it does know about _alloca, so I put
> ` /D alloca=_alloca`
> on the compiler command line.

This should not be necessary. That precise define is already made in flint-config.h if compiling with MSVC. Perhaps there is an issue with the flint-config.h file in @BrianGladman 's repository?

> 
> ============================================================
> In the file mpn_extras\factor_trial_tree.c, the function _cleanup_trial_tree needs to be declared as
> ` void _cleanup_trial_tree(void)`
> instead of
> ` void _cleanup_trial_tree()`
> so as conform (at least as fas as MSVC is concerned) to the prototype for
> ` typedef void (*flint_cleanup_function_t)(void);`

Fixed.

> 
> ============================================================
> In the file nmod_poly\compose_mod_brent_kung_vec_preinv.c the function
> ` _nmod_poly_compose_mod_brent_kung_vec_preinv`
> differs from its prototype in nmod_poly.h where the fifth parameter is of type
> ` const mp_srcptr`
> and in the prototype it is
> ` mp_srcptr`
> I changed the prototype in nmod_poly.h to include const.

Fixed.

> 
> ============================================================
> In the file nmod_poly\compose_mod_brent_kung.c the function
> ` _nmod_poly_compose_mod_brent_kung' differs from its prototype in nmod_poly.h where the fourth parameter is of type` mp_src_ptr` and in the prototype it is ' const mp_src_ptr`
> I changed the declaration in nmod_poly\compose_mod_brent_kung.c to include const.
> 

I was unable to find this. However, I removed some consts from other mp_srcptr's (which are already const in the way that matters) in other files.

> ============================================================
> In the file qadic\ctx_init_conway.c, there is a reference to the file CPImport.h which is not contained in the 2.6.0-rc2 source code. In previous versions, it was found in either /build.vc14/ or /qadic/. I copied it from an old version to /qadic/ which fixed the problem.

Perhaps @BrianGladman can address this one. CPImport.h has to be generated at build time from qadic/CPimport.txt.

> 
> ============================================================
> In the file ulong_extras\randint.c, the declaration of function n_urandint is
> ` mp_limb_t n_urandint(flint_rand_t state, const mp_limb_t limit)`
> but the prototype in ulong_extras.h is
> ` ulong n_urandint(flint_rand_t state, ulong limit);`
> Note the difference in the result and parameter 2. I changed the prototype in ulong_extras.h to match the declaration as the declaration looks more specific. However, now in ulong _extras.h the adjacent prototypes are all similar and different from the one I changed. Please help -- this decision is way above my pay grade.

In Flint, ulong is #defined to be mp_limb_t. So this shouldn't matter. I just changed the function to work around the apparent compiler bug.

> 
> ============================================================
> For the moment, I'm compiling without thread support (HAVE_PTHREAD 0). However, there are a lot of instances where thread support is included whether I like it or not (unresolved externals, e.g. pthread_mutex_init, ..._lock, ..._unlock, ..._destroy, ...). I thought that defining HAVE_PTHREAD as 0 would omit those dependencies. Is there some simple way to compile without thread support?
> 

I will try to fix this, but it will take some time. I forgot that we still needed to do this. These days pthreads is available everywhere including Windows. But the option should do what it says and we've been lazy.

I will announce an rc3 later today which should fix the issues in the main repo. Please wait for Brian Gladman to announce on flint-devel that he has fixed any of the other issues in his repository before trying again however.

> ============================================================
> With these changes, I can compile all of FLINT2 2.6.0-rc2, but linking it has thread support problems.

**Comment by BrianGladman** [comment]
> 
> FWIW, Win10 doesn't seem to recognize alloca, but it does know about _alloca, so I put
> ` /D alloca=_alloca`  on the compiler command line.

If you are building from a clone of my repository, flint-config.h  includes the definition  

#define alloca _alloca

so its should not be necessary to add anything on the command line.  This hence suggests that the build is not acting as it should.  Can you please check that flint-config.h is being included (and contains this define).
 

> ============================================================
> In the file qadic\ctx_init_conway.c, there is a reference to the file CPImport.h which is not contained in the 2.6.0-rc2 source code. In previous versions, it was found in either /build.vc14/ or /qadic/. I copied it from an old version to /qadic/ which fixed the problem.

The CPimport.h file is present in the directory flint\build.vc, which is now where the current Visual Studio build files look for it.    Have you recently rerun the FLINT build generator?  I ask because I have done a fair bit of work on it over the last few weeks and this may mean that old build files will no longer work.

**Comment by sudleyplace** [comment]
On 5/29/2020 9:58 AM, Brian Gladman wrote:
>     FWIW, Win10 doesn't seem to recognize alloca, but it does know about
>     _alloca, so I put
>     |/D alloca=_alloca| on the compiler command line.
> 
> If you are building from a clone of my repository, flint-config.h 
> includes the definition
> 
> #define alloca _alloca
> 
> so its should not be necessary to add anything on the command line. This 
> hence suggests that the build is not acting as it should. Can you please 
> check that flint-config.h is being included (and contains this define).

I built FLINT on Win10 by downloading the 2.6.0-rc2.zip file, unzipping 
it, and running

bash
./configure --disable-shared
exit

to generate flint-config.h.

>     ============================================================
>     In the file qadic\ctx_init_conway.c, there is a reference to the
>     file CPImport.h which is not contained in the 2.6.0-rc2 source code.
>     In previous versions, it was found in either /build.vc14/ or
>     /qadic/. I copied it from an old version to /qadic/ which fixed the
>     problem.
> 
> The CPimport.h file is present in the directory flint\build.vc, which is 
> now where the current Visual Studio build files look for it. Have you 
> recently rerun the FLINT build generator? I ask because I have done a 
> fair bit of work on it over the last few weeks and this may mean that 
> old build files will no longer work.

As with my several previous builds of FLINT, I use MSVC from the command 
line, not the GUI, and so I skipped using your repository as I have 
custom Makefiles which are shared with the similar builds of ANANT, ARB, 
FLINT, MPC, MPFFT, etc.  These differences are "All Minor Cosmetic 
Compiler Issues", so please ignore my reports as we seem to have found 
similar solutions.
   I enjoy the challenge of figuring out what I've done wrong and then 
fixing it.  Given that I use custom Makefiles, I expect there will be 
differences that I alone need to resolve.


I greatly appreciate all of the work you folks have put into this highly 
worthwhile project.  I have incorporated FLINT (along with MPIR, MPFR, 
ARB, MPC, GMP, ECM, GSL, MPFFT, etc.) into my Experimental APL 
Interpreter to its great benefit.  Thank you all.

-- 
_______________________________________________________________
Bob Smith - bsmith@sudleyplace.com
http://www.sudleyplace.com - http://www.nars2000.org

**Comment by wbhart** [comment]
Some of your reports were certainly valuable. But I'll close this ticket now as essentially resolved.

**Comment by sudleyplace** [comment]
On 5/29/2020 9:02 AM, wbhart wrote:
[...]
>     ============================================================
>     For the moment, I'm compiling without thread support (HAVE_PTHREAD
>     0). However, there are a lot of instances where thread support is
>     included whether I like it or not (unresolved externals, e.g.
>     pthread_mutex_init, ..._lock, ..._unlock, ..._destroy, ...). I
>     thought that defining HAVE_PTHREAD as 0 would omit those
>     dependencies. Is there some simple way to compile without thread
>     support?
> 
> I will try to fix this, but it will take some time. I forgot that we 
> still needed to do this. These days pthreads is available everywhere 
> including Windows. But the option should do what it says and we've been 
> lazy.

No rush as I compiled rc1/rc2 because you asked for feedback and I 
wanted to thank you all for everything you've done.  For my part, I 
should be using thread support, so I'll look into adding that.

Thanks again.

-- 
_______________________________________________________________
Bob Smith - bsmith@sudleyplace.com
http://www.sudleyplace.com - http://www.nars2000.org
