### ISSUE TITLE
Possibly un-forwarded patch in the Debian package

### ISSUE THREAD

**Issue by SnarkBoojum** [wbhart/flint2#757]
I was reviewing my Debian package for flint to see if everything was known here ; and the status isn't clear: [undef_count_leading_zeros.patch](https://salsa.debian.org/science-team/flint/-/blob/master/debian/patches/undef_count_leading_zeros.patch)

Is it still needed? Was it known?

**Comment by wbhart** [comment]
As far as I can see that has been merged. It seems like a reasonable patch.

**Comment by SnarkBoojum** [comment]
Oh, if it has been merged already, then I can drop it!

**Comment by wbhart** [comment]
Sure. I don't see why not.
