### ISSUE TITLE
FLINT 2.6.0-rc4 Minor Cosmetic Compiler Issue On Windows

### ISSUE THREAD

**Issue by sudleyplace** [wbhart/flint2#763]
I am trying to compile this version on Win 10 using MSVC 2013 (ver. 18.00.40629).

Minor Cosmetic Compiler Issue:

* In the file `ulong_extras\randint.c`, the declaration of function `n_urandint` is
`mp_limb_t n_urandint(flint_rand_t state, const mp_limb_t limit)`
but the prototype in `ulong_extras.h` is
`ulong n_urandint(flint_rand_t state, ulong limit);`

Either remove `const` from the declaration or insert it into the prototype.

Support For No Threads:

* I'm unsure from your description of the changes in rc4 whether or not you intend to support no threads as in `./configure --disable-shared --disable-pthread`.

In any case, when I link rc4 I still get a dozen missing externals.  If I should have done something beyond the `configure` settings, that's my fault.

I really wasn't expecting you to address this issue so soon.  I'm perfectly happy to surround the following occurrences with `#if HAVE_PTHREAD` / `#endif` and be done with it.

FWIW, here's my list of errors from the linker:

```
flint32.lib(memory_manager.obj) : error LNK2019: unresolved external symbol _thread_pool_clear referenced in function _flint_cleanup_master
flint32.lib(fft_mfa_truncate_sqrt2_inner.obj) : error LNK2001: unresolved external symbol _global_thread_pool
flint32.lib(ifft_mfa_truncate_sqrt2.obj) : error LNK2001: unresolved external symbol _global_thread_pool
flint32.lib(memory_manager.obj) : error LNK2001: unresolved external symbol _global_thread_pool
flint32.lib(thread_support.obj) : error LNK2001: unresolved external symbol _global_thread_pool
flint32.lib(split_bits.obj) : error LNK2001: unresolved external symbol _global_thread_pool
flint32.lib(fft_mfa_truncate_sqrt2.obj) : error LNK2001: unresolved external symbol _global_thread_pool
flint32.lib(memory_manager.obj) : error LNK2001: unresolved external symbol _global_thread_pool_initialized
flint32.lib(thread_support.obj) : error LNK2001: unresolved external symbol _global_thread_pool_initialized
flint32.lib(thread_support.obj) : error LNK2019: unresolved external symbol _thread_pool_init referenced in function _flint_set_num_threads
flint32.lib(thread_support.obj) : error LNK2019: unresolved external symbol _thread_pool_set_affinity referenced in function _flint_set_thread_affinity
flint32.lib(thread_support.obj) : error LNK2019: unresolved external symbol _thread_pool_restore_affinity referenced in function _flint_restore_thread_affinity
flint32.lib(thread_support.obj) : error LNK2019: unresolved external symbol _thread_pool_get_size referenced in function _flint_request_threads
flint32.lib(thread_support.obj) : error LNK2019: unresolved external symbol _thread_pool_set_size referenced in function _flint_set_num_threads
flint32.lib(thread_support.obj) : error LNK2019: unresolved external symbol _thread_pool_request referenced in function _flint_request_threads
flint32.lib(thread_support.obj) : error LNK2019: unresolved external symbol _thread_pool_give_back referenced in function _flint_give_back_threads
flint32.lib(split_bits.obj) : error LNK2019: unresolved external symbol _thread_pool_wake referenced in function _fft_split_bits
flint32.lib(fft_mfa_truncate_sqrt2.obj) : error LNK2001: unresolved external symbol _thread_pool_wake
flint32.lib(fft_mfa_truncate_sqrt2_inner.obj) : error LNK2001: unresolved external symbol _thread_pool_wake
flint32.lib(ifft_mfa_truncate_sqrt2.obj) : error LNK2001: unresolved external symbol _thread_pool_wake
flint32.lib(split_bits.obj) : error LNK2019: unresolved external symbol _thread_pool_wait referenced in function _fft_split_bits
flint32.lib(fft_mfa_truncate_sqrt2.obj) : error LNK2001: unresolved external symbol _thread_pool_wait
flint32.lib(fft_mfa_truncate_sqrt2_inner.obj) : error LNK2001: unresolved external symbol _thread_pool_wait
flint32.lib(ifft_mfa_truncate_sqrt2.obj) : error LNK2001: unresolved external symbol _thread_pool_wait
RET\ND32\NARS2000.exe : fatal error LNK1120: 12 unresolved externals
```

**Comment by wbhart** [comment]
Thanks for the report of the errant const in the prototype. I have fixed this for the final release.

As for the messages you are getting, that may happen if you do not have HAVE_TLS set to 1 in flint-config.h. If this is actually a problem for you, let me know and I'll work on it. But as far as I know thread local storage has been available for a long time on Windows.

However, I don't know if Windows requires pthreads to be linked in order to support TLS. On Linux that is not needed, which is why I didn't take the extra step of supporting building without pthreads and without thread local storage.

**Comment by wbhart** [comment]
Oh wait, those symbols are not pthreads symbols. I am missing something here. Let me look into it. This should not be happening, and I tested this.

**Comment by wbhart** [comment]
I don't see why this is happening. There is no symbol _thread_pool_clear anywhere in the entire Flint library. There is thread_pool_clear, which is a function defined in thread_pool/clear.c. I don't see any reason why that wouldn't be being compiled into the library.

Can you check that file is actually being compiled. It's still required, but just doesn't use any threads.

**Comment by wbhart** [comment]
Given that there were no complaints about the later release candidates and release, may I presume this issue was addressed?
