### ISSUE TITLE
FLINT 2.6.0-rc4 versus Win10/x64

### ISSUE THREAD

**Issue by sudleyplace** [wbhart/flint2#764]
In the file `flint.h`, the function `FLINT_BIT_COUNT` is a problem on Win10/x64.  When compiling with MSVC 2013 in that context, I get an error message

`R:\NARS2000\flint\include\flint.h(318) : warning C4244: '=' : conversion from 'mp_limb_t' to 'unsigned int',  possible loss of data`.

As you already know, this occurs on Windows because it is quirky about its 64-bit ABI.  The short of it is that I changed both occurrences of `unsigned int` in

```
unsigned int FLINT_BIT_COUNT(mp_limb_t x)
{
   unsigned int zeros = FLINT_BITS;
   if (x) count_leading_zeros(zeros, x);
   return FLINT_BITS - zeros;
}
```
into `mp_limb_t` as in
```
mp_limb_t FLINT_BIT_COUNT(mp_limb_t x)
{
   mp_limb_t zeros = FLINT_BITS;
   if (x) count_leading_zeros(zeros, x);
   return FLINT_BITS - zeros;
}
```
recompiled all of FLINT 2.6.0-rc4 without error, and the problem went away.

I think this is a safe fix, but only you see the whole picture.

**Comment by wbhart** [comment]
That seems like a harmless change so I have made that change and tested it. It will be in the final release.
