### ISSUE TITLE
Getting the p out of each fq_nmod_t

### ISSUE THREAD

**Issue by tthsqe12** [wbhart/flint2#774]
I have decided not to touch the official interfaces for fmpz_mod_poly. I tried it, and it was a change of about 1500 lines of code. The problem with doing this were:
- the interfaces for fmpz_mod_poly must change 
- the interfaces for fq_embed must change

Of course the problems with not doing this are:
- fmpz_mod_poly arithmetic is locked into a bad interface, where either (1) precomputed inverses are not used, or (2) if precomputed inverses are used, they must recomputed by each function on function call, or (3) each polynomial stores a separate useless copy of all of the precomputed info.

Thankfully, `fq_t` is typedef'd to a `fmpz_poly`. However, `fq_nmod_t` is typedef'd to a `nmod_poly` which is an error in my opinion. For my work on the internals, I absolutely need the following type
```
typedef struct
{
    mp_limb_t * coeffs;
    slong alloc;
    slong length;
} n_poly_struct;

typedef n_poly_struct n_poly_t[1];
```
I also absolutely have to have a thin wrapper for arithmetic operations on these `n_poly_t` that take an `nmod_ctx_t` as a separate argument.

@wbhart  Would it be OK if I typedef'd fq_nmod_t to n_poly_t and re-implemented the arithmetic? No official interfaces should have to change, and, as a bonus, the size of each fq_nmod_t is halved. An answer sooner rather than later would be appreciated.

**Comment by wbhart** [comment]
If it is absolutely necessary, all official interfaces remain unaltered and you make the appropriate adjustments to Nemo (which has to actually create these structs) then it would be ok.

But note that this would be a breaking change which would mean we couldn't develop Nemo against it until it is fixed in both.

**Comment by wbhart** [comment]
Certainly (2) in your list above is not the way to go.

Of course Flint never envisaged working with multiple moduli in the same operation. If you need that then the current interface doesn't make sense.

**Comment by tthsqe12** [comment]
I assume the code in nemo is
https://github.com/Nemocas/Nemo.jl/blob/master/src/flint/FlintTypes.jl#L1692
It is actually not a breaking change because the first three fields will remain the same.
PS:
All of the mpoly_ctx_t's are wrong in nemo. They still work though.
The lll_ctx is also wrong. This one doesn't work.
Trying to guess how the compiler is going to layout a struct is just asking for trouble.

**Comment by wbhart** [comment]
Mostly it just needs to get the size right. Too small and you have problems. We mostly access the fields via accessor functions and not directly, so the layout isn't that important in most cases. There are some exceptions of course.

If you want to make a patch to fix the structs there, that would be appreciated.

**Comment by wbhart** [comment]
It's also using LLVM behind the scenes to lay out the structs, presumably, which is what Clang would do. So hopefully this is compatible with GCC.

**Comment by wbhart** [comment]
From memory the main field that we access directly in various places is the length field. I'm not sure if we do this for mpolys or not. We do access valuations/precisions/scale factors but these are actually Julia fields that we add to the Flint structures in all cases that I can think of, as we don't actually have series in Flint.

**Comment by tthsqe12** [comment]
I have given up on trying to have precomputed info for fmpz_mod_poly. The interface simply doesn't support it. I you ever want to revisit this topic, I would vote very heavily against putting the precomputed info in thread global storage. This would be worst that having no precomputed info in my opinion.

**Comment by fredrik-johansson** [comment]
I think your alternative nmod_poly type is fine; I guess the number of nmod_poly functions that need to be wrapped to support fq_nmod isn't huge.

**Comment by fredrik-johansson** [comment]
What arithmetic needs to be reimplemented though? The existing underscore methods should be usable.

**Comment by tthsqe12** [comment]
I need `n_poly_t`, which is to `nmod_poly` as `fmpz_poly` is to `fmpz_mod_poly`, and a basic interface that support memory management with a separate modulus.
It currently looks like
```
NMOD_MPOLY_FACTOR_INLINE
void n_poly_init(n_poly_t A)
{
    A->length = 0;
    A->alloc = 0;
    A->coeffs = NULL;
}

NMOD_MPOLY_FACTOR_INLINE
void n_poly_mod_add(n_poly_t A, const n_poly_t B, const n_poly_t C, nmod_t ctx)
{
    slong Alen = FLINT_MAX(B->length, C->length);
    n_poly_fit_length(A, Alen);
    _nmod_poly_add(A->coeffs, B->coeffs, B->length, C->coeffs, C->length, ctx);
    A->length = Alen;
    _n_poly_normalise(A);
}
```

**Comment by fredrik-johansson** [comment]
Yes, that's what I'd expect.

**Comment by wbhart** [comment]
Should we close this issue @tthsqe12 ?

**Comment by tthsqe12** [comment]
Yeah, I have no intention anymore of changing fq_nmod_t. It is what it is.
