### ISSUE TITLE
bug in fmpz_poly_factor

### ISSUE THREAD

**Issue by tthsqe12** [wbhart/flint2#783]
```
    {
        fmpz_poly_t a;
        fmpz_poly_factor_t f;
        fmpz_poly_init(a);
flint_printf("starting\n");
        fmpz_poly_set_str(a, "31  294114975 822759704 601207031 3459410600 6329635407 5561735376 2870497527 -364079376 -984488613 -2855108728 -5168185293 -2678402184 -3199593893 -2740409376 -1003657917 -549998688 -252445155 -80724312 -19101979 -28418280 -2087859 -9732528 -2615547 -159120 -148311 -4680 -1359 2504 73 0 1");
flint_printf("a: "); fmpz_poly_print_pretty(a, "x"); printf("\n");
        fmpz_poly_factor_init(f);
        fmpz_poly_factor(f, a);
flint_printf("f: "); fmpz_poly_factor_print(f); printf("\n");
        flint_printf("done\n");
        fmpz_poly_factor_clear(f);
        fmpz_poly_clear(a);
    }
```

**Comment by thofma** [comment]
This is hanging. I found it when trying to use Hecke/Nemo with flint 2.6.0.

It was not failing on previous versions, because flint was not calling van Hoeij. But with slighlty changed parameters, it is now calling van Hoeij for this example. But it hangs forever.

**Comment by tthsqe12** [comment]
This is caused by
https://github.com/wbhart/flint2/commit/aad28633f1bf88c47436fdc3ab9e79220829b13a
The last commit before the release.

**Comment by wbhart** [comment]
@tthsqe12 do you have an explanation for why this would be a problematic commit? The assembly code in longlong.h actually uses mp_limb_t internally for the count and returning it as an mp_limb_t shouldn't be problematic I would have thought, given that it's just an unsigned number from 0-64 inclusive.

**Comment by tthsqe12** [comment]
@wbhart the issue is on https://github.com/wbhart/flint2/blob/trunk/fmpz_mat/next_col_van_hoeij.c#L87

previously this like looked like
`slong < slong + unsigned int`

Because of
> If the type of the operand with signed integer type can represent all of the values of the type of the operand with unsigned integer type, the operand with unsigned integer type is converted to the type of the operand with signed integer type.
`slong + unsignged int` is still `slong`.

But now we have
`slong < slong + ulong`
and `slong + ulong` is `ulong` and the comparison is done using `ulongs` which is nonsense because `k` could be negative.

I think this line of code in `fmpz_mod_next_col_van_hoeij` is sloppy and should be fixed, possibly with an additional `k < 0 ||`.

**Comment by tthsqe12** [comment]
Actually, I would prefer the bitcount to be casted to an slong. This is one problem with using types that are much larger than needed. Btw, this code should also have been broken on 32 bits both before and after aad2.

**Comment by wbhart** [comment]
I'm ok with casting to slong. I don't know if this will fix the issue that the original patch was supposed to fix, but probably it will. We can ask for additional testing before 2.6.1 to confirm anyway.

I'll merge this change tonight and also try to address the bugs you found in fq_poly.

Would you be interested in being given access to the ARM machine the Debian people have to try and track down the ARM 32 bit issues. I am on holidays for two weeks from tomorrow, so it doesn't make sense for me to do it. If you agree, I can send @SnarkBoojum your email address privately and confirm you have been working on Flint for years.

**Comment by SnarkBoojum** [comment]
Which platform is broken by this issue?

**Comment by wbhart** [comment]
@SnarkBoojum Sorry, I probably shouldn't have tagged you on this issue or talked about the ARM issue here.

This is a bug report for x86_64 and not relevant to the problems you are seeing on Debian. I merely wanted to give you the heads up that I'll send @tthsqe12 's email address to you if he agrees to look into the ARM issue you were seeing.

**Comment by tthsqe12** [comment]
Just for clarification, I am talking about only touching the code in van_heoij
```
-   if (k < exp + FLINT_BIT_COUNT(r + 1))
+   if (k < exp + (slong)FLINT_BIT_COUNT(r + 1))
```
I don't have any problems with the FLINT_BIT_COUNT function returning a ulong, but it should come with a strong warning:
```
+ /* WARNING: this will poison all signed arithmetic */
static __inline__
mp_limb_t FLINT_BIT_COUNT(mp_limb_t x)
```

**Comment by wbhart** [comment]
If it's a problem with all signed arithmetic, why not simply make it signed?

**Comment by tthsqe12** [comment]
flint_bitcnt_t is unsigned. It would be the height of inconsistency for FLINT_BIT_COUNT to return signed. I am already going half crazy because of the inconsistencies in flint.

**Comment by wbhart** [comment]
Ok, that's a reasonable argument. I'll switch to an unsigned value and fix the issue in van hoeij.

**Comment by tthsqe12** [comment]
@wbhart Please add the problematic example to the test code.

**Comment by wbhart** [comment]
I did.
