### ISSUE TITLE
HPPA stuck in t-divrem_monagan_pearce (fq_nmod_mpoly)

### ISSUE THREAD

**Issue by SnarkBoojum** [wbhart/flint2#784]
Checking why the platform doesn't build anymore in Debian, I see that the above test just stays stuck. After a while, the Debian builder errors out and declares a failure.

Probably an infinite loop somewhere.

**Comment by thofma** [comment]
Should be fixed by #790

**Comment by SnarkBoojum** [comment]
Do you want me to confirm the modification is correct?

**Comment by wbhart** [comment]
We may as well just do a release which you can check. We can do a release candidate if you like to confirm it's fixed for the release.

**Comment by SnarkBoojum** [comment]
If you're satisfied with your fix, a new release is nice.

**Comment by SnarkBoojum** [comment]
I can confirm the commit fixes HPPA ; I uploaded in Debian a 2.6.0+this ; it does nothing for the arm situation ; see the [build logs for 2.6.0-3](https://buildd.debian.org/status/package.php?p=flint).
