### ISSUE TITLE
ARMHF: pollard_brent_single....FAIL : Pollard Rho failed too many times (106 times)

### ISSUE THREAD

**Issue by SnarkBoojum** [wbhart/flint2#786]
The armhf platform is broken because of the above message.

**Comment by thofma** [comment]
@SnarkBoojum Could you sponsor @tthsqe12 for a gues account on the arm hf server?

**Comment by SnarkBoojum** [comment]
I wanted to try a git bisect, but the old version tags are gone, and it looks like a few of the commits don't even build, so it ended fast.

**Comment by wbhart** [comment]
Were you able to get access for @tthsqe12 ?

**Comment by tthsqe12** [comment]
I have no access

**Comment by SnarkBoojum** [comment]
No access requested, no access granted... [Here's the procedure](https://dsa.debian.org/doc/guest-account/) ; I can sponsor but you have to provide some information...

**Comment by tthsqe12** [comment]
We are trying something a bit simpler first.

**Comment by SnarkBoojum** [comment]
Can I help?

**Comment by tthsqe12** [comment]
I don't think so. We will know in a few hours if we really need access to the machine that was failing. Did you observe this consistently failing at every try, or was it more a Heisenbug?

**Comment by SnarkBoojum** [comment]
I would say it fails consistently.

**Comment by wbhart** [comment]
@tthsqe12 it passes on x86 32 bit if that's what you are wondering. It really does seem to be ARM specific, and most likely something in longlong.h. I looked through the code for anything else it could be and came up blank.

**Comment by tthsqe12** [comment]
We will most likely be able to fix this ourselves by tomorrow or the day after. By the way, the other two failures on mips and something else should be fixed.

**Comment by wbhart** [comment]
Should be fixed in the flint-2.6 branch now. We'll issue 2.6.1 as soon as some of the other recent bug tickets are closed.

**Comment by SnarkBoojum** [comment]
I'll wait for 2.6.1 ; thanks!
