### ISSUE TITLE
bug in fq_poly_xgcd_euclidean_f

### ISSUE THREAD

**Issue by tthsqe12** [wbhart/flint2#788]
the case of one constant input and one input of degree > 0 is not handled correctly.

**Comment by wbhart** [comment]
Can you explain what you think is wrong?

The only thing I can see is that the lenB == 1 case seems to make the result monic, whereas the non-underscore function already does that.

If there's something wrong with this function there might be something wrong with the nmod_poly and fmpz_mod_poly functions too.

**Comment by tthsqe12** [comment]
fixed by https://github.com/wbhart/flint2/pull/791/commits/6cdc998763c51fc0aed21ab50f19aa4171e182e7
in #791
