### ISSUE TITLE
handle composite "characteristics" in fq_poly_xgcd_euclidean_f

### ISSUE THREAD

**Issue by tthsqe12** [wbhart/flint2#789]
I was surprised that the following code aborts. It is due to carelessness in the inversion of the "field" elements. It should be done with `_fmpz_mod_poly_gcdinv_f`, but it is not. However, there are too many other issues with `fq_poly_t` that I can't fix it right now.
```
#include "fq_poly.h"

void fq_poly_rand_monic(fq_poly_t f, flint_rand_t state, slong len, fq_ctx_t ctx)
{
    slong i;
    FLINT_ASSERT(len > 0);
    fq_poly_fit_length(f, len, ctx);
    f->length = len;
    fq_one(f->coeffs + len - 1, ctx);
    for (i = len - 2; i >= 0; i--)
        fq_rand(f->coeffs + i, state, ctx);
    f->length = len;
    _fq_poly_normalise(f, ctx);
}


int
main(void)
{
    slong i, j, k;

    FLINT_TEST_INIT(state);

    {
        fmpz_t p;
        fmpz_mod_poly_t h;
        fq_ctx_t ctx;
        fq_poly_t a, b, g, s, t, t1, t2;
        fq_t f;
        slong tries, fails;

        fmpz_init_set_ui(p, 17*17);
        fmpz_mod_poly_init(h, p);

        fmpz_mod_poly_set_coeff_ui(h, 2, 1);
        fmpz_mod_poly_set_coeff_ui(h, 1, 1);
        fmpz_mod_poly_set_coeff_ui(h, 0, 1);

flint_printf("h: "); fmpz_mod_poly_print_pretty(h, "t"); flint_printf("\n");

        fq_ctx_init_modulus(ctx, h, "t");
        fq_poly_init(a, ctx);
        fq_poly_init(b, ctx);
        fq_poly_init(g, ctx);
        fq_poly_init(s, ctx);
        fq_poly_init(t, ctx);
        fq_poly_init(t1, ctx);
        fq_poly_init(t2, ctx);
        fq_init(f, ctx);

        tries = 0;
        fails = 0;
        for (i = 0; i < 2000000; i++)
        {
            tries++;
            fq_poly_rand_monic(a, state, 4, ctx);
            fq_poly_rand_monic(b, state, 3, ctx);
            fq_poly_xgcd_euclidean_f(f, g, s, t, a, b, ctx);
            if (!fq_is_one(f, ctx))
            {
                fails++;
            }
            else
            {
                fq_poly_mul(t1, s, a, ctx);
                fq_poly_mul(t2, t, b, ctx);
                fq_poly_add(t1, t1, t2, ctx);
                if (!fq_poly_equal(t1, g, ctx))
                {
                    flint_printf("oops tries = %wd\n", tries);
                    flint_printf("f: "); fq_print_pretty(f, ctx); flint_printf("\n");
                    flint_printf("a: "); fq_poly_print_pretty(a, "x", ctx); flint_printf("\n");
                    flint_printf("b: "); fq_poly_print_pretty(b, "x", ctx); flint_printf("\n");
                    flint_printf("s: "); fq_poly_print_pretty(s, "x", ctx); flint_printf("\n");
                    flint_printf("t: "); fq_poly_print_pretty(t, "x", ctx); flint_printf("\n");
                    flint_printf("g: "); fq_poly_print_pretty(g, "x", ctx); flint_printf("\n");
                    flint_printf("s*a+t*b: "); fq_poly_print_pretty(t1, "x", ctx); flint_printf("\n");
                    flint_abort();
                }
            }
        }

        flint_printf("prob: %f = %wd/%wd\n", (double)fails/(double)tries, fails, tries);

        fmpz_mod_poly_clear(h);

        fq_poly_clear(a, ctx);
        fq_poly_clear(b, ctx);
        fq_poly_clear(g, ctx);
        fq_poly_clear(s, ctx);
        fq_poly_clear(t, ctx);
        fq_poly_clear(t1, ctx);
        fq_poly_clear(t2, ctx);
        fq_clear(f, ctx);
        fq_ctx_clear(ctx);
    }

    FLINT_TEST_CLEANUP(state);
    return 0;
}
```

**Comment by wbhart** [comment]
I fixed some bugs in fmpz_mod_poly with the _f functions and completely forgot that this code had already been ported to fq_poly as well. It obviously needs fixing there too.

**Comment by tthsqe12** [comment]
So you agree that if it returns with f=1, we should have s*a+b*t=g?
Here was my proposed fix https://github.com/tthsqe12/flint2/blob/tfix/fq/gcdinv.c

**Comment by wbhart** [comment]
I honestly don't know. I would have to think about the mathematics to see if the function even makes sense. Just because it works for Z/pZ doesn't mean automatically that it will work here.

**Comment by tthsqe12** [comment]
It is a very simple extension of the existing function. The function tries to solve `s*a+b*t = g` as if the fq_ctx_t were a field. If nothing goes wrong, the function doesn't know it is not a field, and everything is fine.

**Comment by wbhart** [comment]
Well sure, but that's not a proof of correctness.

**Comment by tthsqe12** [comment]
I think it is easy to make it one.

**Comment by wbhart** [comment]
For example, the algorithm for finding a square root mod p can be extended easily to an algorithm for finding a square root mod n. If nothing goes wrong the algorithm doesn't know it's not a field and yet it certainly won't return a square root mod n, even though such a thing exists.

**Comment by wbhart** [comment]
The usual Euclidean algorithm generally relies on having a Euclidean domain or at the very least some kind of Euclidean ring. Z/nZ is the latter, but I'm not sure about the more general case.

**Comment by thofma** [comment]
I think one can just use that `(a, b) = (a, b - a * q) = ... = (g, 0)`, so that if all of the Euclidean divisions work, then one has `(a, b) = (g)`. Thus the result `g` is a gcd of `a` and `b`. This works for any ring.

**Comment by tthsqe12** [comment]
With the important point that the gcd is able to be made monic in the last step.

**Comment by wbhart** [comment]
@thofma Yes, I suppose that follows (with the proviso that "any ring" is restricted to rings in which you have some notion of "Euclidean" division, that you don't hit impossible inverses and that the process terminates in finite time, which is what I assume you meant).

I would have to quickly check that one can "revert" the sequence of Euclidean remainders to retrieve the Bezout relation that @tthsqe12  is after, without anything going wrong. Probably. So that's the answer to the original question then. Probably.

**Comment by wbhart** [comment]
We'll have to implement a new function for the _f version of inversion since you can't just put fmpz_mod_poly code in templated finite field code. It'll have to be implemented for each of the finite field types.

**Comment by tthsqe12** [comment]
No. The fix is in gcdinv, which is not part of the templated part. Everything was satisfactory in fq_poly with the change I had above.

**Comment by wbhart** [comment]
I don't see how the proposed change is correct. You are setting the "factor of the modulus" to zero. How is that useful in an _f function? Won't you simply lose the factor?

**Comment by wbhart** [comment]
You realise that no one has tried to support composite "characteristic" in *any* of the finite field code. This is not an isolated incidence I am sure.

Anyhow, given that the fq_poly_...._f functions are surely for detecting factors of the modulus not the characteristic, wouldn't it make more sense to just raise an exception if a factor of the "characteristic" is found?

**Comment by tthsqe12** [comment]
In the cases that it worked, the previous behavior of the function was to set the `f` to zero. I am simply making it work in all cases. If you would to make it set `f` to an actual factor of the characteristic, be my guest. However, this would be equally inconsistent with the stated behavior of the function.

**Comment by tthsqe12** [comment]
> Anyhow, given that the fq_poly_...._f functions are surely for detecting factors of the modulus not the characteristic, wouldn't it make more sense to just raise an exception if a factor of the "characteristic" is found?

No. The point of this function is to have an absolutely safe function for doing xgcd. This means no throwing, especially since flint exceptions are not real exception, and leave the library in a corrupted state.

**Comment by wbhart** [comment]
Are you sure it's not returning mathematical rubbish if there was an impossible inverse here?

**Comment by tthsqe12** [comment]
If there is an impossible inverse anywhere, the _f functions are supposed to safely return with f!=1

**Comment by wbhart** [comment]
Maybe we ought to update the documentation then to state that a return value of 0 means the characteristic was not prime. It almost seems like it should return two values, one for a factor of the modulus and one for a factor of the characteristic, otherwise that factor is just lost.

**Comment by tthsqe12** [comment]
As I said before, it would not be inconsistent with the documentation to return with a integral f!=1 in the case of composite characteristic found. It is just that the current behavior of the function is to set it to zero (sometimes).

**Comment by tthsqe12** [comment]
Fix in https://github.com/wbhart/flint2/pull/791/commits/5a79a801ae58b4e35a1eb2f2b6d6783b17abf039 in #791 sets `f` to zero in the case where it detects a composite characteristic. The documentation is silent on composite characteristics, so as long as we return in this case with a `f!=1` it should be ok. If you want it to actually return a divisor of the characteristic, this will require a bit more work and is inconsistent with the previous behavior of the function.

**Comment by wbhart** [comment]
No, that sounds fine. So I can consider this fixed by #791 then?

**Comment by tthsqe12** [comment]
If the composite test code passes, I am sure it is probably correct. Let me rebase and run my code above.

**Comment by tthsqe12** [comment]
looks good

**Comment by wbhart** [comment]
Excellent! Any other reasons you know of to hold up 2.6.1? Or are we good to go?

I've merged all your patches and don't see any further issues that are reported that should hold a point release.

We can later address any failures in the minor debian arches. So long as the major arches all pass that is enough for a 2.6.1.

**Comment by tthsqe12** [comment]
Considering what I have seen in fq_poly_templates thus far, I am fairly confident there are more trivial bugs in corner cases. fq_nmod_poly is currently meeting my needs, but it will be about a day before I will be able to thoroughly test fq_nmod_poly for my needs.

**Comment by wbhart** [comment]
That's ok, we can do a 2.6.2 to address those. So long as there is nothing currently known to be broken for sure.
