### ISSUE TITLE
_nmod_mat_set_mod() calls count_leading_zeros() twice

### ISSUE THREAD

**Issue by krisk0** [wbhart/flint2#79]
In FLINT version 2.4.3, subroutine count_leading_zeros() is called twice on same data when constructing nmod_mat.

First call is in _nmod_mat_set_mod() and second call in n_preinvert_limb().

I suggest a fix that does not increase code length:
```
--- nmod_mat-old.h      2014-04-30 16:55:40.000000000 +0400
+++ nmod_mat.h  2014-06-09 10:38:55.877107772 +0400
@@ -65,8 +65,8 @@
 _nmod_mat_set_mod(nmod_mat_t mat, mp_limb_t n)
 {
     mat->mod.n = n;
-    mat->mod.ninv = n_preinvert_limb(n);
     count_leading_zeros(mat->mod.norm, n);
+    invert_limb(mat->mod.ninv, n<<mat->mod.norm);
 }
 
 /* Memory management */
```

**Comment by kushagrasurana** [comment]
why is the issue not closed?
i believe the code above solved the problem.

**Comment by wbhart** [comment]
It does solve the problem, if you really consider it to be one. But it's not been merged, probably because we were lazy and there was no pull request.

**Comment by wbhart** [comment]
Fixed in trunk.
