### ISSUE TITLE
bug in _nmod_vec_scalar_mul_nmod?

### ISSUE THREAD

**Issue by tthsqe12** [wbhart/flint2#793]
`_nmod_vec_scalar_mul_nmod` has no stated restriction that `len > 0`, yet it can call `mpn_mul_1` which does need `len > 0`.

**Comment by wbhart** [comment]
Yeah we should maybe introduce flint_mpn_mul_1 in gmpcompat.h

**Comment by tthsqe12** [comment]
No. I see no reason to call mpn_mul_1 to propogate carries that don't exist. A simple for loop with ordinary c multiplication will suffice, esp since the compiler is instructed to unroll every loop with funroll loops.

**Comment by tthsqe12** [comment]
Oh, I see the same code is supposed to work on both aliased input and non-aliased input, so most optimizations are out the window.

**Comment by tthsqe12** [comment]
should be fixed https://github.com/wbhart/flint2/pull/797
