### ISSUE TITLE
bug in fq_poly_div_series

### ISSUE THREAD

**Issue by tthsqe12** [wbhart/flint2#794]
There is another false dependence on the input due to some carelessness in _fq_poly_div_series when dividing by 1.

**Comment by thofma** [comment]
Are you in your office?

**Comment by tthsqe12** [comment]
should be fixed by https://github.com/wbhart/flint2/pull/791/commits/dd8b463a038935bed6dd05da348cbee0fa8ba6a7 in https://github.com/wbhart/flint2/pull/791
