### ISSUE TITLE
Soname in 2.6.1

### ISSUE THREAD

**Issue by SnarkBoojum** [wbhart/flint2#798]
Until 2.6.0, flint built library files like this:
```
/usr/lib/x86_64-linux-gnu/libflint-2.6.0.so.14.0.0
/usr/lib/x86_64-linux-gnu/libflint-2.6.0.so
```

in 2.6.1, it looks like this:
```
/usr/lib/x86_64-linux-gnu/libflint-2.6.1.so.14.0.1
/usr/lib/x86_64-linux-gnu/libflint-2.6.1.so
/usr/lib/x86_64-linux-gnu/libflint.so.14
```

Is the move intentional? If you intend to use soname versions (here 14) according to the standards, let me know so I number my packages accordingly.

**Comment by wbhart** [comment]
I'm not aware of any changes that we made here. As far as I know I simply updated the patch number of the soname.

Could this change be something to do with the tools we are using for this?

**Comment by isuruf** [comment]
In 2.6.0 it was,
```
libflint.so  libflint.so.14  libflint.so.14.0.0
```
and in 2.5.2, it was,
```
libflint.so  libflint.so.13  libflint.so.13.5.2
```

Apparently, Debian had a rule `sed -i Makefile -e "/^FLINT_LIB\>=/s/libflint/libflint-$(DEB_VERSION_UPSTREAM)/"` and I guess it was dropped for 2.6.1.

**Comment by SnarkBoojum** [comment]
Ah, I found out what I changed in the packaging : I just wasn't shipping the file. But still, if you use soname according to standards, that might be a good idea if I used it.
