### ISSUE TITLE
Access violation in fmpq_poly/t-add_sub_fmpq on Windows

### ISSUE THREAD

**Issue by wbhart** [wbhart/flint2#803]
Brian Gladman reports:

It fails on line 52 in t-add_sub_fmpq.c when i == 41 so I added:

```
       if(i == 41)
        {
            printf("\nt = "); fmpq_poly_print(t);
            printf("\nb = "); fmpq_poly_print(b);
            printf("\nc = "); fmpq_print(c);
            printf("\n");
            fflush(stdout);
        }
        fmpq_poly_add_fmpq(t, b, c);  // causes an access violation
        fmpq_poly_sub_fmpq(a, t, c);
```

before the line and gave the gave the following inputs:

t = 0
b = 1  5401982579940461832074144198431120424832
c = -2/195267

The call stack is:

  fmpq_poly_add__fmpq
    _fmpq_add
      _fmpz_add
        _fmpz_add
          __fmpz_promote access violation (address 0)

**Comment by BrianGladman** [comment]
The test that fails is the only test that invokes the block of code at line 157 to 163 in fmpq_poly_add_fmpq.   The first parameter in the call to _fmpq_add, i.e. res->coeffs has never been set and is zero (null) at this point and causes an access violation in _fmpq_add

**Comment by fingolfin** [comment]
If I apply your modification of the test and run on this on macOS, I get the same output; and yeah, also here `t->coeffs` / `res->coeffs` is NULL *before* invoking `fmpq_poly_add_fmpq`. Then the call `fmpq_poly_set(res, poly);` is supposed to set it to something that's not null. Are you saying that `res->coeffs` was 0 afterwards despite this?

**Comment by BrianGladman** [comment]
Within the inlined routine  fmpq_poly_add_fmpq, the  code block that causes the access violation occurs before fmpq_poly_set(res, poly) is called.   I suspect that the fix is to move this call to before the offending block of code.

**Comment by fingolfin** [comment]
Could it be that you are looking at Flint 2.6.0, not 2.6.1?

Otherwise I am a bit confused now, because you earlier mentioned that the test fails when the code in lines 157-163 is invoked, but in my copy of the code, that comes *after* the call to `fmpq_poly_set(res, poly);`, which indeed is in line 157. This wasn't so in 2.6.0, though, this was a fix made in 17d26d4c957828f3c98c15ddec85108f841d3438.

Here is the relevant code as it looks right now:

https://github.com/wbhart/flint2/blob/c2b11aad82014c18118d02323eb51ead08352ab5/fmpq_poly/inlines.c#L147-L165

**Comment by BrianGladman** [comment]
That explains it, thanks.   I am using trunk from Bill's repository but it changed after I cloned it so I have just found and fixed the same bug that someone else found!

**Comment by wbhart** [comment]
Then we can close this issue?

**Comment by BrianGladman** [comment]
yes

**Comment by wbhart** [comment]
Thanks @BrianGladman 

I think we are ok to issue 2.6.2 then. Is everyone agreed? @fredrik-johansson @tthsqe12 ?

As Brian has now presumably tested the latest trunk, which contains the same fixes, we can even announce this one as a release in all the usual channels, (with full MSVC support).

**Comment by BrianGladman** [comment]
On 30/07/2020 15:50, wbhart wrote:
> Thanks @BrianGladman <https://github.com/BrianGladman>
> 
> I think we are ok to issue 2.6.2 then. Is everyone agreed?
> @fredrik-johansson <https://github.com/fredrik-johansson> @tthsqe12
> <https://github.com/tthsqe12> ?
> 
> As Brian has now presumably tested the latest trunk, which contains the
> same fixes, we can even announce this one as a release in all the usual
> channels, (with full MSVC support).

I have just completed a build and test from scratch and all tests pass.

So all now OK on my Visual Studio 2019 build.

   Brian

**Comment by tthsqe12** [comment]
I think everything should be fine since 2.6.1 was fine. The real test is if it works with hecke. The only think you might want to fix is the printing of zero in fq_zech. But, this is no big deal for anyone.

**Comment by wbhart** [comment]
Yeah, I'll open a ticket for that. I don't think it is a severe bug. We'll just bundle it with the next release.

**Comment by thofma** [comment]
If you give me half an hour, I can try to run the Hecke tests.
