### ISSUE TITLE
Zero prints incorrectly in fq_zech

### ISSUE THREAD

**Issue by wbhart** [wbhart/flint2#808]
Users currently have to deal with that case separately, as the printing is broken.

**Comment by tthsqe12** [comment]
When you fix this, you might want to make a non-generic version of fq_zech_sqrt. I think fq_zech_sqrt is a lot easier than the generic code.

**Comment by wbhart** [comment]
That already exists, in the fq_zech directory.

**Comment by tthsqe12** [comment]
oh, good. My bad.
