### ISSUE TITLE
Clarify remaining GPL2+ headers

### ISSUE THREAD

**Issue by nckx** [wbhart/flint2#812]
Hullo all,

Thanks for FLINT!  While versions >2.5 are advertised as [LGPL-2.1+](http://flintlib.org/index.html), there are still some [GPL-2+](https://github.com/wbhart/flint2/blob/trunk/fmpz_mod_poly/profile/p-minpoly.c#L1) headers to be found.  Some are in tests, but not all.

<details><summary> :eyes: </summary>
<p>

```shell
$ grep -r "GNU General Public License as" *
fmpq_poly/test/t-add_sub_fmpq.c:    it under the terms of the GNU General Public License as published by
fmpz_mod_poly/test/t-minpoly.c:    it under the terms of the GNU General Public License as published by
fmpz_mod_poly/profile/p-minpoly.c:    it under the terms of the GNU General Public License as published by
fmpz_mod_poly/minpoly_hgcd.c:    it under the terms of the GNU General Public License as published by
fmpz_mod_poly/minpoly_bm.c:    it under the terms of the GNU General Public License as published by
qsieve/test/t-primes_init.c:    it under the terms of the GNU General Public License as published by
qsieve/test/t-factor.c:    it under the terms of the GNU General Public License as published by
```
</p></details>

All non-test files carry a ‘public domain’ notice below the GPL2+ header.  This (IANAL) probably makes your (L)GPL header irrelevant anyway.  _[edit: in some countries; ‘public domain’ is meaningless elsewhere.]_

Still, it would be nice if you could remove any ambiguity in the sources themselves.

**Comment by wbhart** [comment]
Thanks, we'll fix these files.

**Comment by fingolfin** [comment]
I found the following files with GPL header via `git grep -l 'GNU General Public License'`:
- fmpq_poly/test/t-add_sub_fmpq.c
- fmpz_mod_poly/minpoly_bm.c
- fmpz_mod_poly/minpoly_hgcd.c
- fmpz_mod_poly/profile/p-minpoly.c
- fmpz_mod_poly/test/t-minpoly.c
- qsieve/test/t-factor.c
- qsieve/test/t-primes_init.c

**Comment by wbhart** [comment]
@fingolfin You have to click the little eyes icon on GitHub to see the rest of the OP.

But it's good to see that both lists are identical. :-)

**Comment by wbhart** [comment]
Fixed in trunk. Backported to flint-2.6.
