### ISSUE TITLE
`fq_gen` broken on 2.6.2

### ISSUE THREAD

**Issue by thofma** [wbhart/flint2#813]
```
julia> Fp = ResidueRing(FlintZZ, fmpz(2))
Integers modulo 2

julia> Fpx, x = Fp["x"]
(Univariate Polynomial Ring in x over Integers modulo 2, x)

julia> typeof(x)
fmpz_mod_poly

julia> F, a = FlintFiniteField(x, "a")
(Finite field of degree 1 over F_2, 0)

julia> z = gen(F)
0

julia> iszero(z)
false

julia> isone(z)
false
```

I think it broke here: https://github.com/wbhart/flint2/commit/c2b11aad82014c18118d02323eb51ead08352ab5

**Comment by thofma** [comment]
P.S.: It works with `fq_nmod`.

**Comment by wbhart** [comment]
Ah yeah, thanks. I'll fix it and we can do a 2.6.3.

**Comment by thofma** [comment]
Thanks!

I don't know much about the details, but if possible, would be great to also have https://github.com/wbhart/flint2/pull/814.

**Comment by thofma** [comment]
P.S.: If you have a candidate for 2.6.3, I am happy to test it.

**Comment by tthsqe12** [comment]
I know that my finite field representatives are not essential bug fixes, but could we have them in 2.6.3?
https://github.com/wbhart/flint2/pull/776

**Comment by wbhart** [comment]
I won't get to a new release until tomorrow. But I'll do it as soon as I can.

@tthsqe12 Merging new features in a stable bugfix branch is really not a good idea. I don't want to set that precedent. If it's urgent for some project where it's needed, then I can do it. But overall it's just poor practice.

**Comment by wbhart** [comment]
@thofma Can I ask what the expected behaviour is here? Is the only problem that iszero(z) returns false?

**Comment by wbhart** [comment]
For me it returns true anyway. Still I can see I have a bug to fix, namely that the length is set to 1 when the generator is 0.
