### ISSUE TITLE
Build dependencies failure on travis

### ISSUE THREAD

**Issue by wbhart** [wbhart/flint2#822]
The travis jobs [1] are randomly failing on Xenial. The message given is:

/home/travis/build/wbhart/flint2/libflint.so: undefined reference to `__gmpn_com'

It seems that yasm, mpir, mpfr and flint all build just fine, but when the test is run with a simple 5 line flint program to determine if everything built correctly, it fails saying __gmpn_com is missing.

We are using MPIR-3.0.0 which contains MPN(com_n), but in the gmp.h file mpn_com is defined to be MPN(com_n) which expands to the correct __gmpn_com_n.

If anyone has any idea what is going on, it would help a lot. I simply don't see how there can be a problem here, especially as the problem doesn't happen every time (but it happens regularly).

It's as though it is picking up an old GMP somewhere. But I don't see how. GMP 6.1.2 and 6.2 both contain mpn_com but not mpn_com_n, which would explain the problem if I understood why it would pick up some other GMP.

[1] https://travis-ci.org/github/wbhart/flint2/jobs/718622400

**Comment by thofma** [comment]
Near line 11398 (the cmake build), there is
```
[0K$ if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ldd libflint.so; echo "Running cmake build"; mkdir build; cd build; cmake -G"Unix Makefiles" -DWITH_NTL=yes -DBUILD_TESTING=yes -DCMAKE_BUILD_TYPE=Release ..; ${MAKE}; ldd lib/libflint.so; cd ..; fi
	linux-vdso.so.1 =>  (0x00007ffd51137000)
	libmpfr.so.6 => /home/travis/build/wbhart/flint2/local/lib/libmpfr.so.6 (0x00007f3e14247000)
	libgmp.so.23 => /home/travis/build/wbhart/flint2/local/lib/libgmp.so.23 (0x00007f3e13fd1000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f3e13cc8000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f3e13aab000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f3e136e1000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f3e14f49000)
Running cmake build
mkdir: cannot create directory â€˜buildâ€™: File exists
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/lib/ccache/gcc
-- Check for working C compiler: /usr/lib/ccache/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/lib/ccache/c++
-- Check for working CXX compiler: /usr/lib/ccache/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found GMP: /usr/include/x86_64-linux-gnu (Required is at least version "5.1.0") 
-- Found MPFR: /usr/include (Required is at least version "1.0.0") 
-- Found NTL: /usr/lib/libntl.so  
-- Found PythonInterp: /opt/pyenv/shims/python (found version "2.7.12") 
-- Looking for pthread.h
...
```
This does not look good. Looks like the cmake thingy picks up the wrong things.

**Comment by isuruf** [comment]
https://github.com/wbhart/flint2/pull/823

**Comment by wbhart** [comment]
Yeah, I think roughly speaking there are two Flint builds. The usual one uses mpir-3.0.0 and the cmake one uses gmp-6.x.y. The latter doesn't have the __gmpn_com_n symbol that MPIR's gmp.h wants. And for some reason the CMake build uses MPIR's gmp.h not GMP's.

Let's see if @isuruf 's patch fixes the issue.
