### ISSUE TITLE
pthread_getaffinity_np/pthread_setaffinity_np aren't portable

### ISSUE THREAD

**Issue by SnarkBoojum** [wbhart/flint2#826]
The name _np means they're not portable, so they should be checked for in the configure script to rule out architectures where they are not available, or where they don't work as expected.

To be specific, the hurd architecture for Debian seems to lack the functions, and from poking around on the net, it looks like it might not work exactly the same everywhere.

The configure script does check HAVE_CPU_SET_T, but apparently, that wasn't good enough to error out early on the hurd box.

**Comment by SnarkBoojum** [comment]
I suggest having a HAVE_THREAD_CPU_AFFINITY checking for both cpu_set_t and one of pthread_[gs]etaffinity_np. I'll see if I can propose a patch.

**Comment by SnarkBoojum** [comment]
Here it is:
[cpu_affinity.txt](https://github.com/wbhart/flint2/files/5095847/cpu_affinity.txt)

**Comment by SnarkBoojum** [comment]
Ah, bad patch, it always fails the test!

**Comment by SnarkBoojum** [comment]
[cpu_affinity.txt](https://github.com/wbhart/flint2/files/5095902/cpu_affinity.txt)

This patch gives HAVE_CPU_SET_T the value 1 on my box and 0 on the hurd box, so it's definitely better!

**Comment by wbhart** [comment]
Thanks very much for the patch. I've applied it as supplied, so hopefully this is resolved.
