### ISSUE TITLE
Migrating from travis-ci.org to travis-ci.com

### ISSUE THREAD

**Issue by fingolfin** [wbhart/flint2#846]
In 2018, Travis CI decided to merge travis-ci.org (for open source projects) into travis-ci.com (previously only for commercial projects). This migration has been possible already for some time as a "beta feature". But now there is a deadline: December 31, 2020, they will shutdown travis-ci.org. So projects using travis-ci.org are well advised to migrate before that at a convenient time, to avoid hassle. I've done this several times for multiple projects and can try to provide some assistance.

Details can be found [in this email](https://mailchi.mp/3d439eeb1098/travis-ciorg-is-moving-to-travis-cicom?e=%5BUNIQID%5D) and [here you can find migration instructions](https://docs.travis-ci.com/user/migrate/open-source-repository-migration). In my experience, migration is really easy and smooth, but YMMV.

Oh and of course afterwards, URLs in e.g. the README.md (for status badges) and on external websites etc. need to be adjusted.

**Comment by fingolfin** [comment]
@wbhart AFAICT, no Travis is running anymore on Flint PRs, so I assume all free OSS credits for Travis in this repository were used up. Time to migrate from Travis to GitHub Actions?

**Comment by wbhart** [comment]
@fingolfin I don't think that is true.

https://travis-ci.org/github/wbhart/flint2/builds/744697421

However, thanks for the heads up. I intend to migrate before the end of the year.

**Comment by wbhart** [comment]
Done. Also for mpir and antic.
