### ISSUE TITLE
Code conventions: permit C99 fixed-width integer types

### ISSUE THREAD

**Issue by jscott0** [wbhart/flint2#857]
Hi,

I articulated these considerations [as an Arb issue](https://github.com/fredrik-johansson/arb/issues/352) but discussion seems to be more relevant here. FLINT and friends defer to C89 for portability's sake, but without the C99 integer types, it's necessary to make assumptions about the built-in types that also potentially restrict portability. In fact it seems the reason why `int` is 32-bit on 64-bit systems is primarily to [avoid breakage with software making that assumption](http://www.unix.org/whitepapers/64bit.html).

It would be better to replace, where appropriate, `char`, `short`, and `int` with `int8_t`, `int16_t`, and `int32_t` respectively. This would make the code more clean by self-documenting the need for two's complement representation and exact width. Python's similar [C coding standards](https://www.python.org/dev/peps/pep-0007/#c-dialect) allow for this exemption.

**Comment by wbhart** [comment]
C99 never took off. Microsoft for example never produced a fully C99 compliant compiler. The only way to enforce this is with -ansi -pedantic. And it is my understanding that this prevents us from doing this.

Besides, replacing int with int32_t is hardly an improvement. I think the time is not right for this.

**Comment by jscott0** [comment]
> C99 never took off. Microsoft for example never produced a fully C99 compliant compiler.
I don't think any compiler is fully compliant. GCC doesn't support the floating point pragmas (although I think Clang fares slightly better). If any C compiler or standard library combination were to not support these types, then sending patches would be trivial; and although Microsoft's compilers do support these, I think the fact that patches can't be sent in is a limitation of using a proprietary compiler, one which we are unable to fix ourselves.

> The only way to enforce this is with -ansi -pedantic. And it is my understanding that this prevents us from doing this.
The fixed-width integer types are usually just provided as typedefs to the compiler types, and are not excluded from compilers running in C89 mode. (Guarding every definition in a `__STDC_VERSION__` comparison would be painful.) Also these types are still in C11, which [Visual Studio now supports all the required components of](https://devblogs.microsoft.com/cppblog/c11-and-c17-standard-support-arriving-in-msvc/); they say that even support for C11 threads will be arriving soon, but due to their distaste for variable-length arrays, it's intentional that they will never support C99.

**Comment by wbhart** [comment]
We don't typically use char, short and int for arithmetic, so changing them seems pointless. As for 32/64 bit types, we use our own slong/ulong. So this seems redundant to me. I'm going to close this issue, as I don't think it is possible to do what you want with -ansi -pedantic and I don't think we need it anyhow.
