### ISSUE TITLE
fmpz_mat/test/t-print_read is segfaulting

### ISSUE THREAD

**Issue by wbhart** [wbhart/flint2#864]
There are also a lot of warning messages when compiling the test.

The problems occur on Ubuntu 20.04.1 with gcc 9.3.0. (WSL as it happens, but this should not be relevant.)

**Comment by tthsqe12** [comment]
Is this not the same as https://github.com/wbhart/flint2/issues/847?

**Comment by wbhart** [comment]
It's very similar, but not the same segfaulting test.
