### ISSUE TITLE
Argument order for fmpz_mat_scalar_mul_**

### ISSUE THREAD

**Issue by plut** [wbhart/flint2#888]
According to [the documentation](http://flintlib.org/sphinx/fmpz_mat.html#types-macros-and-constants), the call `fmpz_mat_scalar_mul_si(A, B, c)` realizes the operation *B <- c\*A*. This order of parameters is not consistent with, for example, the `fmpz_***` calls (where the pointer to the lvalue comes first), and moreover a quick trial shows that what actually happens is *A <- c\* B*. (This also seems to be what the `Nemo.jl` author believed for instance).

Is the order indicated in the documentation wrong? Even if it is right, it deserves at least a little sentence of clarification, pointing out that the argument order is not the same as e.g. `fmpz_mul`.

**Comment by wbhart** [comment]
An initial examination leads me to conclude that all the prototypes in that section are incorrect. The A and B should be swapped in all cases. Thanks for reporting this. Feel free to open a PR to switch these if you would like to contribute. The docs are of course in doc/source/fmpz_mat.rst

**Comment by wbhart** [comment]
Fixed in trunk. Docs need updating online of course.
