### ISSUE TITLE
FLINT_LIBNAME symlink doesn't get cleaned

### ISSUE THREAD

**Issue by SnarkBoojum** [wbhart/flint2#889]
In Makefile.in, there is code to create the FLINT_LIBNAME symlink, there is code to install it... but no code to clean it ;  I received a [bug report](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=979465) about it.

**Comment by wbhart** [comment]
Thanks. I will take a look into that.

**Comment by wbhart** [comment]
In clean there is:

rm -f $(wildcard $(FLINT_LIBNAME)*)

I'm not sure why that doesn't clean it up. It looks like $(FLINT_LIBNAME) and $(FLINT_LIBNAME).$(FLINT_MAJOR) are created, both of which should be deleted by the above.

**Comment by wbhart** [comment]
I'm unable to replicate this. The symlinks are cleaned up for me.

I assume it was fixed in trunk at some point as indicated in the downstream bug report.
