### ISSUE TITLE
test code in fq_poly_templates for {x}gcd{_f} does not test aliasing

### ISSUE THREAD

**Issue by tthsqe12** [wbhart/flint2#890]
And there are bugs in the code that would be revealed by testing aliasing.

**Comment by wbhart** [comment]
Fixed in trunk (as soon as the GitHub brownout is over).

**Comment by tthsqe12** [comment]
Huh? Did you fix any bugs in the code? There were bugs in the code...

**Comment by wbhart** [comment]
The aliasing tests now pass.

**Comment by tthsqe12** [comment]
Any they didn't pass before?

**Comment by wbhart** [comment]
Take a look at the title of the issue!

**Comment by tthsqe12** [comment]
read the next line :)

> And there are bugs in the code that would be revealed by testing aliasing.

**Comment by tthsqe12** [comment]
I will have a look at this.

**Comment by wbhart** [comment]
No bugs were specified in the issue, so I've no idea if the specific issues you are talking about are fixed.

**Comment by tthsqe12** [comment]
Ok I see e68c5b2 now. All is well.
