### ISSUE TITLE
fmpz_jacobi does not compute jacobi symbol

### ISSUE THREAD

**Issue by wbhart** [wbhart/flint2#895]
Currently it is restricted to prime denominator because for small components it calls n_jacobi which has the following restrictions:

* positive denominator
* numerator and denominator coprime
* denominator odd

It's fine for a Jacobi symbol to require the denominator to be odd and positive, however GMP does not mention the requirement for the denominator to be positive in its documentation.

**Comment by thofma** [comment]
Thanks.

PS: GMP does not mention the positive requirement *and* the coprime requirement. It only mentions that the denominator must be odd.

**Comment by wbhart** [comment]
Yes, but my comment was in relation to what Jacobi defined, not what we defined, which is certainly incorrect.

**Comment by thofma** [comment]
Ah, I misread. Sorry for the misunderstanding.
