### ISSUE TITLE
Random generator seed

### ISSUE THREAD

**Issue by louisaslett** [wbhart/flint2#93]
Superb library and really enjoying using it -- many thanks to all the devs!

I've an issue I hope someone can assist with: looking at the source in `flint.h` it seems that `flint_randinit()` sets the seed to a fixed value.  Is there any API for selecting a different seed?  Using `frandxx` the return from `frandxx::_data()` is const so I can't see a way to manually change it (if that were even advisable?).

Thanks!

**Comment by wbhart** [comment]
There is now a flint_randseed function in flint.h (undocumented), which allows two random ulongs (32 or 64 bits, depending on ABI) to be provided as seeds for the random generator.
