### ISSUE TITLE
xgcd does not give minimal solution

### ISSUE THREAD

**Issue by albinahlback** [wbhart/flint2#948]
By running this extremly advanced C-code
```c
#include "flint/flint.h"
#include "flint/fmpz.h"

int main(int argc, char* argv[])
{
    fmpz_t x, y, a, b, d;

    fmpz_init(x); fmpz_init(y);
    fmpz_init(a); fmpz_init(b);
    fmpz_init(d);

    fmpz_set_str(a, argv[1], 10);
    fmpz_set_str(b, argv[2], 10);

    fmpz_xgcd(d, x, y, a, b);

    flint_printf("Solution to    x a + y b = d    is\n    ");
    fmpz_print(x); flint_printf(" * "); fmpz_print(a);
    flint_printf(" + ");
    fmpz_print(y); flint_printf(" * "); fmpz_print(b);
    flint_printf(" = ");
    fmpz_print(d);
    flint_printf("\n");

    fmpz_clear(x); fmpz_clear(y);
    fmpz_clear(a); fmpz_clear(b);
    fmpz_clear(d);

    return 0;
}
```
one obtain that
```
$ ./a.out 14 12
Solution to    x a + y b = d    is
    -11 * 14 + 13 * 12 = 2
```
However, the minimal solution (x, y) is (1, -1).

This could easily be fixed via [the solutions to Bézout's identity](https://en.wikipedia.org/wiki/B%C3%A9zout%27s_identity#Structure_of_solutions). This would cost some extra lines of code, so if this were to be implemented, should it be implemented in a different function?

Edit: Noticed there is a linked issue to this on Nemo: https://github.com/Nemocas/Nemo.jl/issues/921

**Comment by wbhart** [comment]
What is the definition of minimal?

GMP already guarantees something. I'm not sure why we are getting these values, but probably it is just the ulong version of xgcd which is returning solutions like this. I think it currently guarantees s is reduced mod b and t reduced mod a. But this is not enough if a and b are not coprime.

**Comment by albinahlback** [comment]
Hmm, I see what you are saying, but it doesn't appear to make a difference if it is large or not. 

I interpret the minimal solution (x, y) to be the pair minimizing |x| + |y|.

Running my pull request and this code in Julia
```julia
using Nemo

function xgcd_minimal(a::fmpz, b::fmpz)
  d = fmpz()
  x = fmpz()
  y = fmpz()
  ccall((:fmpz_xgcd_minimal, :libflint), Nothing,
        (Ref{fmpz}, Ref{fmpz}, Ref{fmpz}, Ref{fmpz}, Ref{fmpz}), d, x, y, a, b)
  return d, x, y
end

function xgcd(a::fmpz, b::fmpz)
  d = fmpz()
  x = fmpz()
  y = fmpz()
  ccall((:fmpz_xgcd, :libflint), Nothing,
        (Ref{fmpz}, Ref{fmpz}, Ref{fmpz}, Ref{fmpz}, Ref{fmpz}), d, x, y, a, b)
  return d, x, y
end
```
gives me
```
julia> a = ZZ("9871263987162893761872638761827368712")
9871263987162893761872638761827368712

julia> b = ZZ("912873981729837767467182781277771876")
912873981729837767467182781277771876

julia> h = xgcd_minimal(a, b)
(4, 84272065771350158899489588688430992, -911266861167636480378684148157469175)

julia> g = xgcd(a, b)
(4, -828601915958487608567693192589340884, 8959997125995257281493954613669899537)

julia> abs(h[2]) + abs(h[3])
995538926938986639278173736845900167

julia> abs(g[2]) + abs(g[3])
9788599041953744890061647806259240421      <--- This is bigger by a magnitude of 10
```
and
```
julia> a = ZZ("9871263987162893761872638761827368712871263871263876172637126837681276387618276387618726387626327636112")
9871263987162893761872638761827368712871263871263876172637126837681276387618276387618726387626327636112

julia> b = ZZ("987126398716289376187263876182736871287126387126387617263712683768127638761827638761872638762632763611271827398")
987126398716289376187263876182736871287126387126387617263712683768127638761827638761872638762632763611271827398

julia> h = xgcd_minimal(a, b)
(2, -234762622107860169103638162207302704653887194906917052292445591781281050936768299915225917208671305275517082299, 2347626221078601691036381622073027046538871949069170522924455917812810509367682999152259172086713052755)

julia> g = xgcd(a, b)
(2, 752363776608429207083625713975434166633239192219470564971267091986846587825059338846646721553961458335754745099, -7523637766084292070836257139754341666332391922194705649712670919868465878250593388466467215539614583357)

julia> abs(h[2]) + abs(h[3])
234762624455486390182239853243684326726914241445789001361616114705736968749578809282908916360930477362230135054

julia> abs(g[2]) + abs(g[3])
752363784132066973167917784811691306387580858551862487165972741699517507693525217097240110020428673875369328456
```
If my math is correct, the solutions from `xgcd_minimal` are in both cases element-wise smaller than the ones from `xgcd`. Moreover, `xgcd_minimal` gives the same solution as Nemo's `gcdx` in both cases.

**Comment by wbhart** [comment]
Ah yes, I see, even GMP's mpz_gcdext doesn't try to give the minimal solution.

```
julia> a = ZZ(9871263987162893761872638761827368712)
9871263987162893761872638761827368712

julia> b = ZZ(912873981729837767467182781277771876)
912873981729837767467182781277771876

julia> g, s, t = gcdx(a, b)
(4, 84272065771350158899489588688430992, -911266861167636480378684148157469175)

julia> abs(s) < div(abs(b), 2g)
true

julia> abs(t) < div(abs(a), 2g)
true
```

So that solution satisfies the inequalities in the GMP manual, but is still not minimal according to your definition.

I am more than happy to add this function to Flint, so long as the definition of minimal is documented, and so long as all corner cases are carefully documented and tested, e.g. abs(a) == abs(b), a = 0, b = 0, a | b, b | a, a = b = 0, etc.

However, we cannot replace the existing definition of fmpz_gcdext in Flint with the new one because that existing implementation has been in use a long time and it will break people's code to switch the definition. In particular we rely on the current behaviour in Nemo/Oscar.

I don't know if your solution will always satisfy the inequalities in the GMP manual. But those inequalities are useful because they give solutions that lie in the least absolute remainder system, s being minimal mod b, t being minimal mod a. That behaviour is useful in modular arithmetic.

**Comment by wbhart** [comment]
Note that the example you give of coprime values not leading to minimal solution is not really relevant. It does not satisfy the GMP inequalities:

```
julia> g == a*s + b*t
true

julia> abs(s) < div(abs(b), 2g)
false

julia> abs(t) < div(abs(a), 2g)
false
```

I believe that the solution is unique (wrt those inequalities) if the inputs are coprime. I think one can prove from there that this means it is the minimal solution.

**Comment by albinahlback** [comment]
> However, we cannot replace the existing definition of fmpz_gcdext in Flint with the new one because that existing implementation has been in use a long time and it will break people's code to switch the definition. In particular we rely on the current behaviour in Nemo/Oscar.

I don't see `fmpz_xgcd` or `fmpz_gcdext` being implemented in Nemo.

> I am more than happy to add this function to Flint, so long as the definition of minimal is documented, and so long as all corner cases are carefully documented and tested, e.g. abs(a) == abs(b), a = 0, b = 0, a | b, b | a, a = b = 0, etc.
Yes, documentation is a must for this.
> s < div(abs(b), 2 g) etc ...
Yes, I think this is what we should mean by minimal, you're right.

**Comment by wbhart** [comment]
fmpz_gcdinv is implemented in Nemo using Flint and the definition should in theory agree with fmpz_xgcd. If you change the definition of one then the other will not necessarily agree without some care.

There's also Sage and Macaulay 2 which use Flint, not to mention many other independent projects. I'm really reluctant to just break everyone's code if there is not a call for this.

I don't know how easy it is to have Flint's fmpz_xgcd agree perfectly with GMP's even for small integers. At the moment it just returns results which satisfy the same inequalities as documented in the GMP manual. Those are only unique when the inputs are coprime.

**Comment by albinahlback** [comment]
I understand what you are saying. I think the first problem before any of this is to implement a fast version if both `a` and `b` are small, and then we can see if it's worth to do the change `xgcd_minimal -> xgcd`. However, if you think it is a good idea to keep the current `xgcd`, I am all for it.

**Comment by wbhart** [comment]
It is already fast in the small case. It calls fmpz_gcdinv which calls our n_gcdinv. This ensures the two functions agree.

However, it does not return minimal values in the sense that you want. If you can find an application for that, I'm perfectly happy having an fmpz_xgcd_minimal. Just implementing it for no particular reason isn't a good strategy though. It'll just annoy people using Flint already.
