### ISSUE TITLE
`make profile` generate errors

### ISSUE THREAD

**Issue by albinahlback** [wbhart/flint2#958]
On Arch with the obligatory dependencies GMP and MPFR, running `make profile` generate errors.

Two of them are the undefined references to `openblas_set_num_threads` in both `nmod_mat/profile/p-mul.c` and `fmpz_mat/profile/p-mul_blas_v_mul.c`. I suppose this is because I don't use BLAS. I'm gonna ping @tthsqe12 for this one.

The last one is `fq_nmod_poly/profile/p-factor_kaltofen_shoup_vs_fq_poly.c`, where `fmpz_mod_poly_get_fmpz_poly` appears to have one less argument than in the declaration.

(I also get a lot of warnings, but I suppose I shouldn't worry about them.)

Edit: The first error in `fmpz_mat/profile/p-mul_blas_v_mul.c` now seems to have gone away, which is logical. I actually don't know how it arose during the first run.

**Comment by tthsqe12** [comment]
Some of the profiling code is in bad shape and may or may not work. You just need `make profile MOD=fmpz && ./build/fmpz/profile/p-my_stuff`.

**Comment by wbhart** [comment]
I have removed the one compiler error (which looked like a cut'n'pasta error) and I removed all the unused variables.

However I can't really get rid of set but unused warnings or the string overrun warnings, as those are intentional abuses.
