### ISSUE TITLE
Flint not compatible with latest GMP

### ISSUE THREAD

**Issue by MSoegtropIMC** [wbhart/flint2#960]
In latest GMP (6.2.1) the function `__gmpn_get_d` has been removed, which is used in 3 functions in flint:
```
fmpz_get_d_2exp(slong *exp, const fmpz_t f)
double fmpz_get_d(const fmpz_t f)
double flint_mpf_get_d_2exp(slong * exp2, mpf_srcptr src)
```
On the other hand, the function `mpf_get_d_2exp` for which flint has a GMP compatibility wrapper, is now available in GMP.

Since one cannot install both GMP and MPIR, GMP compatibility would be nice.

**Comment by wbhart** [comment]
Thanks for the report. We'll look into it for the next Flint release. Unfortunately the first two functions cannot be implemented in terms of `mpf_get_d_2exp`, so we will have to make some very old version of the function part of Flint.

**Comment by fredrik-johansson** [comment]
Has it though? I still see https://gmplib.org/repo/gmp/file/tip/mpn/generic/get_d.c

**Comment by wbhart** [comment]
I can confirm the files are still there in GMP-6.2.1. The functions are not exported in gmp.h, but we already knew that, which is why we declare them extern in the above files.

If this is causing a linker issue somehow, please let us know. In the meantime I will close this issue as invalid.

**Comment by wbhart** [comment]
I've also checked that mpn_get_d is still in gmp_mpn_functions in configure.

**Comment by MSoegtropIMC** [comment]
Sorry, I somehow didn't see your previous messages.

Yes, I do get a linker error. I will investigate why.

I didn't mention it, but I have these issues on Windows with shared libraries (DLLs), so the likely cause is that the function is not exported from the DLL. On Windows (unlike Linux) one has to explicitly name the functions, which shall be accessible in a DLL. Since the function is not documented, it would be a reasonable choice to not export it. This should be solvable with a minor patch to GMP.

**Comment by wbhart** [comment]
Ah yes, this would be an issue on Windows. I don't know why that didn't occur to me.

I am not sure if GMP would export this for Windows if they are not doing so for other OS's. I think we have to add mpn_get_d to our Flint compatibility layer (gmp_compat.h) to keep using it. I will reopen the issue.

**Comment by MSoegtropIMC** [comment]
Well on Linux and MacOS it is implicitly exported (because everything is exported) - so why not explicitly export it on Windows?

Long term of course the best alternative would be to think about how the GMP interface would have to change, so that Flint can live without depending on internal features of it.

**Comment by wbhart** [comment]
It's bizarre that our continuous integration tests have been passing on Windows 64 bits. This has been the state of affairs for a long time.

**Comment by MSoegtropIMC** [comment]
Maybe you test with static libraries? This would be different then. I can also have a look at what you test in your CI - maybe I am just doing something silly.

**Comment by wbhart** [comment]
Perhaps we still use MPIR on Windows. I didn't check that actually.

**Comment by wbhart** [comment]
Fixed in trunk.

**Comment by MSoegtropIMC** [comment]
Thanks! I will test it over the weekend.
