### ISSUE TITLE
Figure out problem with Appveyor CI (CMake?)

### ISSUE THREAD

**Issue by wbhart** [wbhart/flint2#968]
Seems to be some GMP issue.

**Comment by fingolfin** [comment]
Or perhaps instead use GitHub Actions to test in Windows and ditch AppVeyor?

**Comment by wbhart** [comment]
I think the issue is real. It seems to be some GMP issue.

But yes, we should probably also switch to GitHub actions on Windows too. It would increase the bus factor though. At least if one goes down, we still have the other.

**Comment by wbhart** [comment]
Fixed by https://github.com/wbhart/flint2/pull/973
