### ISSUE TITLE
nmod_mat_print_pretty() prints garbage

### ISSUE THREAD

**Issue by krisk0** [wbhart/flint2#99]
If flint-2.4.4 is compiled with gcc (Gentoo 4.7.3-r1 p1.3, pie-0.5.5) 4.7.3, subroutine nmod_mat_print_pretty() prints format string such as "%%20lu" instead of matrice entries. This defect makes the subroutine mostly useless (no matrice entries printed).

I offer patch which worked for me (untested under Windows):
```
--- nmod_mat/print_pretty.c.old	2014-09-04 12:51:51.000000000 +0400
+++ nmod_mat/print_pretty.c	2014-09-04 13:15:30.000000000 +0400
@@ -45,8 +45,14 @@
 
     width = n_sizeinbase(mat->mod.n, 10);
 
-    flint_sprintf(fmt, "%%%dlu", width);
-
+    #if defined(_WIN64)
+     #define TAIL "llu"
+    #else
+     #define TAIL "lu"
+    #endif
+    flint_sprintf(fmt, "%c%d%s", '%', width, TAIL );
+    #undef TAIL
+    
     for (i = 0; i < mat->r; i++)
     {
         flint_printf("[");
```

**Comment by wbhart** [comment]
I've taught flint_printf about specific width specifiers and checked nmod_mat_print_pretty works as expected.
