### ISSUE TITLE
Building 2.8.0 documentation failuresI

### ISSUE THREAD

**Issue by SnarkBoojum** [wbhart/flint2#990]
Now that Debian 11 is out, I can finally resume packaging new flint versions. And I have a hard time building 2.8.0's doc. To reproduce, just go in the doc/ directory and "make latexpdf":
```
[52]
! Misplaced \omit.
\math@cr@@@ ...@ \@ne \add@amps \maxfields@ \omit 
                                                  \kern -\alignsep@ \iftag@ ...
l.6881 \end{align*}\end{split}
                              
? 
```
it is even asking for input ('q' is the usual answer) before erroring out.

**Comment by SnarkBoojum** [comment]
The code looks like:
```
\begin{equation*}
\begin{split}\newcommand{\xgcd}{\operatorname{xgcd}}
\newcommand{\sgn}{\operatorname{sgn}}
\begin{align*}
    \xgcd(\pm g, g) &= \bigl(|g|, 0, \sgn(g)\bigr)\\
    \xgcd(f, 0) &= \bigl(|f|, \sgn(f), 0\bigr)\\
    \xgcd(0, g) &= \bigl(|g|, 0, \sgn(g)\bigr)\\
    \xgcd(f, \mp 1) &= (1, 0, \mp 1)\\
    \xgcd(\mp 1, g) &= (1, \mp 1, 0)\quad g \neq 0, \pm 1\\
    \xgcd(\mp 2 d, g) &=
        \bigl(d, {\textstyle\frac{d - |g|}{\mp 2 d}}, \sgn(g)\bigr)\\
    \xgcd(f, \mp 2 d) &=
        \bigl(d, \sgn(f), {\textstyle\frac{d - |g|}{\mp 2 d}}\bigr).
\end{align*}\end{split}
\end{equation*}
```
and is followed by:
```
\begin{equation*}
\begin{split}\begin{equation*}
    |a| < \Bigl| \frac{g}{2 d} \Bigr|,
    \qquad \Bigl| |b| < \frac{f}{2 d} \Bigr|.
\end{equation*}\end{split}
\end{equation*}
```
both of which have three levels of equation* split and align*! If I edit the file to keep only the innermost, and try to run (by hand) pdflatex Flint.tex, then I get much further before hitting another wall.

**Comment by SnarkBoojum** [comment]
Lines 20237 and 32230 there's a "\time" instead of a "\times". After the previous changes and that one, I get the pdf to compile.

**Comment by SnarkBoojum** [comment]
The first batch comes from fmpz.rst, and it's the documentation of fmpz_canonical_bezout which opens a math environment and then proceeds to put plain code as if it weren't already in math-mode. I don't know how to fix it yet.

The second batch is a one-liner in two files, I have a patch ready for this part.

**Comment by SnarkBoojum** [comment]
Here is a pre-patch ; I'm still working on it:
[unbreak_doc.txt](https://github.com/wbhart/flint2/files/7013924/unbreak_doc.txt)

**Comment by wbhart** [comment]
Thanks for looking at this. I believe this was fixed in trunk and that there will be a 2.8.1. I was actually unaware anyone was still using it.

**Comment by SnarkBoojum** [comment]
Ah, I hadn't seen the new unbreaking commits. Sorry for the noise.

What do you mean by "I was actually unaware anyone was still using it." ?

**Comment by wbhart** [comment]
I meant I didn't know the pdf was still being built. I thought everyone just used the web documentation. But it's no problem to keep up-to-date in future.

**Comment by SnarkBoojum** [comment]
Hmmm...

**Comment by SnarkBoojum** [comment]
I'm surprised, because in 2.8.3, the patch I have in Debian, based on commit 7f57344cb8f762df7096522f9fb7eaa920e138a3 by David Einstein still applies perfectly -- that shouldn't be the case, should it? [Here it is, for reference.](https://salsa.debian.org/math-team/flint/-/blob/master/debian/patches/unbreak_doc.patch)

**Comment by wbhart** [comment]
I don't know. Was there a PR? The issue seems to have gotten closed at some point, but I don't recall why.

**Comment by wbhart** [comment]
Oh I see, I commented that this was fixed in trunk. I think there has been some miscommunication.

We probably don't have this after all.

**Comment by wbhart** [comment]
Yeah looking at this now, I have *no idea* how a patch that was clearly applied, still applies. Anyway, I'm applying it again right now.
