### ISSUE TITLE
Copyright assignments

### ISSUE THREAD

**Issue by SnarkBoojum** [wbhart/flint2#993]
Updating the Debian package also implies checking the copyright assignments ; I found the following two strange things:
1. ./fmpz/kronecker.c Copyright (C) 2021 Dnaiel Schultz (typo)
2. ./fq_zech_mat/test/t-set_fmpz_mod_mat.c ./fq_zech_mat/test/t-set_nmod_mat.c Copyright (C) 2021 (no name!)

**Comment by wbhart** [comment]
Thanks, we'll correct both of these.
