### ISSUE TITLE
Precached FFT for fmpz_polyxx

### ISSUE THREAD

**Issue by hilder-vitor** [wbhart/flint2#995]
Hello!

Is there a way of precomputing the FFT, like [this](http://flintlib.org/doc/fmpz_poly.html#fft-precached-multiplication) but using the "C++ polynomial" fmpz_polyxx instead of the "C polynomial" fmpz_poly_t?

I already searched on the documentation, but could not find it.

Thank you very much!

**Comment by wbhart** [comment]
No, sorry. The fft precaching is not currently wrapped in the C++ layer. That would be quite difficult to do I think.

**Comment by hilder-vitor** [comment]
OK, I understand. Thanks anyway.
